Adyen/adyen-android

- .github/workflows/publish_release.yml
This seems to be what is making the release Action fail.
https://github.com/Adyen/adyen-android/runs/1263961604
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
...
at com.jfrog.bintray.gradle.tasks.BintrayPublishTask.gpgSignVersion(BintrayPublishTask.groovy:73)
> Add back GPG passphrase to release.

- .github/workflows/publish_release.yml
- config/gradle/release.gradle
Failure on publish action happens when trying to sign the artifacts.
Which is useless since we don't have a GPG key setup for this project yet.
> Disable signing on Bintray task.

- .github/workflows/check_pr.yml
- .github/workflows/check_release.yml
- .github/workflows/publish_release.yml
On older release branches we only have 1 branch for dev and releases. 
The branch will accept PRs from feature branches, and releases will be triggered manually on the Actions.
> Update Actions for manual releases on V3 branch.

- example-app/build.gradle
- example-app/default.local.gradle
- example-app/src/main/java/com/adyen/checkout/example/data/api/CheckoutApiService.kt
- example-app/src/main/java/com/adyen/checkout/example/di/NetworkModule.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
Allow local.gradle to be untracked by Git again.
Using default.local.gradle with default values for CI builds.
Fail gracefully on App if MERCHANT_SERVER_URL is not properly setup on local.gradle file.
> Fix local.gradle

- base-v3/src/main/java/com/adyen/checkout/base/analytics/AnalyticsDispatcher.java
- core-v3/src/main/java/com/adyen/checkout/core/api/Connection.java
Since we updated min API version we can use this resource now.
> Use try-with-resources to auto close InputStreams.

- CHANGELOG.md
- RELEASE_NOTES.md
- build.gradle
This alpha release has our migration to AndroidX for people who want to get rid of jetifier and help test new changes.
We will still be adding to this version so public APIs might still change in the future, that's why it's in `alpha`.
#217
> Release 4.0.0-alpha01

- base-v3/src/main/java/com/adyen/checkout/base/component/BasePaymentComponent.java
- card-base-core/src/main/java/com/adyen/checkout/card/data/CardType.java
- card-base/src/main/java/com/adyen/checkout/card/CardComponent.java
- card-base/src/main/java/com/adyen/checkout/card/CardConfiguration.java
- card-base/src/main/java/com/adyen/checkout/card/CardOutputData.java
- card-ui/src/main/java/com/adyen/checkout/card/CardView.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/BaseComponentDialogFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- Allow CardComponent to not request CVC for regular and stored card flows.
- Create `hideCvc` and `hideCvcStoredCard` flags on `CardConfiguration`
- Automatically hide the CVC field on stored BCMC cards.
- Remove relying on `InputDetails` for CVC optionality.
Tested BCMC card on regular and stored flows.
Tested Visa card on regular and stored flows.
> Allow CardComponent to not request CVC

- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
- Add `threeDS2RequestData` with `challengeIndicator:requestChallenge` to force challenge flow.
https://docs.adyen.com/api-explorer/#/CheckoutService/v65/post/payments__reqParam_threeDS2RequestData-challengeIndicator
> Add option to force 3DS2 Challenge on payment request.

- base-v3/build.gradle
- base-v3/src/main/java/com/adyen/checkout/base/ActionComponentProvider.java
- base-v3/src/main/java/com/adyen/checkout/base/PaymentComponentProvider.java
- base-v3/src/main/java/com/adyen/checkout/base/StoredPaymentComponentProvider.java
- base-v3/src/main/java/com/adyen/checkout/base/component/ActionComponentProviderImpl.java
- base-v3/src/main/java/com/adyen/checkout/base/component/PaymentComponentProviderImpl.java
- base-v3/src/main/java/com/adyen/checkout/base/component/lifecycle/PaymentComponentViewModelFactory.java
- bcmc-base/src/main/java/com/adyen/checkout/bcmc/BcmcComponentProvider.java
- build.gradle
- card-base/src/main/java/com/adyen/checkout/card/CardComponentProvider.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ActionHandler.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- example-app/build.gradle
- googlepay-base/src/main/java/com/adyen/checkout/googlepay/GooglePayProvider.java
- wechatpay-base/src/main/java/com/adyen/checkout/wechatpay/WeChatPayProvider.java
- Update the Payment and Action Component Providers to use `ViewModelProvider`.
- Merge `PROVIDER` get methods for Activity and Fragment into  ViewModelStoreOwner.
- Create `StoredPaymentComponentProvider` to separate initialization with `PaymentMethod` and `StoredPaymentMethod` to prepare for API model separation.
- Remove deprecated methods.
> Update Component Providers

- base-v3/src/main/java/com/adyen/checkout/base/component/BaseConfigurationBuilder.java
- base-v3/src/main/java/com/adyen/checkout/base/component/Configuration.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
When no Configuration is defined for a payment method on the Drop-in, it creates a base generic one if possible. 
It sets the `clientKey` from the `DropInConfiguration` to propagate it automatically, but if there is no `clientKey` defined it tries to set the default emtpy value and throws the validation exception.
Fix: Only set the `clientKey` on generic configurations if it's not empty.
- Reproduced issue and confirmed the problem
- Tested flow with and without the clientKey
> Fix clientKey validation for BaseConfiguration on DropIn.

- README.md
- Removed a deprecated call to `CardConfiguration.Builder` in the components section sample.
- Added a link to the docs for a more detailed explanation on how to init the builder.
> Fix CardConfiguration readme sample

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInExtensions.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodsListViewModel.kt
- Move the logic of the Payment Methods list out of DropInViewModel to it's own.
- Add extension functions to initialize ViewModels with Factory (thx @jreij)
> Separate DropInViewModel and the fragment specific ViewModels.

- googlepay-base/build.gradle
- Make Google Pay wallet dependency visible to merchants so that they can have access to the `WalletConstants`.
> Make Google Pay wallet depenency visible.

- gradle.properties
- Gradle check was giving OOM errors and taking a long time. Increase available memory on the JVM.
> Increase memory for the gradle JVM to speed up builds.

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcView.java
- card/src/main/java/com/adyen/checkout/card/CardView.java
Hide the card brand logo icon when the card number input is invalid, because the logo icon and the error icon are overlapping.
> Hide card brand logo icon on error

- CHANGELOG.md
- RELEASE_NOTES.md
- build.gradle
- Remove configuration object from /paymentmethods model breaking serialization in some API versions.
> Release 3.8.2

- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/BaseComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/DropInBottomSheetDialogFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ResultActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
Currently the only way to handle the drop in successful response is with the `resultHandlerIntent`. We want to allow the option to handle the drop in solely using `onActivityResult`:
* Make `resultHandlerIntent` optional.
* Return the result using `setResult` if `resultHandlerIntent` is not set.
* Allow fragments to use `startActivityForResult` also.
> DropIn initialization with activityResult

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
When restoring Drop-in from background with "Don't keep activities" the app crashes and some components are not properly initialized.
> Fix activity restore from background issues

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentViewModel.kt
Handle errors from `CardComponent` when directly paying from `PreselectedStoredPaymentMethodFragment`.
> Handle card component error in frictionless payment

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- await/src/main/java/com/adyen/checkout/await/AwaitComponent.java
- await/src/main/java/com/adyen/checkout/await/AwaitView.java
- components-core/src/main/java/com/adyen/checkout/components/ActionComponentProvider.java
- components-core/src/main/java/com/adyen/checkout/components/base/ActionComponentProviderImpl.java
- components-core/src/main/java/com/adyen/checkout/components/base/BaseActionComponent.java
- components-core/src/main/java/com/adyen/checkout/components/util/PaymentMethodTypes.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ActionHandler.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodsListViewModel.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponent.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.java
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponent.java
- Split `getConfigurationFor` in 2 methods: payment method and action.
- Add handling for payment methods that do not require a payment component.
- Validate payment method types inside action components.
> Split action configurations handling from payment method configurations

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
This field was introduced in version 2.2.0 so older protocols don't expect it to be present and might throw an error.
> Don't pass threeDSRequestorAppURL on challenges in version 2.1.0

- card/src/main/java/com/adyen/checkout/card/CardView.kt
Don't set window FLAG_SECURE in Debug builds to allow for screenshots and recording.
Fixes #380
> Don't set window FLAG_SECURE in Debug builds

- CHANGELOG.md
- RELEASE_NOTES.md
- build.gradle
- Enable showing Postal Code input in Card component.
- Release to Maven Central.
- Update Google Pay logo.
- Update 3DS2 SDK to version `2.1.0-rc09` which fixes restricted security exceptions on Android 10.
> Release 3.8.3

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/NewCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/api/BinLookupConnection.kt
- card/src/main/java/com/adyen/checkout/card/repository/BinLookupRepository.kt
Call BinLookup every time the  Card number is big enough.
Caching is handled by the repository to avoid doing multiple calls.
Fix properly updating the `CardOutputData` when the binLookup flow is emitted to reflect the UI state correctly.
> Call Bin Lookup every time

- RELEASE_NOTES.md
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.java
- googlepay/src/main/java/com/adyen/checkout/googlepay/model/GooglePayParams.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/util/GooglePayUtils.java
Adding TotalPriceStatus to the GooglePayConfiguration allows merchants to override that property.
> Add TotalPriceStatus to GooglePayCofing

- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
Adding the `threeDSAuthenticationOnly` flag allows us to make payment calls that don't charge the card.
This call will only ask for a Card Authentication. More info [here](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_threeDSAuthenticationOnly).
False by default, can be changed in code for tests. We can add it to the settings screen later.
> Add flag for authentication only payment calls on Example App.

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.kt
- await/src/main/java/com/adyen/checkout/await/AwaitConfiguration.java
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.java
- blik/src/main/java/com/adyen/checkout/blik/BlikConfiguration.java
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.java
- components-core/src/main/java/com/adyen/checkout/components/base/BaseConfigurationBuilder.kt
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayConfiguration.java
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashConfiguration.java
- eps/src/main/java/com/adyen/checkout/eps/EPSConfiguration.java
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.java
- ideal/src/main/java/com/adyen/checkout/ideal/IdealConfiguration.java
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayConfiguration.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayConfiguration.java
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingConfiguration.java
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeConfiguration.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectConfiguration.java
- sepa/src/main/java/com/adyen/checkout/sepa/SepaConfiguration.java
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionConfiguration.java
Instead of passing parameters one by one to the constructors of
Configuration classes pass the builder instance to make it cleaner.
> Pass builder instances while instantiating Configuration classes

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- build.gradle
- config/gradle/checksums.gradle
Update 3DS2 SDK to version `2.2.4` which contains some fixes, new certificates and support for tagetApi 31.
> Update 3DS2 version.

- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInCallback.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInResultContract.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.java
Replace the deprecated `onActivityResult` with AndroidX's [Activity Result API](https://developer.android.com/training/basics/intents/result).
> Use new Activity Result API

- checkout-core/consumer-rules.pro
- components-core/consumer-rules.pro
- example-app/build.gradle
- example-app/proguard-rules.pro
This way merchants don't have to add the ProGuard rules themselves anymore.
> Add ProGuard/R8 consumer rules to the release artifacts.

- googlepay/src/main/java/com/adyen/checkout/googlepay/util/GooglePayUtils.java
Consulted Google as we shouldn't pass in totalPrice when totalPriceStatus is "NOT_CURRENTLY_KNOWN". This is a quick workaround.
Logs from Logcat:
W WalletMerchantError: Error in loadPaymentData: PaymentDataRequest.transactionInfo.totalPrice should not be set for totalPriceStatus = NOT_CURRENTLY_KNOWN!
**Fixed issue**:
> fix: Handle NOT_CURRENTLY_KNOWN flag

- checkout-core/src/main/java/com/adyen/checkout/core/api/Environment.java
Add `LIVE` value to Environment. 
This is identical to the EUROPE value but makes it clearer that a region specfic endpoint is not necessary. 
Brings the Android SDK in line with the iOS one https://github.com/Adyen/adyen-ios/blob/95f158b88630f023b9f3dc71766b53fe9b17477d/Adyen/Core/APIClient/Environment.swift
**Fixed issue**:
> Include `LIVE` in Environment values

- checkout-core/src/main/java/com/adyen/checkout/core/api/Environment.java
- checkout-core/src/main/java/com/adyen/checkout/core/model/ModelObject.java
- checkout-core/src/main/java/com/adyen/checkout/core/util/ParcelUtils.java
- components-core/src/main/java/com/adyen/checkout/components/analytics/AnalyticEvent.java
- components-core/src/main/java/com/adyen/checkout/components/api/LogoApi.kt
- components-core/src/main/java/com/adyen/checkout/components/base/Configuration.kt
- cse/src/main/java/com/adyen/checkout/cse/EncryptedCard.java
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/BaseComponentDialogFragment.kt
If there is only 1 available payment method, and it has a Component, the Drop-in will skip to the Component screen instead of showing the payment methods list.
Merchant can choose to disable this behavior in the DropInConfiguration
> Skip to Component screen if only 1 available

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/BaseComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/DropInBottomSheetDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GenericComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GooglePayComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/ComponentDialogViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInActivityEvent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModelFactory.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/GooglePayViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PaymentMethodsListViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PreselectedStoredPaymentViewModel.kt
- drop-in/src/main/res/layout/fragment_google_pay_component.xml
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
Add the ability to reload the GooglePayComponent with a different configuration in the same drop-in session (e.g. in the gift card flow).
> Reload Google Pay component in drop-in

- checkout-core/src/main/java/com/adyen/checkout/core/util/LocaleUtil.kt
Rely on `Locale.Builder` validate locales, instead of checking the ISO3 language and country.
> Fix Locale validation

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/PaymentComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/base/BasePaymentComponent.kt
- components-core/src/test/java/com/adyen/checkout/components/base/BaseComponentTest.kt
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayComponent.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashComponent.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSComponent.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.kt
- ideal/src/main/java/com/adyen/checkout/ideal/IdealComponent.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponent.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayComponent.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayComponent.kt
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingComponent.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaComponent.kt
Fix crash from call to not initialized `supportedPaymentMethodTypes` in BasePaymentComponent when underlying val was not yet assigned.
> Fix crash when initializing iDeal.

- 3ds2/build.gradle
- await/build.gradle
- bacs/build.gradle
- bcmc/build.gradle
- blik/build.gradle
- card/build.gradle
- checkout-core/build.gradle
- components-core/build.gradle
- config/gradle/checksums.gradle
- dotpay/build.gradle
- drop-in/build.gradle
- entercash/build.gradle
- eps/build.gradle
- example-app/build.gradle
- giftcard/build.gradle
- googlepay/build.gradle
- ideal/build.gradle
- issuer-list/build.gradle
- mbway/build.gradle
- molpay/build.gradle
- openbanking/build.gradle
- qr-code/build.gradle
- redirect/build.gradle
- sepa/build.gradle
- sessions-core/build.gradle
- ui-core/build.gradle
- voucher/build.gradle
- wechatpay/build.gradle
Starting from AGP 4.2 we no longer need to specify sourceCompatibility and targetCompatibility.
https://developer.android.com/studio/releases/gradle-plugin#java-8-default
Since Kotlin 1.5 the default value for jvmTarget is 1.8
https://kotlinlang.org/docs/whatsnew15.html#new-default-jvm-target-1-8
> Small Gradle cleanup.

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/LoadingDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/BacsDirectDebitDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GenericComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GiftCardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/giftcard/GiftCardPaymentConfirmationDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
Holding a reference to a binding in a fragment will cause a memory leak, because the fragment lives longer than the view. Source: https://developer.android.com/topic/libraries/view-binding#fragments
> Remove view binding references when view is destroyed for all fragments

- googlepay/src/main/java/com/adyen/checkout/googlepay/model/GooglePayParams.kt
Try to use the `GooglePayConfiguration.merchantAccount` first before falling back to the `paymentMethod.configuration.gatewayMerchantId` field returned by the API.
> Switch Google Pay gatewayMerchantId priority (develop)

- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayProvider.kt
`onComplete` will always be called even when the task fails. Since we already have `onFailed` and `onCancelled` listeners, we only have to change `onComplete` with `onSuccess`
> Fix crash in GooglePayProvider (v4)

- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponentProvider.kt
`onComplete` will always be called even when the task fails. Since we already have `onFailed` and `onCancelled` listeners, we only have to change `onComplete` with `onSuccess`
> Fix crash in GooglePayComponentProvider (develop)

- drop-in/src/main/AndroidManifest.xml
- example-app/src/main/AndroidManifest.xml
Bonus: mark exported false for all services. Our services shouldn't be started by other applications/processes, so it's better to not export them
> Remove unnecessary permission

- giftcard/build.gradle
- giftcard/src/test/java/com/adyen/checkout/giftcard/DefaultGiftCardDelegateTest.kt
- sessions-core/build.gradle
- sessions-core/src/test/java/com/adyen/checkout/sessions/repository/SessionRepositoryTest.kt
- settings.gradle
- test-core/build.gradle
- test-core/src/main/java/com/adyen/checkout/test/TestDispatcherExtension.kt
- Add `:test-core` module
- Create JUnit extension that replaces the main coroutine dispatcher with a test dispatcher and can provide this dispatchers to tests
- Replace manually replacing the main dispatcher in tests with this new extension
> Add JUnit extension to make coroutine testing easier

- wechatpay/build.gradle
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/DefaultWeChatDelegate.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatDelegate.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponent.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponentProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayRequestGenerator.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayUtils.kt
- wechatpay/src/test/java/com/adyen/checkout/wechatpay/DefaultWeChatDelegateTest.kt
- Move logic from component to delegate
- Extract as much logic from `WeChatPayUtils` to classes that use it
- Wrap generation of `PayReq` in a class, so it's testable
> WeChatDelegate: Create WeChatDelegate

- 3ds2/build.gradle
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Event.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/model/ChallengeResult.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/repository/SubmitFingerprintRepository.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/DefaultAdyen3DS2DelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/encoding/Base64Encoder.kt
- redirect/src/main/java/com/adyen/checkout/redirect/test/TestRedirectHandler.kt
- Move logic from component to delegate
- Split `Base64Encoder` into an interface and two implementations (for testing)
- Small tweaks to make testing easier
> 3DS2Delegate: Create 3DS2Delegate

- config/gradle/checksums.gradle
- dependencies.gradle
Also needed to update AndroidX Fragment to fix the issues caused by the latest Hilt version
> UpdateAndroidXLifecycle: Update AndroidX Lifecycle dependencies to 2.5.1

- README.md
- RELEASE_NOTES.md
- build.gradle
- example-app/build.gradle
- `Online banking Poland` Component
- Update 3DS2 SDK version to `2.2.8`
- Gracefully terminate drop in without crashing when coming back from a redirect after drop-in was closed
- Updating 3DS2 SDK version fixed a crash on Android 13
> Release 4.8.0

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ViewProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/DefaultAdyen3DS2Delegate.kt
- action/src/test/java/com/adyen/checkout/action/TestActionDelegate.kt
- await/src/main/res/layout/await_view.xml
- checkout-core/src/main/java/com/adyen/checkout/core/exception/CancellationException.kt
- components-core/src/main/java/com/adyen/checkout/components/base/ActionDelegate.kt
- components-core/src/test/java/com/adyen/checkout/components/status/DefaultStatusRepositoryTest.kt
- config/gradle/checksums.gradle
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/LazyArguments.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- redirect/src/main/java/com/adyen/checkout/redirect/DefaultRedirectDelegate.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectDelegate.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectViewProvider.kt
- ui-core/build.gradle
- ui-core/src/main/java/com/adyen/checkout/components/ui/PaymentInProgressView.kt
- ui-core/src/main/res/layout/view_payment_in_progress.xml
- wechatpay/build.gradle
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/DefaultWeChatDelegate.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatDelegate.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatViewProvider.kt
- Add `PaymentInProgressView`. It looks a bit like the `AwaitView`, but it might change once we have a final design
- Show this new view for redirect and 3ds2 payment flows
Bonus:
- Make `DefaultStatusRepositoryTest` more stable
- Add extension method to lazily initialise arguments:
```Kotlin
class MyFragment : Fragment() {
// Not so cool way to do it
private val someArgument: ParcelableClass
get() = arguments?.getParcelable(ARG_KEY) ?: throw IllegalStateException("OH NO")
// Cool way to do it 😎 
private val someArgument: ParcelableClass by arguments(ARG_KEY)
...
}
```
> IntermediateActionScreen: Show payment in progress screen for redirect and 3ds2

- config/gradle/checksums.gradle
- dependencies.gradle
- example-app/src/main/res/values-land/styles_bottom_sheet.xml
- ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenSwipeToRevealLayout.kt
- ui-core/src/main/res/values-land/styles_bottom_sheet.xml
- Setting the navigation bar color to an opaque color fixed the positioning
- Updating the Material library fixed an issue with the sizing of AdyenSwipeToRevealLayout
- Noticed that the background color of AdyenSwipeToRevealLayout was slightly off in dark mode, so adjusted it to better match
> Fix bottom sheets in landscape

- card/src/main/java/com/adyen/checkout/card/CardValidationMapper.kt
- card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
This makes it in line with iOS and web. Credit card numbers range from 13 to 19 digits, so this is safe to do
> MinCardNumberLength: Set min card number length to 12

- card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
This makes it in line with iOS and web. Credit card numbers range from 13 to 19 digits, so this is safe to do.
> MinCardNumberLength: Set min card number length to 12 (v4)

- config/git/commit-template
- config/git/init.sh
A commit message template will help us to write good, consistent messages. The init.sh file is to easily configure the template. You can run this file with `sh ./config/git/init.sh`.
The template is open for discussion, this is just my preference.
COAND-666
> Add git commit message template

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponentParams.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponentParams.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParams.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/repository/AddressRepository.kt
- card/src/main/java/com/adyen/checkout/card/repository/DefaultAddressRepository.kt
- card/src/main/java/com/adyen/checkout/card/test/TestAddressRepository.kt
- card/src/test/java/com/adyen/checkout/card/CardComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/StoredCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/base/ComponentParams.kt
- components-core/src/main/java/com/adyen/checkout/components/base/GenericComponentParams.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInComponentParams.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponentParams.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/model/GooglePayParams.kt
- issuer-list/build.gradle
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponentParams.kt
Our configuration classes are built directly by the developers and they are immutable. We need to be able to inject some values into them from drop-in or from the API responses.
In this PR we create a data class for the card component that shadows the card configuration and includes any extra parameters we need.
COAND-549
> Create card component parameters for internal use

- build.gradle
- dependencies.gradle
The plugin wasn't configured correctly so it wasn't even working. After enabling it, it flagged errors inside the auto generated view binding classes. Disabling it for now and will investigate later whether it's needed.
COAND-674
> Remove spotbugs

- card/src/main/java/com/adyen/checkout/card/CardInputData.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/util/DetectedCardTypesUtils.kt
By default, no brand will be selected in dual-branded flow. Hence it won't be passed to the PaymentComponentData.
COAND-676
> Remove selecting the first card in dual brand flow by default

- bacs/src/main/java/com/adyen/checkout/bacs/DefaultBacsDirectDebitDelegate.kt
Minor fix to make `DefaultBacsDirectDebitDelegate.paymentMethod` private
> Make DefaultBacsDirectDebitDelegate.paymentMethod private

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponentParamsMapper.kt
- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitConfiguration.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponentParamsMapper.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- components-core/src/main/java/com/adyen/checkout/components/base/AmountConfiguration.kt
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayConfiguration.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashConfiguration.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSComponentProvider.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSConfiguration.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponentParamsMapper.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
- ideal/src/main/java/com/adyen/checkout/ideal/IdealConfiguration.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponentParamsMapper.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListConfiguration.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/utils/TestIssuerListConfiguration.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayConfiguration.kt
- online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/OnlineBankingPLConfiguration.kt
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingConfiguration.kt
Moving all the default values from the configuration builders to the mappers means that the mappers become the source of truth for all config values, since we already compute other values in there. And we need to make sure that we keep the config builder docs up to date.
COAND-549
> Move configuration defaults to params

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/DefaultAdyen3DS2Delegate.kt
- components-core/src/main/java/com/adyen/checkout/components/bundle/SavedStateHandleContainer.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/BaseComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/ActionComponentViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/ComponentDialogViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInSavedStateHandleContainer.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModelFactory.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/GooglePayViewModel.kt
We use `var`s with getters and setters that access `savedStateHandle` in order to persist values in bundles.
This solution uses an implementation of `ReadWriteProperty` to delegate reading and writing to the `savedStateHandle` to a custom class.
COAND-682
> Extract Bundle and SaveStateHandle logic to BundleHandler

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/flow/FlowExtensions.kt
- ui-core/build.gradle
- ui-core/src/main/java/com/adyen/checkout/components/extensions/FlowExtensions.kt
- ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenComponentView.kt
- ui-core/src/test/java/com/adyen/checkout/components/extensions/FlowExtensionsTest.kt
Steps to reproduce:
1. Open card implementation example
2. Enter credit card details to open native 3ds2 flow
3. Rotate device
4. Complete 3ds2 flow
5. 💥
The issue was that Kotlin's `merge(flows)` function doesn't keep state and the flows in question that are merged are `StateFlow`s. When (re)subscribing to the merged flow, the last values from the `StateFlow`s were emitted again. With `mergeStateFlows` and `mergeViewFlows` added in this PR, it is possible to merge multiple flows into a `StateFlow`. `mergeViewFlows` is tailored to our special needs
COAND-660
> Fix screen rotation issues with action handling in payment components

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PaymentMethodsListViewModel.kt
When there's stored payment methods, payment methods header should be `Select other method` and when there's no stored payment methods header should be `Payment Methods`
COAND-686
> Fix payment methods headers

- ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenComponentView.kt
1. Open Ideal (or any payment method that's using an action)
2. Crash
When the ComponentViewType is null then there most likely also is no delegate, but we were trying to get the delegate anyway. A simple check before fixes it.
COAND-650
> Fix crash in generic action handling

- card/src/main/java/com/adyen/checkout/card/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/data/RestrictedCardType.kt
- card/src/test/java/com/adyen/checkout/card/CardComponentParamsMapperTest.kt
I removed US Debit cards from supported card type. 
COAND-628
> Remove US debit cards from supported type

- await/src/main/java/com/adyen/checkout/await/AwaitView.kt
- card/src/main/java/com/adyen/checkout/card/CardListAdapter.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- checkout-core/src/main/java/com/adyen/checkout/core/image/ImageLoader.kt
- components-core/src/main/java/com/adyen/checkout/components/api/OldImageLoader.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/giftcard/GiftCardPaymentConfirmationDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodAdapter.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListRecyclerAdapter.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListRecyclerView.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListSpinnerAdapter.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListSpinnerView.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankRecyclerAdapter.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankView.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QrCodeView.kt
- ui-core/src/main/java/com/adyen/checkout/components/image/ImageLoadingExtensions.kt
- voucher/src/main/java/com/adyen/checkout/voucher/VoucherView.kt
- Add extension functions for loading images and logos
- Add minimal implementation of image loading (not lifecycle aware and no caching)
- Rename the "old" `ImageLoader` to `OldImageLoader`
- Use new image loading extension in `CardView` to test it
COAND-673
> Create image loading extension

- example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewState.kt
1. Click "Change payment method"
2. Remove a stored payment method
3. Navigate back
4. The stored payment method still shows in the preselected screen
The payment method request was cached and since the request doesn't change when removing a stored pm, the cached version was returned. The caching is now moved to the card example to avoid unnecessary requests there.
COAND-687
> Fix stored payment methods not showing directly

- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewState.kt
1. Turn off internet on your device
2. Click an entry in MainActivity
3. See error toast
4. Rotate device
5. See error toast again
Errors were a view state, so they would display the toast again and again on for example a configuration change. Now errors are an event to ensure the toast is displayed only once.
> Prevent duplicate toast messages in MainActivity

- eps/src/main/java/com/adyen/checkout/eps/EPSConfiguration.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListConfiguration.kt
The docs for `IssuerListConfiguration.Builder.setHideIssuerLogos` state that the default value is false, while for EPS that default value is actually true.
COAND-549
> Fix docs for EPSConfiguration.Builder.setHideIssuerLogos

- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikDelegate.kt
- blik/src/main/java/com/adyen/checkout/blik/DefaultBlikDelegate.kt
- blik/src/main/java/com/adyen/checkout/blik/StoredBlikDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- components-core/src/main/java/com/adyen/checkout/components/PaymentComponent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PreselectedStoredPaymentViewModel.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/ui/viewmodel/PreselectedStoredPaymentViewModelTest.kt
- ui-core/src/main/java/com/adyen/checkout/components/ui/util/PayButtonFormatter.kt
- ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenComponentView.kt
`PreselectedStoredPaymentMethodFragment` logic should be moved to the view model, and it should not rely on `requiresInput()` anymore, but instead we can make use of the component state.
COAND-698
> Refactor PreselectedStoredPaymentMethodFragment

- drop-in/src/main/res/layout/fragment_bacs_direct_debit_component.xml
- drop-in/src/main/res/layout/fragment_generic_component.xml
- drop-in/src/main/res/layout/fragment_giftcard_component.xml
- example-app/src/main/res/values/colors.xml
- example-app/src/main/res/values/styles.xml
The navigation bar color was transparent in the example app. This causes problems with window insets on lower API versions, so the navigation bar color is now the same as the background color. Also, we had unnecessary padding at the bottom of some fragments, so that is now gone.
| Before | After |
|-------|-------|
| ![image](https://user-images.githubusercontent.com/17701279/210070737-06a5d059-f34e-41ef-9dc9-a5f3eec5697b.png) | ![image](https://user-images.githubusercontent.com/17701279/210070580-e863a886-ec8a-4d3b-b406-ff9bcf1df2d7.png) |
COAND-696
> Fix white space at the bottom of bottom sheets

- card/src/main/java/com/adyen/checkout/card/CardOutputData.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/test/TestDetectCardTypeRepository.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/StoredCardDelegateTest.kt
if a card brand is detected when a user enters a card number, the supported card list should be hidden.
The card list visibility logic was moved from view to delegate
| Before  | A brand is detected |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/9745693/209958161-42968acb-7eba-4f48-8c68-f182f1e63f49.png" width="200" height="400" /> | <img src="https://user-images.githubusercontent.com/9745693/209958214-642784fb-38c7-407d-bd17-27fa06a01c1d.png" width="200" height="400" />
|
COAND-627
> Remove the brand list if a card brand is detected

- checkout-core/src/main/java/com/adyen/checkout/core/api/OkHttpClient.kt
- checkout-core/src/main/java/com/adyen/checkout/core/image/ImageLoader.kt
According to the [OkHttp docs](https://github.com/square/okhttp/blob/cf2a40bdb997c359c0516941015181958f4381df/okhttp/src/main/kotlin/okhttp3/Call.kt#L42-L55) a Response(Body) should be closed asap to avoid memory leaks. I found these memory leaks while testing something, so that's how a found out.
> Close responses as soon as possible

- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
When the card number is 16 digits or more and valid we are allowed to return an 8 digit bin value.
COAND-540
> Return bin value of 8 digits under right conditions

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
When the card number is 16 digits or more and valid we are allowed to return an 8 digit bin value.
COAND-540
> Return bin value of 8 digits under right conditions (v4)

- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/ui/AddressFormInput.kt
- card/src/main/java/com/adyen/checkout/card/util/AddressFormUtils.kt
- card/src/test/java/com/adyen/checkout/card/AddressFormUtilsTest.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- Stop default country picker to first alphabetically available country Instead of choosing the first available option.
- States are not selected by default to first option you need to select them.
COAND-668
> Stop default country picker from picking first alphabetically available country

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentProvider.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentTest.kt
- action/src/main/java/com/adyen/checkout/action/GenericActionComponent.kt
- action/src/main/java/com/adyen/checkout/action/GenericActionComponentProvider.kt
- action/src/test/java/com/adyen/checkout/action/GenericActionComponentTest.kt
- await/src/main/java/com/adyen/checkout/await/AwaitComponent.kt
- await/src/main/java/com/adyen/checkout/await/AwaitComponentProvider.kt
- await/src/test/java/com/adyen/checkout/await/AwaitComponentTest.kt
- components-core/src/main/java/com/adyen/checkout/components/ActionComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/ActionComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/base/ActionComponentCallback.kt
- components-core/src/main/java/com/adyen/checkout/components/base/ActionComponentEventHandler.kt
- components-core/src/main/java/com/adyen/checkout/components/base/DefaultActionComponentEventHandler.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponent.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponentProvider.kt
- qr-code/src/test/java/com/adyen/checkout/qrcode/QRCodeComponentTest.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponentProvider.kt
- redirect/src/test/java/com/adyen/checkout/redirect/RedirectComponentTest.kt
- voucher/src/main/java/com/adyen/checkout/voucher/VoucherComponent.kt
- voucher/src/main/java/com/adyen/checkout/voucher/VoucherComponentProvider.kt
- voucher/src/test/java/com/adyen/checkout/voucher/VoucherComponentTest.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponent.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponentProvider.kt
- wechatpay/src/test/java/com/adyen/checkout/wechatpay/WeChatPayActionComponentTest.kt
Merchants don't have to call observe on action components anymore. Events are propagated through `ActionComponentCallback`
COAND-699
> Add action component callback to handle events from action components

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/data/CardType.kt
- card/src/main/java/com/adyen/checkout/card/repository/DefaultDetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/test/TestDetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/DualBrandedCardUtils.kt
- card/src/test/java/com/adyen/checkout/card/CardComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/CardTypeTest.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/DualBrandedCardUtilsTest.kt
- card/src/test/java/com/adyen/checkout/card/StoredCardDelegateTest.kt
- Fix supported card brands that are not part of predefined types inside `CardType.CardBrand` enum.
COAND-708
> Remove hard-coded brand support on card component/drop-in Android SDK

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- bacs/src/test/java/com/adyen/checkout/bacs/BacsDirectDebitComponentTest.kt
- ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenComponentView.kt
Prevent from components being attached multiple times to `AdyenComponentView`.
Bonus fix: handle back press correctly in BACS
COAND-711
> Fix card examples becoming empty when re-opening the app

- example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/RecurringRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleSessionsDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
Remove non suspending methods from `PaymentsRepository` after the refactor that removes support for synchronous API calls in `DropInService`.
COAND-716
> Remove non suspending methods from PaymentsRepository

- RELEASE_NOTES.md
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.java
- card/src/main/java/com/adyen/checkout/card/CardListAdapter.java
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/NewCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/data/CardBrand.kt
- card/src/main/java/com/adyen/checkout/card/data/CardType.java
- card/src/main/java/com/adyen/checkout/card/data/DetectedCardType.kt
- card/src/main/java/com/adyen/checkout/card/repository/BinLookupRepository.kt
- card/src/main/java/com/adyen/checkout/card/util/AddressValidationUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/DualBrandedCardUtils.kt
- card/src/test/java/com/adyen/checkout/card/CardBrandTest.kt
- card/src/test/java/com/adyen/checkout/card/DualBrandedCardUtilsTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- Fix supported card brands that are not part of predefined types inside `CardBrand.CardType` enum.
- Add `SupportedCardBrands` inside `CardConfiguration`
- Add new method `CardConfiguration.setSupportedCardTypes` with new argument `CardBrand` to allow merchants to add more `supported` types that are not predefined inside `CardType` enum.
COAND-708
> Remove hard-coded brand support on card component/drop-in Android SDK (V4)

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/DefaultBcmcDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParams.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentState.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/CardListAdapter.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/InstallmentConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/data/CardBrand.kt
- card/src/main/java/com/adyen/checkout/card/data/DetectedCardType.kt
- card/src/main/java/com/adyen/checkout/card/repository/DefaultDetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/repository/DetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/test/TestDetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/ui/model/CardListItem.kt
- card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/DualBrandedCardUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/InstallmentUtils.kt
- card/src/test/java/com/adyen/checkout/card/CardComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/CardTypeTest.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/DualBrandedCardUtilsTest.kt
- card/src/test/java/com/adyen/checkout/card/StoredCardDelegateTest.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- Rename `CardType -> CardBrand` and `CardBrand -> CardType` 
- Add a new method inside `CardConfiguration` `setSupportedCardType(CardBrand)` so now we have two methods one with `CardBrand` and another one with `CardType` to make it easy for migration from V4 to V5 
PS: `CardBrand` is the source of truth internally when adding `SupportCardTypes`.
COAND-708
> Remove hard-coded brand support on card component (V5)

- action/src/main/java/com/adyen/checkout/action/DefaultGenericActionDelegate.kt
The cancel button in the redirect view does not work with standalone components. `delegate.onError` gets called from `PaymentInProgressView` but the delegate there is the `GenericActionDelegate` which does not implement `onError`.
COAND-720
> Cancel button in redirect view not working in components

- README.md
- RELEASE_NOTES.md
- build.gradle
- example-app/build.gradle
* The `CardComponentState.binValue` now reports 8 digit bins in case of card numbers with 16 or more digits.
* The new `CardBrand` class can be used to define unknown card brands. This can be used along with `CardType`.
* When adding new card brands through `CardConfiguration`, you can now use the new `CardBrand`to add brands that are not already defined in `CardType`. 
For example:
```kotlin
CardConfiguration.Builder([SHOPPER_LOCALE], [ENVIRONMENT], [CLIENT_KEY])
.setSupportedCardTypes(CardBrand(txVariant = "[CARD_BRAND1]"), CardBrand(txVariant = "[CARD_BRAND2]"))
.build()
```
* Upgraded the 3D Secure 2 SDK version to v2.2.11.
* Upgraded `compileSdkVersion` and `targetSdkVersion` to 32.
* Upgraded Kotlin version to 1.6.21.
* Upgraded Kotlin coroutines version to 1.6.1.
* Upgraded …
> Release 4.10.0 🎉

- await/src/main/res/layout/await_view.xml
- bacs/src/main/res/layout/bacs_direct_debit_confirmation_view.xml
- bacs/src/main/res/layout/bacs_direct_debit_input_view.xml
- bcmc/src/main/res/layout/bcmc_view.xml
- blik/src/main/res/layout/blik_view.xml
- card/src/main/res/layout/card_view.xml
- econtext/src/main/res/layout/econtext_view.xml
- giftcard/src/main/res/layout/giftcard_view.xml
- mbway/src/main/res/layout/mbway_view.xml
- paybybank/src/main/res/layout/pay_by_bank_view.xml
- qr-code/src/main/res/layout/full_qrcode_view.xml
- qr-code/src/main/res/layout/simple_qrcode_view.xml
- sepa/src/main/res/layout/sepa_view.xml
- ui-core/src/main/res/layout/address_form_br.xml
- ui-core/src/main/res/layout/address_form_ca.xml
- ui-core/src/main/res/layout/address_form_default.xml
- ui-core/src/main/res/layout/address_form_gb.xml
- ui-core/src/main/res/layout/address_form_us.xml
- ui-core/src/main/res/layout/view_payment_in_progress.xml
There was a lint [bug](https://issuetracker.google.com/issues/155088391) called " Error: The required layout_width and layout_height attributes are missing [RequiredSize]" when we give layout_width and layout_height from style. To prevent this error "tools:ignore ="RequiredSize" was used. The bug was fixed  so we don't need to use it anymore
COAND-645
> Remove RequiredSize from XML

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/model/FingerprintToken.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- config/gradle/checksums.gradle
- dependencies.gradle
With version `2.2.12` the 3DS2 SDK now requires the `directoryServerRootCertificates` to be passed through the `AdyenConfigParameters.Builder` class.
We can read this value from the decoded `token` attribute inside the `action` object returned by the checkout API.
COAND-738
> Pass directory server root certificates to 3DS2 SDK

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/model/FingerprintToken.kt
- build.gradle
- config/gradle/checksums.gradle
With version `2.2.12` the 3DS2 SDK now requires the `directoryServerRootCertificates` to be passed through the `AdyenConfigParameters.Builder` class.
We can read this value from the decoded `token` attribute inside the `action` object returned by the checkout API.
COAND-738
> Pass directory server root certificates to 3DS2 SDK (v4)

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/Adyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParams.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapper.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentTest.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapperTest.kt
- action/src/main/java/com/adyen/checkout/action/internal/ActionHandlingComponent.kt
- action/src/main/java/com/adyen/checkout/action/internal/DefaultActionHandlingComponent.kt
- action/src/main/java/com/adyen/checkout/action/internal/ui/DefaultGenericActionDelegate.kt
- action/src/main/java/com/adyen/checkout/action/internal/ui/GenericActionDelegate.kt
- action/src/test/java/com/adyen/checkout/action/internal/ui/DefaultGenericActionDelegateTest.kt
- action/src/test/java/com/adyen/checkout/action/internal/ui/TestActionDelegate.kt
With version `2.2.12` the `UiCustomization` class in the 3DS2 SDK is now `Parcelable`.
Which means that we can move this class to the 3DS2 configuration and remove the `setUiCustomization` and `set3DS2UICustomization` methods from delegates and components.
COAND-739
> Move 3DS2 UI customization to configuration

- ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitComponent.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/provider/ACHDirectDebitComponentProvider.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/ACHDirectDebitDelegate.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegate.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/StoredACHDirectDebitDelegate.kt
- ach/src/test/java/com/adyen/checkout/ach/ACHDirectDebitComponentTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegateTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/StoredACHDirectDebitDelegateTest.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodsListViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentViewModel.kt
- drop-in/src/test/java/com/adyen/checkout/internal/ui/PreselectedStoredPaymentViewModelTest.kt
Stored card triggers a payment on instantiation if cvc is hidden. Stored ach triggers a payment on instantiation always. These are propogated through onStateChanged callback. PreselectedStoredPaymentViewModel receives the new state and stores and uses it to trigger a payments call on pay button click. In the flows where a payments call is triggered on instantiation no view type is emitted anymore. Since stored ach doesn't support any UI anymore related delegates have been removed from common ACHDirectDebitDelegate and have been put into DefaultACHDirectDebitDelegate.
COAND-733
> Improve consistency in preselected stored payment methods

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.kt
With this method in the configuration it is possible to override the return URL used by the 3DS2 SDK. If not set, the default value from the 3DS2 SDK will be used.
COAND-725
> Make threedsRequestorAppURL overridable (v4)

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParams.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapper.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapperTest.kt
With this method in the configuration it is possible to override the return URL used by the 3DS2 SDK. If not set, the default value from the 3DS2 SDK will be used.
COAND-725
> Make threedsRequestorAppURL overridable

- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
We get the configuration by payment method type and in some edge cases UPI collect and/or QR could be used. Adding these keys to the Drop-in configuration makes sure the given `UpiConfiguration` will be used for all the UPI payment method types.
> Add UPI collect and QR to Drop-in configuration

- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/QRCodeCountDownTimer.kt
If the timer was not properly initialized and `cancel()` was called, then it would crash. Making the timer nullable instead of `lateinit` fixes it.
> Fix QRCodeCountDownTimer initialization error

- wechatpay/src/main/AndroidManifest.xml
The WeChat SDK checks if their app is available on the phone. Since Android 11 this is restricted and there should be extra config to make it work again.
COAND-751
> Enable querying the WeChat app package (v4)

- wechatpay/src/main/AndroidManifest.xml
The WeChat SDK checks if their app is available on the phone. Since Android 11 this is restricted and there should be extra config to make it work again.
COAND-751
> Enable querying the WeChat app package

- example-app/src/main/java/com/adyen/checkout/example/data/api/model/paymentsRequest/RecurringProcessingModel.kt
- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
Add `recurringProcessingModel` to the `/payments` request in the example app, as it's a required field for API v70.
COAND-755
> Support checkout API v70 on example app (v4)

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentProvider.kt
Fix restrict annotation for `Adyen3DS2ComponentProvider`.
COAND-758
> Fix restrict annotation for 3DS2 Component Provider

- components-core/src/main/java/com/adyen/checkout/components/core/internal/util/ValidationUtils.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/util/ValidationUtilsTest.kt
The regex we used before had some performance issues in certain edge cases. This new regex addresses those performance issues.
COAND-759
> Improve email validation regex

- RELEASE_NOTES.md
- action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/ActionComponentExtensions.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/NotAvailablePaymentMethod.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
It is now safe to exclude external dependencies from drop-in. You can do so by for example:
```Groovy
implementation('com.adyen.checkout:drop-in:5.0.0-local') {
exclude group: 'com.adyen.checkout', module: '3ds2'
exclude group: 'com.adyen.checkout', module: 'wechatpay'
}
```
COAND-695
> Make it safe to exclude external dependencies from drop-in

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CashAppPayComponentDialogFragment.kt
- drop-in/src/main/res/layout/fragment_cash_app_pay_component.xml
- drop-in/src/main/res/values/styles.xml
Instead of using our default button we should use [the one provided by the Cash App SDK](https://developers.cash.app/docs/api/technical-documentation/sdks/pay-kit/android-getting-started#cashapppaybutton). In our drop-in. This doesn't apply to the component as we have no button there.
COAND-634
> Use Cash App Pay's button

- .github/workflows/update_verification_metadata.yml
This workflow should automatically update the verification metadata if the `dependencies.gradle` file is updated by Renovate. Not sure how to test this except for merging it and rebasing current Renovate PRs.
COAND-770
> Add workflow that updates verification metadata

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
This solves an issue in the frictionless flow where if the first
challenge fails and the second is retried with a different card, it
would fail as well. Because the second challenge would be performed
with data from the first challenge.
COAND-771
> Fix 3DS2 frictionless flow (v4)

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
This solves an issue in the frictionless flow where if the first challenge fails and the second is retried with a different card, it would fail as well. Because the second challenge would be performed with data from the first challenge.
COAND-771
> Always clean up ThreeDS2Service before starting 3DS transaction

- await/src/main/java/com/adyen/checkout/await/AwaitView.java
Passing a String to a switch will call .hashCode(), so if it's null an exception will be thrown. Adding a null check before the switch solves this issue.
COAND-772
> Fix AwaitView state restoration

- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/CashAppPayViewProvider.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/view/CashAppPayButtonView.kt
- cashapppay/src/main/res/layout-night/cash_app_pay_button_view.xml
- cashapppay/src/main/res/layout/cash_app_pay_button_view.xml
- ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ButtonViewProvider.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ComponentViewType.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/DefaultPayButton.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/PayButton.kt
- ui-core/src/main/res/layout/adyen_component_view.xml
- ui-core/src/main/res/layout/default_pay_button_view.xml
> Use Cash App Pay SDK button

- ach/src/main/res/template/values/strings.xml.tt
- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodAdapter.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/res/template/values/strings.xml.tt
- drop-in/src/main/res/values/strings.xml
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/SessionsGiftCardViewModel.kt
As a continuation of #1221, we can now exclude any component from drop-in, even payment components:
```groovy
implementation('com.adyen.checkout:drop-in:YOUR_VERSION') {
exclude group: 'com.adyen.checkout', module: 'cashapppay'
exclude group: 'com.adyen.checkout', module: 'googlepay'
}
```
COAND-776
> Make it safe to exclude any component module from drop-in

- card/src/main/java/com/adyen/checkout/card/internal/data/model/Brand.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
- card/src/test/java/com/adyen/checkout/card/internal/util/CardValidationUtilsTest.kt
CVC field is still being validated as required when bin lookup returns that the CVC should be "hidden". 
We should treat hidden as optional and allow this field to be empty when bin lookup returns "hidden".
COAND-783
> Allow CVC to be empty when bin lookup returns "hidden"

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/api/model/Brand.kt
- card/src/main/java/com/adyen/checkout/card/util/CardValidationUtils.kt
CVC field is still being validated as required when bin lookup returns that the CVC should be "hidden". 
We should treat hidden as optional and allow this field to be empty when bin lookup returns "hidden".
COAND-783
> Allow CVC to be empty when bin lookup returns "hidden" (v4)

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Serializer.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/model/ChallengeResult.kt
- build.gradle
- config/gradle/checksums.gradle
Update 3ds2 sdk to 2.2.15 and start using the new onCompletion callback to get challenge results. Before this change details were emitted only for completion event, however starting from now they will be emitted for all results received from 3ds2 sdk for merchants to be able to get more information about the errors they encounter during the flow.
COAND-748
> Propagate details on error, cancel and timeout from 3ds2 sdk (v4)

- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
Brand parameter was being set incorrectly in a dual branded card payment where no brand is selected.
COAND-676
> Fix dual branded flow check

- instant/src/main/java/com/adyen/checkout/instant/InstantPaymentComponent.kt
Using a payment method like Duitnow would crash. This was because the delegate received by the QR code view was not the correct delegate type yet. 
COAND-786
> Fix QR code actions for InstantPaymentComponent

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
Fixed an exception that appears when rotating the phone while being in the redirection screen. 
Reproduction path with example app (video is attached): 
- Open DropIn by clicking start
- Select iDEAL and select a test issuer
- Wait for browser to open the redirect url showing the issuer simulation 
- Rotate phone 
- Press continue
Video for reproduction: https://github.com/Adyen/adyen-android/assets/13377878/b3243776-b956-421e-9856-995d45d427fd
Video with fix applied: https://github.com/Adyen/adyen-android/assets/13377878/23c656cb-5789-4f6a-a438-f1b210f45501
COAND-XXX
> Prevent crash when rotating the phone while being in the redirection screen

- card/src/main/java/com/adyen/checkout/card/AddressDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/ui/AddressSpecification.kt
- Return empty list when fetching country or states fails. Before it would crash. Now when fetching countries fails we notify the merchant and display a dialog to the shopper. This should prevent the shopper from proceeding to the empty states list.
- Keep AddressSpecification from being obfuscated. We are mapping country codes the this enum's entries. This will not work if the enum is obfuscated.
COAND-777
> Fix address fetch crash (v4)

- ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
The drop-in bottom sheet was jumping position when a new view was loaded into it and navigating to another activity at the same time. Having a slight delay prevents the jumping from happening.
COAND-792
> Fix jumping bottom sheet

- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegate.kt
By propagating the view errors correctly to the component the cancel flow is now correctly working.
COAND-798
> Fix cancel button not working during WeChat flow

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
This fixes an issue where a loading spinner would show infinitely when an error is returned in the remove stored payment method callback.
COAND-801
> Fix infinite loading spinner

- example-app/src/main/AndroidManifest.xml
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
Fix deep links to fragments in example app not working
COAND-796
> Fix deep links to fragments in example app not working

- checkout-core/src/main/java/com/adyen/checkout/core/exception/HttpException.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/OkHttpClient.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/ErrorResponseBody.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/DefaultAnalyticsRepository.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ImageLoadingExtensions.kt
Improve error handling and logging for analytics and image loader.
> Improve error logging for analytics and image loader

- renovate.json
Configure renovate to reduce noise and improve stability by only updating releases more than 30 days old and grouping all updates at the start of the month.
> Configure renovate to reduce noise and improve stability

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/Adyen3DS2ViewProvider.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/ACHDirectDebitViewProvider.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitViewProvider.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/BacsDirectDebitViewProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/BcmcViewProvider.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/BlikViewProvider.kt
- boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/BoletoViewProvider.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/CardViewProvider.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/CashAppPayViewProvider.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/EContextViewProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardViewProvider.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/ui/IssuerListViewProvider.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MbWayViewProvider.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/OnlineBankingViewProvider.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/PayByBankViewProvider.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/QrCodeViewProvider.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/RedirectViewProvider.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/SepaViewProvider.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ButtonViewProvider.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ViewProvider.kt
- upi/src/main/java/com/adyen/checkout/upi/internal/ui/UPIViewProvider.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/VoucherViewProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/WeChatViewProvider.kt
The layout inspector enables a developer option that would trigger some sort of XML parsing to happen. This XML was not available (because we create the views programatically), so it resulted in a crash.
COAND-809
> Fix crash triggered by layout inspector

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BaseComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInBottomSheetDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardPaymentConfirmationDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GooglePayComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
When a user dismisses the gift card fragment drop-in would not be terminated. This blocks the user with an invisible activity and makes the merchant app seem unresponsive. By simply overriding onCancel this was fixed.
COAND-817
> Fix frozen screen when dismissing gift card fragment

- action-core/build.gradle
It used the same namespace as action, so it would generate a duplicate BuildConfig class. Ultimately failing the build when implementing the action module.
COAND-820
> Give action-core another namespace

- renovate.json
Stop renovate from automatically rebasing PRs to reduce notification noise.
You can manually rebase or click on the rebase checkbox in the PR description.
> Do not rebase renovate PRs automatically

- example-app/src/main/java/com/adyen/checkout/example/data/storage/KeyValueStorage.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/res/values/arrays.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/xml/preferences.xml
Rename telemetry (only used in the example app) to analytics to preserve consistency with the SDK and because analytics is a broader term that fits our use case more than telemetry.
> Rename telemetry to analytics

- build.gradle
- config/gradle/checksums.gradle
This should make WeChat work on Android 11+ again.
> Update WeChat SDK to 6.8.0

- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
The issue is when a new card is inputted we keep selected card index which results in incorrectly selecting a brand if the new card being inputted is dual branded. 
COAND-795
> Fix selected card index not being reset when a new card is detected

- renovate.json
This will make sure Compose and Kotlin will get updated in the same PR, so we will no longer run into compatibility conflicts.
> Group Compose and Kotlin for Renovate

- .github/workflows/check_release_notes.yml
Add a workflow to make sure we update the release notes file when a PR has a 'Feature', 'Fix' or 'Breaking change' label.
COAND-762
> Add workflow to validate release notes

- RELEASE_NOTES.md
- bacs/src/main/res/values/styles.xml
- paybybank/src/main/res/values/styles.xml
- ui-core/src/main/res/values/styles.xml
- upi/src/main/res/values/styles.xml
- voucher/src/main/res/values/styles.xml
Some styles are not overridable and will cause a build error, because their parent style is not declared in `styles.xml`.
COAND-841
> Add missing parent styles in XML

- checkout-core/src/main/java/com/adyen/checkout/core/exception/HttpException.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClientExt.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/OkHttpClient.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/ErrorResponseBody.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/DefaultAnalyticsRepository.kt
- Added detailed error logging to internal API calls:
- Logging is added on the HTTP client level, to make sure it covers every call.
- If the error body is a json string with the expected format, we log it as it is to make debugging easier.
- Otherwise, the error code and body or message are logged.
- Added `pspReference` attribute to the error response body.
- Changed analytics API error logging level back to `e` now that the endpoints are live.
> Improve logging of API errors

- RELEASE_NOTES.md
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
For polling action components (Await and QR code) the polling intervals were set to very big values which can leave shoppers stuck on the loading screen for a long time after the payment was processed.
This PR fixes these values and aligns them again with v4.
> Fix polling interval values in polling action components

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/api/SubmitFingerprintService.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- card/src/main/java/com/adyen/checkout/card/internal/data/api/BinLookupService.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegate.kt
- cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsService.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/OrderStatusService.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/PublicKeyService.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/CheckoutSessionInitializer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/api/SessionService.kt
- test-core/src/main/java/com/adyen/checkout/test/TestDispatcherExtension.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/data/api/AddressService.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/data/api/DefaultAddressRepository.kt
Inject coroutines dispatchers instead of using them directly. This makes the code better testable.
Bonus:
- Reduced complexity of `DefaultAdyen3DS2Delegate` methods
- Removed dispatcher injection from `TestDispatcherExtension`
- It was only used in one test and there were warnings about it
> Inject coroutine dispatchers

- ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitConfiguration.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/CashAppPayConfiguration.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/BaseConfigurationBuilder.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
Some configuration values are ignored in the sessions flow and can only be set in the `/sessions` request. In this PR we clarify that in the code docs of the configurations that are affected.
List of affected configurations:
- `setShowStorePaymentField`
- `setAmount`
- `setReturnUrl`
- `setInstallmentConfigurations`
COAND-850
> Add documentation for configurations that cannot be set with sessions

- RELEASE_NOTES.md
- action-core/src/main/java/com/adyen/checkout/action/core/internal/ActionHandlingPaymentMethodConfigurationBuilder.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/util/LocaleUtil.kt
- components-compose/src/main/java/com/adyen/checkout/components/compose/ComposeExtensions.kt
- components-core/src/main/java/com/adyen/checkout/components/core/CheckoutConfiguration.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/BaseConfigurationBuilder.kt
- drop-in-compose/src/main/java/com/adyen/checkout/dropin/compose/ComposeExtensions.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/CheckoutSession.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/CheckoutSessionProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/CheckoutSessionInitializer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/provider/SessionPaymentComponentProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/provider/SessionStoredPaymentComponentProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/ui/model/SessionParamsFactory.kt
- With the sessions flow, when starting drop-in or creating a component, the configuration parameter can be made optional.
- When `CheckoutSessionProvider.createSession` to create a `CheckoutSession`, we can pass the `environment` and `clientKey` instead of the whole configuration.
COAND-853
> Make configurations optional with the sessions flow

- RELEASE_NOTES.md
- checkout-core/build.gradle
- dependencies.gradle
The parcelize plugin needs this dependency and if the merchant doesn't include it in their project it crashes the build when using R8.
COAND-858
> Ship kotlin-parcelize-runtime with the SDK

- RELEASE_NOTES.md
- action-core/src/main/java/com/adyen/checkout/action/core/GenericActionComponent.kt
- action-core/src/main/java/com/adyen/checkout/action/core/internal/DefaultActionHandlingComponent.kt
- action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/GenericActionComponentProvider.kt
- action-core/src/test/java/com/adyen/checkout/action/core/GenericActionComponentTest.kt
- action-core/src/test/java/com/adyen/checkout/action/core/internal/DefaultActionHandlingComponentTest.kt
Fixes an issue with getting the active delegate while handling an action.
Steps to reproduce:
- Integrate Blik in an compose app
- Make a Blik payment
- It will crash while trying to handle the await action
COAND-864
> Fix action handling concurrency issue

- components-core/src/main/java/com/adyen/checkout/components/core/internal/Component.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/model/DropInResultContractParams.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/model/SessionDropInResultContractParams.kt
Remove RestrictTo annotations from classes that can be publicly accessible:
- `DropInResultContractParams` and `SessionDropInResultContractParams` are needed if you need to explicitly specify the type of `dropInLauncher`.
- `Component` is needed if you want to use components generically.
COAND-867
> Fix wrong `RestrictTo` annotations

- drop-in/src/main/java/com/adyen/checkout/dropin/BaseDropInServiceContract.kt
Throw `MethodNotImplementedException` if `onAddressLookupQueryChanged(query: String)` is not implemented in drop-in.
COAND-730
> Throw exception if onAddressLookupQueryChanged is not implemented

- example-app/build.gradle
Duplicate `example.local.gradle` file into `local.gradle` to allow building from Renovate just like we do with CI builds.
Reference for the environment variable in use: https://docs.renovatebot.com/configuration-options/#env.
COAND-831
> Fix Renovate builds failing

- example-app/build.gradle
- renovate.json
Duplicate `example.local.gradle` file into `local.gradle` to allow building from Renovate just like we do with CI builds, by setting the CI environment variable to true.
Reference for the environment variable in use: https://docs.renovatebot.com/configuration-options/#env.
COAND-831
> Fix Renovate builds failing (attempt #2)

- example-app/build.gradle
- renovate.json
Reverse the logic of checking for CI builds by checking if the build is triggered by the IDE.
COAND-831
> Fix Renovate builds failing (attempt #3)

- card/src/main/res/values/styles.xml
This fixes an issue where the styling was incorrect and caused weird looks and behavior. In #1534 we accidentally caused this, but we didn't release it yet.
| Before | After |
|--------|--------|
| ![Screenshot_20240405_144611](https://github.com/Adyen/adyen-android/assets/17701279/3677ad2a-d671-4731-9d5b-144f9e2c995d) | ![Screenshot_20240405_144447](https://github.com/Adyen/adyen-android/assets/17701279/9c38e586-5156-4835-b631-f9aa563ad3ef) |
COAND-880
> Fix duplicate parent styling for AdyenCheckout.DropdownTextInputLayout

- RELEASE_NOTES.md
- card/src/main/res/values/styles.xml
- ui-core/src/main/res/values/styles.xml
Replace `?android:attr/textColor` with `?attr/colorOnSurface`. `?android:attr/textColor` is not defined by default by any AppCompat or Material base theme. If not defined manually it will cause a crash. `?attr/colorOnSurface` is used by Material primarily for text coloring.
COAND-884
> Fix InflateException

- RELEASE_NOTES.md
- card/src/main/res/values-ar/strings.xml
- card/src/main/res/values-cs-rCZ/strings.xml
- card/src/main/res/values-da-rDK/strings.xml
- card/src/main/res/values-de-rDE/strings.xml
- card/src/main/res/values-el-rGR/strings.xml
- card/src/main/res/values-es-rES/strings.xml
- card/src/main/res/values-fi-rFI/strings.xml
- card/src/main/res/values-fr-rFR/strings.xml
- card/src/main/res/values-hr-rHR/strings.xml
- card/src/main/res/values-hu-rHU/strings.xml
- card/src/main/res/values-it-rIT/strings.xml
- card/src/main/res/values-ja-rJP/strings.xml
- card/src/main/res/values-ko-rKR/strings.xml
- card/src/main/res/values-nb-rNO/strings.xml
- card/src/main/res/values-nl-rNL/strings.xml
- card/src/main/res/values-pl-rPL/strings.xml
- card/src/main/res/values-pt-rBR/strings.xml
- card/src/main/res/values-pt-rPT/strings.xml
- card/src/main/res/values-ro-rRO/strings.xml
- card/src/main/res/values-ru-rRU/strings.xml
- card/src/main/res/values-sk-rSK/strings.xml
- card/src/main/res/values-sl-rSI/strings.xml
- card/src/main/res/values-sv-rSE/strings.xml
- card/src/main/res/values-zh-rCN/strings.xml
- card/src/main/res/values-zh-rTW/strings.xml
- card/src/main/res/values/strings.xml
Fix `checkout_card_installments_option_regular_with_price` which was causing build warnings.
COAND-879
> Fix existing string resources with multiple substitutions

- RELEASE_NOTES.md
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/DefaultStatusRepositoryTest.kt
- test-core/src/main/java/com/adyen/checkout/test/extensions/TestFlow.kt
The issue was caused by the status polling emitting the final value multiple times. By merging and cancelling the flows in `StatusRepository` and adding debounce the issue is solved.
COAND-883
> Fix onAdditionalDetails being called multiple times

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- RELEASE_NOTES.md
- action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/GenericActionComponentProvider.kt
- await/src/main/java/com/adyen/checkout/await/internal/provider/AwaitComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ActionComponentEventHandler.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/DefaultActionComponentEventHandler.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/provider/QRCodeComponentProvider.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/provider/RedirectComponentProvider.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/provider/VoucherComponentProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/provider/WeChatPayActionComponentProvider.kt
Fixed an issue where the action components leak their callbacks after screen rotation because `DefaultActionComponentEventHandler` holds on to them.
> Fix memroy leak in action components

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
The constructors of the card and bcmc components were kept public by mistake, they should not be used directly to instantiate components. Their providers should be used instead.
> Restrict constructors of card and bcmc components

- action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/DefaultGenericActionDelegate.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
Fixed a memory leak caused by  the redirect listener holding references to an activity or fragment.
> Fix redirect callback leak

- RELEASE_NOTES.md
- checkout-core/src/main/java/com/adyen/checkout/core/AdyenLogger.kt
- checkout-core/src/test/java/com/adyen/checkout/core/internal/util/AdyenLoggerTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
This fixes a bug where drop-in would override the log level that a merchant has already set before.
COAND-889
> Fix initial log level

- renovate.json
Changed the release age for renovate to 14 days
COAND-897
> Reduce release age to 14 days

- RELEASE_NOTES.md
- components-core/src/main/java/com/adyen/checkout/components/core/CheckoutConfiguration.kt
This solves a crash where configurations would get the same name when they are obfuscated.
COAND-902
> Fix crash caused by obfuscation of action configurations

- ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapper.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapperTest.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapper.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapperTest.kt
- boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapper.kt
- boleto/src/test/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapperTest.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapper.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapperTest.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapper.kt
- cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapperTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapper.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/DropInOverrideParams.kt
- components-core/src/test/java/com/adyen/checkout/components/core/ButtonTestConfiguration.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapperTest.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapper.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapperTest.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapper.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapperTest.kt
After this change, it is not allowed to hide to pay button in components when they are created by drop-in.
COAND-838
> Display pay button in components if created by drop in

- RELEASE_NOTES.md
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
With Checkout API v66 and earlier, drop-in throws an error while trying to handle two separate 3DS2 actions returned by the API (fingerprint and challenge).
COAND-906
> Fix drop-in unable to handle 3DS2 on API v66 and below

- docs/UI_CUSTOMIZATION.md
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/DefaultEContextDelegate.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/EContextDelegate.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/view/EContextView.kt
- econtext/src/main/res/layout/econtext_view.xml
- econtext/src/test/java/com/adyen/checkout/econtext/internal/ui/DefaultEContextDelegateTest.kt
- example-app/src/main/res/color/text_color_secondary.xml
- example-app/src/main/res/values/styles.xml
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegate.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayDelegate.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
- mbway/src/main/res/layout/mbway_view.xml
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/CountryViewHolder.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/CountryUtils.kt
- ui-core/src/main/res/color/text_color_secondary.xml
- ui-core/src/main/res/layout/country_view.xml
- ui-core/src/main/res/template/values/strings.xml.tt
- ui-core/src/main/res/values/strings.xml
- ui-core/src/main/res/values/styles.xml
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/util/CountryUtilsTest.kt
- Align country code picker with other platforms
- Sort list by localized country name
- Some design tweaks
- Addition of NEW secondary text color
- Preselected correct country code for MBWay
COAND-912
> Change phone number country code picker

- RELEASE_NOTES.md
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupConfiguration.kt
Fix the bug which cause storedPaymentMethod removal to not work for older integrations
COAND-913
> Fix storedPaymentMethod removal for older integrations

- RELEASE_NOTES.md
Add dependency updates to release notes
> Add dependency updates to release notes

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/TwintActionComponent.kt
- twint-action/src/main/res/layout/view_twint_action.xml
- twint/api/twint.api
- twint/build.gradle
- twint/src/main/java/com/adyen/checkout/twint/TwintComponent.kt
- twint/src/main/java/com/adyen/checkout/twint/TwintComponentState.kt
- twint/src/main/java/com/adyen/checkout/twint/TwintConfiguration.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/provider/TwintComponentProvider.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegate.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintDelegate.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/TwintViewProvider.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParams.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapper.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintInputData.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintOutputData.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/view/TwintView.kt
- twint/src/test/java/com/adyen/checkout/twint/TwintComponentTest.kt
- twint/src/test/java/com/adyen/checkout/twint/TwintConfigurationTest.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegateTest.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapperTest.kt
Create a Twint payment component.
Next step is to populate the view, so shoppers can use a switch to store their Twint.
COAND-927
> Create Twint payment component

- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- drop-in/build.gradle
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/DropInViewModelTest.kt
- instant/api/instant.api
- instant/src/main/java/com/adyen/checkout/instant/InstantPaymentComponent.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
- instant/src/test/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProviderTest.kt
Separated `SUPPORTED_ACTION_ONLY_PAYMENT_METHODS` into two, one for drop-in skip to logic and one for `InstantPayComponent` supported payment methods.
COAND-962
> Fix skip to payment method list

- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/DropInViewModelTest.kt
- Removed UPI payment methods from unsupported list
- Move the Drop-in payment method filtering to `DropInViewModel`
- Filtering is done in `getPaymentMethods()` method, to apply it for features like `skipListWhenSinglePaymentMethod`
I changed the initial approach of creating a `PaymentMethodManager`, since it was redundant with the current Drop-in structure. It could be a better fit after we refactor Drop-in.
COAND-965
> UPI - Improve payment methods list

- drop-in/src/main/res/layout/fragment_generic_action_component.xml
- drop-in/src/main/res/layout/fragment_gift_card_payment_confirmation.xml
- drop-in/src/main/res/layout/fragment_stored_payment_method.xml
- drop-in/src/main/res/values/styles.xml
- lint/src/main/java/com/adyen/checkout/lint/LintIssueRegistry.kt
- lint/src/main/java/com/adyen/checkout/lint/TextInLayoutXml.kt
- lint/src/test/java/com/adyen/checkout/lint/TextInLayoutXmlTest.kt
- ui-core/src/main/res/layout/address_lookup_view.xml
- ui-core/src/main/res/values/styles.xml
Add lint rule to check if `android:text` is used directly and fix violations of this new rule.
COAND-956
> Add lint rule to check if `android:text` is used directly

- lint/src/main/java/com/adyen/checkout/lint/ContextGetString.kt
- lint/src/main/java/com/adyen/checkout/lint/LintIssueRegistry.kt
- lint/src/test/java/com/adyen/checkout/lint/ContextGetStringTest.kt
Add lint rule that checks if `context.getString()` is used and replace it with `localizedContext.getString()`.
COAND-956
> Add lint rule that checks if `context.getString()` is used

- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/provider/BcmcComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/internal/provider/CardComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/CardConfigDataGenerator.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/CardConfigDataGeneratorTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/JsonUtils.kt
- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsEvent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/AnalyticsTrackRequestProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackInfo.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/AnalyticsTrackRequestProviderTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackInfoTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackRequestTest.kt
Added `configData` to the rendered analytics event. This field contains the merchant configuration for the specific component. Currently, the field is only used by the card component.
COAND-967
> Add configData field to rendered  analytics event

- .github/workflows/stale_issues.yml
The stale action allows us to automatically comment on and close inactive issues. The configuration I suggested is:
- We need to manually label issues with `Needs more info` to prevent this from running on all issues.
- After 14 days without any activity, the stale bot will comment with the first message (`stale-issue-message`).
- After another 14 days the stale bot will comment with the second message (`close-issue-message`) and then close the issue.
> Add action to manage stale issues

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProvider.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProviderTest.kt
Fix malformed locale in analytics setup request. The backend only accepts language tags (`xx-YY-zzzzzz`) and not full unformatted locales (xx_YY_#zzzzzz).
COAND-993
> Analytics - Fix malformed locale in analytics setup request

- redirect/src/main/java/com/adyen/checkout/redirect/internal/data/model/NativeRedirectRequest.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
Before we used to fallback to the normal redirect flow if we would lose nativeRedirectData. Instead, we can just send null in the native redirect request and the backend will be able to recover the state to complete the flow.
COAND-996
> Don't fallback to normal redirect flow

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManagerTest.kt
- If fetching `checkoutAttemptId` fails, we send `fetch-checkoutAttemptId-failed` for its value.
- It should only be sent as part of `/payments` call, so we should stop sending analytics events if `checkoutAttemptId` has failed to fetch.
COAND-982
> Analytics - Send failed checkoutAttemptId if fetching fails

- RELEASE_NOTES.md
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/JsonUtils.kt
- checkout-core/src/test/java/com/adyen/checkout/core/internal/data/model/JsonUtilsTest.kt
Replace `JSONObject.has` with `!JSONObject.isNull` when reading JSON values to ensure correct handling of null values.
COAND-994
> Correctly check nullability when reading from JSON objects

- checkout-core/api/checkout-core.api
- checkout-core/src/main/java/com/adyen/checkout/core/ui/validation/CardNumberValidator.kt
Restrict public field `CardNumberValidator.MAXIMUM_CARD_NUMBER_LENGTH` to library group.
COAND-985
> Restrict CardNumberValidator.MAXIMUM_CARD_NUMBER_LENGTH to library group

- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/ExpiryDateInput.kt
Move expiry date autofill hint to CardView. Now it should only autofill for credit cards and not for French meal vouchers.
> Fix expiry date autofill hint

- gradle/libs.versions.toml
[Renovate cannot update this dependency](https://github.com/renovatebot/renovate/issues/18354) unless it is explicitly declared in `[libraries]` as well as `[versions]` in the `libs.versions.toml` file. The newly added entry will be unused.
> Explicitly add compose compiler dependency in libs.versions.toml

- example-app/src/main/res/values-night/styles.xml
- example-app/src/main/res/values/styles.xml
- googlepay/api/googlepay.api
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayButtonStyling.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayButtonView.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParams.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapper.kt
- googlepay/src/main/res/layout/view_google_pay_button.xml
- googlepay/src/main/res/values-night/styles.xml
- googlepay/src/main/res/values/attrs.xml
- googlepay/src/main/res/values/styles.xml
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtilsTest.kt
Make it possible to style the Google Pay button both through code and XML. Where code has priority.
COAND-942
> Google Pay button styling

- RELEASE_NOTES.md
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GooglePayComponentDialogFragment.kt
- drop-in/src/main/res/layout/fragment_google_pay_component.xml
Display toolbar in drop-in Google Pay fragment (all other fragments already have a toolbar). In a follow up PR we will show a loading indicator on all these intermediary screens as well.
COAND-1012
> Display toolbar on all intermediary screens for drop-in

- config/gradle/buildConfig.gradle
Fixed an issue with reading the `BuildConfig.CHECKOUT_VERSION` from the toml file.
COAND-977
> Correctly read checkout version from version catalog

- .github/workflows/publish_release.yml
- .github/workflows/publish_release_old.yml
- Allow running the job on a specified branch instead of main
- Use new Github secrets for publishing the app on maven central
- Make the Github release draft
- Add a step to verify if the branch name starts with e.g. `release/`
- Separate each step into a different job
COAND-1013
> Release - New GitHub workflow for releasing

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/data/api/SubmitFingerprintService.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/internal/data/api/BinLookupService.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegate.kt
- checkout-core/src/main/java/com/adyen/checkout/core/DispatcherProvider.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/ui/ImageLoader.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsService.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/OrderStatusService.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/PublicKeyService.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/StatusRepository.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- example-app/src/androidTest/java/com/adyen/checkout/test/rule/IdlingDispatcherRule.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/data/api/NativeRedirectService.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/CheckoutSessionInitializer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/api/SessionService.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/data/api/AddressService.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/data/api/DefaultAddressRepository.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ImageSaver.kt
`DispatcherProvider` allows us to set the `CoroutineDispatcher` we're going to use hence it is now possible to use a custom dispatcher in our ui tests.
> Introduce DispatcherProvider

- example-app/src/main/java/com/adyen/checkout/example/repositories/RepositoryUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleSessionsDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/compose/SessionsGooglePayViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewModel.kt
This will make sure espresso tests will be aware of all async work that is happening and should fix the UI tests.
> Replace usage of Dispatchers with DispatcherProvider in example app

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsEvent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/analytics/DropInEvents.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/DropInViewModelTest.kt
Track event when user closes Drop-in
COAND-816
> Analytics - Track event when Drop-in closes

- example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupCompletionResult.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- Fix issue where selecting the same address from the lookup list options multiple times in a row only works the first time.
- Remove `onLookupCompletion` callback in `CardActivity` to allow testing this scenario.
> Address lookup fixes and improvements in example app

- checkout-core/src/main/java/com/adyen/checkout/core/DispatcherProvider.kt
- lint/src/main/java/com/adyen/checkout/lint/LintIssueRegistry.kt
- lint/src/main/java/com/adyen/checkout/lint/NotDispatcherProvider.kt
- lint/src/test/java/com/adyen/checkout/lint/NotDispatcherProviderTest.kt
- test-core/src/testFixtures/java/com/adyen/checkout/test/TestDispatcherExtension.kt
Add lint rule that prevents `Dispatchers` usage and forces to use `DispatcherProvider` instead. This will help us to keep our code testable.
COAND-1020
> Add lint rule that prevents Dispatchers usage

- example-app/src/main/java/com/adyen/checkout/example/extensions/DispatcherExtensions.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/RepositoryUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleSessionsDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/compose/SessionsGooglePayViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewModel.kt
This will make it easier to replace in the future and avoids the need of suppressions.
> Centralize IO dispatcher usage in example app

- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapperTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapperTest.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapperTest.kt
- boleto/src/test/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapperTest.kt
- cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapperTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/CheckoutConfiguration.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsManagerFactory.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsSetupRequest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/AnalyticsParams.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManagerTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProviderTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsSetupRequestTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapperTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/GenericComponentParamsMapperTest.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/model/DropInParamsMapperTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapperTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtilsTest.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapperTest.kt
- meal-voucher-fr/src/test/java/com/adyen/checkout/mealvoucherfr/internal/ui/model/MealVoucherFRComponentParamsMapperTest.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapperTest.kt
Add level field to the initial call to determine if the analytics is disabled or not
COAND-1029
> Analytics - Level field

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegateTest.kt
Track redirect error events
COAND-1006
> Analytics - Track redirect error events

- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayView.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayViewProvider.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayOutputData.kt
- googlepay/src/main/res/layout/view_google_pay.xml
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/ProcessingPaymentView.kt
Previously, the GooglePayView was replaced with ProcessingPaymentView. This causes the Activity Result API to fail and not deliver the result in case the view got recreated on configuration change. By keeping the GooglePayView in view it will be able to successfully restore it's state and deliver the activity result. Making the loading state part of the GooglePayView is essential to fix this problem.
COAND-941
> Move loading state to GooglePayView

- RELEASE_NOTES.md
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
- drop-in/src/main/res/layout/fragment_giftcard_component.xml
1. Override this in the drop in service:
```Kotlin
override fun onBalanceCheck(paymentComponentState: PaymentComponentState<*>) {
val result = handleBalanceResponse(null)
sendBalanceResult(result)
}
```
2. Open drop-in
3. Do a gift card payment
4. Aaaand you're now stuck on a loading state with an error dialog behind it...
The issue is fixed by using `showNow()` when showing the loading state fragment. An extra improvement is to always dismiss the loading state when we get back a result from the merchant. Before we only dismissed the loading state in some specific places.
COAND-984
> Fix loading state overlapping error dialog in drop-in

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/ErrorEvent.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegateTest.kt
Do not track an error event if the user cancels the redirect flow, since it is not considered an error anymore.
COAND-1006
> Analytics - Remove tracking redirect cancelled event

- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegate.kt
- cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegateTest.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/internal/ui/DefaultTwintActionDelegate.kt
- twint-action/src/test/java/com/adyen/checkout/twint/action/internal/ui/DefaultTwintActionDelegateTest.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegate.kt
- wechatpay/src/test/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegateTest.kt
Track error events for Third party SDKs and services
There is a [separate PR](https://github.com/Adyen/adyen-android/pull/1900) to add events for the new flow of the Google Pay.
COAND-1009
> Analytics - Track third party error events

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodAdapter.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/model/StoredPaymentMethodModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/util/StoredUtils.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/PreselectedStoredPaymentViewModelTest.kt
Display confirmation pop-up in `PreselectedStoredPaymentMethodFragment` and include bank account name as message in the pop-up for Pay by Bank US.
COAND-974
> Pay by Bank US - Confirmation Pop-up

- .github/workflows/check_labels.yml
- scripts/check_release_notes_labels.sh
- Added a new script to check for release notes in the PR body
- Adjusted the old `check_labels` script
- Created two list for required and optional labels, which define if release notes should be present or not
**Release notes exist**
| Case                       | Status  (should pass or not pass)                       |
|-----------------------------|------------------------------------|
| [No label added](https://github.com/Adyen/adyen-testcards-android/actions/runs/12070355320/job/33659672367)       |  ❌ (label required)  |
| [Has required label (Fix)](https://github.com/Adyen/adyen-testcards-android/actions/runs/12070331556/job/33659594009)   | ✅  |
| [Has optional label (Dependencies)](https://github.com/Adyen/adyen-testcards-android/actions/runs/12070366385/job/33659712142)  | ✅ | …
> Release - Update the script to check for release notes based on PR label

- .github/workflows/publish_release.yml
- Added generating release notes and creating release notes pr steps to the release workflow
- Used `push` trigger to start the release workflow. `create` trigger does not support branch filtering and since we will add a rule to not allow pushes on release notes, this should function similarly.
COAND-1016
> Release - Add release notes jobs to the release workflow

- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
Track error events for Third party SDKs and services for new Google Pay flow
COAND-1009
> Analytics - Track third party error events - Google pay

- .github/workflows/update_verification_metadata.yml
Added a new trigger to the `Update verification metadata` job to run automatically when code is pushed to a branch named `renovate/android.gradle.plugin` (this is the name of the branch that Renovate creates when updating AGP).
- For now AGP is the only dependency where we need to run this command. If we encounter similar issues in other dependencies we should add there branch names as well. Adding this step as part of any dependency update is overkill and will waste resources since the job can takes +40 minutes to complete and it will produce no code changes except with AGP.
- The trigger is set to `push` instead of `pull_request` because we should only run this job when new code is pushed.
- The `AdyenAutomationBot` will make a commit when the job is done, however this commit would …
> Automatically update verification metadata when AGP is updated

- .github/workflows/publish_to_maven_central.yml
Allow the workflow to upload the build to maven central to also be run manually
COAND-1051
> Release - Make uploading to maven central run manually

- .github/workflows/check_pr.yml
- .github/workflows/validate_dependencies.yml
- scripts/validate_dependencies_for_release_notes.py
Added a new action to run as part of `check_pr` workflow and fail if there are newly added dependencies which are not part of `included` or `excluded` lists for release notes.
Here are workflow runs:
- [New dependency has been added, which causes the action to fail](https://github.com/Adyen/adyen-testcards-android/actions/runs/12636449335/job/35208539572?pr=55) ❌
- [Action run on a PR where no dependencies have been changed](https://github.com/Adyen/adyen-testcards-android/actions/runs/12636429874/job/35208475346?pr=55) ✅
- [Action run on a PR where new dependency has been added](https://github.com/Adyen/adyen-testcards-android/actions/runs/12636662709/job/35209229890?pr=56) ✅
COAND-1055
> Release - Add action to verify new dependencies

- .github/workflows/fetch_version_name_from_release_notes.yml
- .github/workflows/trigger_finalize_release.yml
- scripts/fetch_release_notes_version_name.sh
- scripts/fetch_updated_release_notes_file.sh
Whenever there's a push (i.e. update release notes PR merge) to `release-notes` branch, `trigger_finalize_release.yml` workflow triggers `finalize_release.yml` on `release/<VERSION_NAME>` branch. 
We will keep fetching the version name and fetching the updated release notes file bash scripts on this branch, since they are needed to be placed on the same branch as the release notes files.
Although `fetch_updated_release_notes_file.sh` is on this branch, it will be run from `release/<VERSION_NAME>` branch since we will be managing the whole `finalize_release` workflow there.
COAND-1034
> Release - Add trigger finalize release workflow

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Cancelled3DS2Exception.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- RELEASE_NOTES.md
Trigger `onAdditionalDetails()` with the payload we get from 3ds2 sdk so that merchants can make a `/details` call with it.
COAND-1057
> Propagate additionalDetails on native 3ds2 cancel flow

- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressLookupView.kt
In Address Lookup the keyboard is now hidden when:
- an address is selected
- a search query is submitted
- the manual entry button is clicked
COAND-873
- For Address Lookup, the keyboard is now hidden when:
- an address is selected
- a search query is submitted
- the manual entry button is clicked
> Address Lookup hide keyboard

- example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupRepository.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/AddressLookupDelegate.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/DefaultAddressLookupDelegate.kt
Reproduction path:
1. Open card component
2. Open address lookup
3. Search "a"
4. Navigate back
5. Open address lookup again
6. Search "a" again
7. Infinite loading...
IMPORTANT: it turns out this was just a example app issue as we fully delegate the address lookup features to the merchant. 
COAND-1062
> Address Lookup fix infinite loading

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
- payto/api/payto.api
- payto/build.gradle
- payto/src/main/java/com/adyen/checkout/payto/PayToComponent.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/provider/PayToComponentProvider.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToViewProvider.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
- payto/src/test/java/com/adyen/checkout/payto/PayToComponentTest.kt
Create component for PayTo
COAND-1058
> PayTo - Create component

- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressLookupView.kt
- ui-core/src/main/res/layout/address_lookup_view.xml
- ui-core/src/main/res/values/styles.xml
Move address lookup loading spinner inside of the search view. This prevents the view from changing size while searching.
COAND-1063
- For address lookup, the loading spinner moved to the search bar to prevent "jumping" of the view.
> Move address lookup loading spinner

- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- example-app/src/main/assets/lookup_options.json
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressFormInput.kt
- In address lookup selecting a consecutive address  from the same country will now update all fields to the latest selection.
- The input is now retained when changing countries
COAND-1064
- For address lookup, when selecting a different address it will now correctly update the form's input fields.
- For address lookup, the input is now retained when changing countries.
> Fix address lookup view state

- example-app/build.gradle
- gradle/libs.versions.toml
Remove unnecessary Google Pay Compose Button dependency. It's not needed anymore after the button was moved inside the component.
> Remove unnecessary Google Pay Compose Button dependency

- twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegate.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegateTest.kt
This fixes an issue where the Twint component would override the `storePaymentMethodMode = enabled` for sessions making it impossible to store Twint.
COAND-1067
- For Twint with sessions flow, the payment method will now be stored correctly when setting `storePaymentMethodMode` to `enabled`
> Fix Twint overriding store payment method mode

- checkout-core/api/checkout-core.api
- checkout-core/src/main/java/com/adyen/checkout/core/exception/CancellationException.kt
- googlepay/api/googlepay.api
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayCancellationException.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
Emit specific exception when Google Pay is cancelled by a user. This makes it easier for merchant to distinguish between an actual error and a cancellation.
COAND-1068
- For Google Pay, when a user cancels the flow you will now get a `GooglePayCancellationException` in `onError`
> Emit specific exception when Google Pay is cancelled

- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputData.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressLookupOptionsAdapter.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputDataTest.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/view/LookupOptionTest.kt
In both the card view and search results of address lookup the addresses are now nicely formatted in two lines.
COAND-1069
- For address lookup, addresses are now formatted onto two lines
> Fix address lookup formatting

- .github/release_notes_dependency_list.toml
- build.gradle
- config/gradle/dependencyList.gradle
The `dependencyList` task lists the dependencies used directly and indirectly by the published modules of the SDK. The `includeModules` parameter includes the list of modules that use each dependency.
Default:
```
androidx.activity:activity-compose:1.10.0
androidx.activity:activity-ktx:1.10.0
androidx.activity:activity:1.10.0
androidx.annotation:annotation-experimental:1.4.0
androidx.annotation:annotation-experimental:1.4.1
androidx.annotation:annotation-jvm:1.9.1
androidx.annotation:annotation:1.9.1
androidx.appcompat:appcompat-resources:1.7.0
androidx.appcompat:appcompat:1.7.0
androidx.arch.core:core-common:2.2.0
androidx.arch.core:core-runtime:2.2.0
androidx.autofill:autofill:1.3.0-beta01
androidx.browser:browser:1.8.0
androidx.cardview:cardview:1.0.0
...
```
With `includeModules=true` …
> Add gradle task to show dependency list

- .github/workflows/codeql.yml
Added codeQL script, to override the default configuration. It will run every time there is a push on main and every Sunday (kept the default trigger).
[Here](https://github.com/Adyen/adyen-android/actions/runs/13431791320/job/37525106947) is an example of the workflow run.
COAND-1070
> Add codeQL script

- scripts/check_dependency_changes.py
When running the `dependencyList` task, if the gradle wrapper needs to be downloaded, the download progress message gets printed inside the task output which causes unwanted result such as this:
To avoid this issue we now make sure the wrapper is downloaded in advance before running the task.
> Fix downloading gradle wrapper log leaking into dependency list task output

- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardUiState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/compose/SessionsCardScreen.kt
Steps to reproduce:
- Open the address lookup mode in the card + sessions screen in the example app.
- Enter a query and select one of the options.
- Enter another query. The list of options does not render again anymore.
> Fix address lookup options not showing in example app (card + sessions)

- payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToOutputData.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/util/PayToValidationUtils.kt
- payto/src/main/res/layout/payto_view.xml
- payto/src/main/res/values/strings.xml
- payto/src/main/res/values/styles.xml
- payto/src/test/java/com/adyen/checkout/payto/internal/util/PayToValidationUtilsTest.kt
Add validation for PayTo fields
COAND-1058
> PayTo - Field validation

- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/AdyenApiResponse.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClient.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClientExt.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/OkHttpClient.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsServiceTest.kt
Responses of internal networking will now be logged like below. This will help us to debug backend related things quicker.
```
2025-02-21 14:50:09.844 15327-15401 CO.OkHttpClient         com.adyen.checkout.example           V  response - 200 .../some/path
2025-02-21 14:50:09.844 15327-15401 CO.OkHttpClient         com.adyen.checkout.example           V  header: value
2025-02-21 14:50:09.844 15327-15401 CO.OkHttpClient         com.adyen.checkout.example           V  another: one
2025-02-21 14:50:09.844 15327-15401 CO.OkHttpClient         com.adyen.checkout.example           V  {"json": "body"}
2025-02-21 14:50:09.844 15327-15401 CO.OkHttpClient         com.adyen.checkout.example           V  response - END
```
> Improve network logging

- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClientExt.kt
This fixes an issue where the log would crash if the response body couldn't be transformed into a JSONObject.
NOTE: the improved logging was not released yet, so there are no release notes needed.
COAND-1077
> Format response body accordingly for logging

- .github/workflows/check_dependency_changes.yml
- .github/workflows/get_dependency_list.yml
- config/gradle/dependencyList.gradle
- scripts/check_dependency_changes.py
- Write output to file instead of console: this solves the issue of gradle printing certain messages to the console that cannot be turned off (like downloading the wrapper).
- Add separate job to fetch dependency list: this allows fetching both base and head deps lists in parallel.
The Check dependency changes job in this PR will fail because the base PR (main) does not have the necessary changes yet,. This [test PR](https://github.com/Adyen/adyen-android/pull/2040) shows the new workflow completing successfully,.
> Dependency changes workflow fixes

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandler.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
This fixes a bug where the state was kept and consecutive 3DS challenges would re-use the state of the first challenge.
COAND-1078
For 3DS2, consecutive challenges don't fail anymore if the first challenge failed.
> Clear 3DS state after challenge is finalized

- payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToInputData.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToOutputData.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/util/PayToValidationUtils.kt
- payto/src/main/res/layout/payto_view.xml
- payto/src/main/res/values/styles.xml
- payto/src/test/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegateTest.kt
- payto/src/test/java/com/adyen/checkout/payto/internal/util/PayToValidationUtilsTest.kt
This PR fixes the BSB structure. The correct structure is: `{bank state branch}-{bank account number}`:
- Regex for bank state branch `^\d{6}$`
- Regex for bank account number `[ -~]{1,28}$`
COAND-1058
> PayTo - Swap Bank state branch with Bank account

- payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/util/PayToValidationUtils.kt
- payto/src/test/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegateTest.kt
- payto/src/test/java/com/adyen/checkout/payto/internal/util/PayToValidationUtilsTest.kt
- Do not include country code in phone number validation, since it is hardcoded and not necessary for the validation and in the view it acts as a prefix
- Recover state from outputData when view gets recreated
COAND-1058
> PayTo - Recover state when view gets recreated

- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/state/DefaultDelegateStateManager.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/state/DelegateStateManager.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/state/StateUpdaterRegistry.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/validation/DefaultValidator.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/validation/FieldValidator.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/validation/FieldValidatorRegistry.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/state/DefaultDelegateStateManagerTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/state/TestFieldValidatorRegistry.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/state/TestStateUpdaterRegistry.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegate.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/model/MBWayStateUpdaterRegistry.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/model/MBWayValidatorRegistry.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/model/MBWayStateUpdaterRegistryTest.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/model/MBWayValidatorRegistryTest.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AdyenTextInputEditText.kt
- Made `updateField()` private and exposed two different functions to update the value and the focus of a field
- Aligned generics order, to keep it consistent within the implementation
- Added `safeUpdateText()` in `AdyenTextInputEditText` to make it easier to update a text without triggering an update callback.
COAND-935
> State management changes - MBWay - Improvements

- ach/src/main/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegate.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegateTest.kt
- boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/DefaultBoletoDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/AddressInputModel.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputData.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/AddressFormInput.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/AddressValidationUtils.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/model/AddressOutputDataTest.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/util/AddressFormUtilsTest.kt
Pass the full country name through address output, so we can display it in the card component.
COAND-1039
- For address lookup, the full country name will be displayed instead of the country code.
> Display full country name in address lookup result

- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ImageLoadingExtensions.kt
Only set placeholder image if ImageView doesn't have an image yet. This will prevent flickering of the ImageView when loading a new image into it.
> Prevent flickering of ImageViews

- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardBrandAdapter.kt
Using `getChangePayload()` enables us to only update radio button, not the whole item in `RecyclerView`. This solves flickering issue on selected state changes.
COAND-1085
> Co-badged Cards: Use getChangePayload in DiffCallback

- drop-in/api/drop-in.api
- drop-in/src/main/AndroidManifest.xml
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInRedirectHandlingActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
Handle Drop-in redirects in a separate activity. This allows merchants to override Drop-in's intent filter.
- You can now override the default [returnUrl](https://docs.adyen.com/api-explorer/Checkout/latest/post/sessions#request-returnUrl) value used by Drop-in. For example, to configure Drop-in to handle this URL `https://your.website.com/adyen-drop-in` as an [App Link](https://developer.android.com/training/app-links), pass its value from your backend to the Checkout API inside `returnUrl`, and declare an intent filter in your manifest with a matching configuration:
```xml
<activity
android:name="com.adyen.checkout.dropin.DropInRedirectHandlingActivity"
android:exported="true"
android:theme="@style/AdyenCheckout.Translucent">
<intent-filter android:autoVerify="true">
<action …
```
>  Handle drop-in redirects in separate activity

- ach/src/main/java/com/adyen/checkout/ach/internal/ui/view/ACHDirectDebitView.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/view/BacsDirectDebitInputView.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/view/BlikView.kt
- boleto/src/main/java/com/adyen/checkout/boleto/internal/ui/view/BoletoView.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BacsDirectDebitDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GenericComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardComponentDialogFragment.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/view/EContextView.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardView.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
- meal-voucher-fr/src/main/java/com/adyen/checkout/mealvoucherfr/internal/ui/view/MealVoucherFRView.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/view/SepaView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ViewExtensions.kt
Directly requesting focus in the view, like we previously had, didn't work for all use cases (compose for example). It is better to let the merchant decide if they want to focus on the `AdyenComponentView` or their own view. In drop-in we are in control, so we can focus on the first input
NOTE: release notes are already provided by https://github.com/Adyen/adyen-android/pull/2098
COSDK-138
> Request focus on first input in drop-in

- ui/api/ui.api
- ui/src/main/java/com/adyen/checkout/ui/internal/AdyenTextField.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/AdyenTextFieldDefaults.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/InternalTextFieldStyle.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenTextFieldStyle.kt
- ui/src/main/res/drawable/ic_checkmark.xml
Add `AdyenTextField` composable. The checkmark drawable was added for preview purposes, but we will need it later as well. 
In the preview below the third field in every column is supposed to have a focussed state. Unfortunately, only the first preview can have a focussed state and it won't display for other previews.
COAND-1084
> Text field input composable

- .aiexclude
- .gitignore
- example-app/.aiexclude
Followed [this doc](https://developer.android.com/studio/preview/gemini/aiexclude) to exclude sensitive and unnecessary files for Gemini access.
The content is the same as in `.gitignore` files.
COSDK-486
> Gemini - Exclude files for Gemini access - v6

- card/src/main/res/layout/card_view.xml
Fix having no margin below brand selection section in CardView.
COSDK-493
[//]: # (Use the headers listed below to organize your release notes. Each section should begin with ### followed by a valid label)
[//]: # (Allowed labels: `Breaking changes`, `New`, `Fixed`, `Improved`, `Changed`, `Removed`, `Deprecated`)
[//]: # (Content will be grouped under a specific label until the next header #, ##, or ### is found)
[//]: # (### New)
[//]: # (List any new features or enhancements)
[//]: # (e.g. - Added functionality for user authentication)
[//]: # (### Fixed)
[//]: # (List fixes here)
[//]: # (e.g. - …
> Add bottom margin to card brand selection section

- .github/workflows/publish_to_maven_central.yml
- config/gradle/release.gradle
- scripts/drop_all_open_ossrh_repositories.py
- scripts/move_ossrh_repository_to_central_portal.py
The workflows are updated to use [OSSRH Staging API](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/) to publish artifacts to Central Portal.
A workflow run can be found [here](https://github.com/Adyen/adyen-android/actions/runs/15579793582). We still get `104` error for the last step, even though it successfully uploads the repository to Central Portal. Currently waiting for a response from Sonatype.
COSDK-475
> Sonatype - Migrate workflows to Sonatype Central portal

- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- googlepay/api/googlepay.api
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParams.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapper.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtils.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtilsTest.kt
`checkoutOption` influences the submit button text inside of the Google Pay sheet. By setting a certain value you can change the text from "Pay" to "Pay now" for example.
COSDK-502
- Add `checkoutOption` to the Google Pay configuration. With this value you can change the submit button text displayed inside of the Google Pay sheet.
> Add checkoutOption configuration to Google Pay

- core/src/main/java/com/adyen/checkout/core/internal/AdvancedPaymentFacilitatorFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/internal/SessionsPaymentFacilitatorFactory.kt
Making `PaymentFacilitator` flow agnostic will make it easier for us to manage the payment flow. This PR removes `checkoutSession` and `checkoutConfiguration` from PaymentFacilitator so it only depends on `componentParams`.
COSDK-142
> v6 - Pass component params to PaymentFacilitator

- .github/workflows/publish_to_maven_central.yml
- scripts/move_ossrh_repository_to_central_portal.py
This PR adds back the step to move repository from Staging API to Central Portal. The changes have been reviewed in [this PR](https://github.com/Adyen/adyen-android/pull/2154).
Workflow run can be found [here](https://github.com/Adyen/adyen-android/actions/runs/15968338423).
COSDK-516
> Sonatype - Add a step to move repository from Staging API to Central Portal

- card/api/card.api
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/DualBrandData.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/DualBrandedCardHandler.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/util/DualBrandedCardHandlerTest.kt
This change makes sure we only display co-badged selection for cards that contain Bcmc, Carte Bancaire or Dankort.
COSDK-529
> v6 - Disable co-badged for not supported brands

- core/src/test/java/com/adyen/checkout/core/common/internal/ui/state/DefaultDelegateStateManagerTest.kt
- core/src/testFixtures/java/com/adyen/checkout/test/ui/state/TestFieldTransformerRegistry.kt
- mbway/build.gradle
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/MBWayComponentStateTest.kt
To let the mbway module use a test class from the core module they needed to be moved to test fixtures. After that the disabled tests could be re-enabled.
> v6 - Move core test class to test fixtures

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/components/AdyenPaymentFlow.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6Activity.kt
- Add `AdyenCheckoutTheme` as a parameter in `AdyenPaymentFlow`
- Apply `AdyenCheckoutTheme` to composables
- Pass dark/light colors in example implementation
> v6 - Apply styling to components

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/common/AdyenLogLevel.kt
- core/src/main/java/com/adyen/checkout/core/common/AdyenLogger.kt
- core/src/main/java/com/adyen/checkout/core/common/internal/helper/AdyenLog.kt
- core/src/main/java/com/adyen/checkout/core/common/internal/helper/LogcatLogger.kt
- core/src/test/java/com/adyen/checkout/core/common/internal/helper/AdyenLoggerTest.kt
- core/src/testFixtures/java/com/adyen/checkout/test/PrintLogger.kt
`AdyenLogger` and related classes are moved to `core` module. Also removed the deprecated `setLogLevel` function.
COSDK-512
> v6- Move AdyenLogger to core module

- example-app/src/main/AndroidManifest.xml
- example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/SessionsGiftCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/compose/SessionsGooglePayViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6SessionsActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6SessionsViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6ViewModel.kt
Create example integration for v6 components with sessions
> v6 - Sessions example

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- action-core/src/main/java/com/adyen/checkout/action/core/internal/provider/GenericActionComponentProvider.kt
- action-core/src/main/java/com/adyen/checkout/action/core/internal/ui/DefaultGenericActionDelegate.kt
- action-core/src/test/java/com/adyen/checkout/action/core/internal/ui/ActionDelegateProviderTest.kt
- action-core/src/test/java/com/adyen/checkout/action/core/ui/DefaultGenericActionDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Action.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2ChallengeAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2FingerprintAction.kt
The old 2 action 3DS2 flow is deprecated for v5. To communicate this clearly the specific action classes are now marked deprecated.
COSDK-569
- The `Threeds2FingerprintAction` and `Threeds2ChallengeAction` actions are now deprecated. Use `Threeds2Action` instead.
> v5 - Deprecate old 3DS2 actions

- ui-core/api/ui-core.api
- ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/PaymentComponentUIState.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/SubmitHandler.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/ui/SubmitHandlerTest.kt
This PR makes sure that we hide keyboard automatically when a shopper clicks on the pay button.
COSDK-571
[//]: # (Use the headers listed below to organize your release notes. Each section should begin with ### followed by a valid label)
[//]: # (Allowed labels: `Breaking changes`, `New`, `Fixed`, `Improved`, `Changed`, `Removed`, `Deprecated`)
[//]: # (Content will be grouped under a specific label until the next header #, ##, or ### is found)
[//]: # (### New)
[//]: # (List any new features or enhancements)
[//]: # (e.g. - Added functionality for user authentication)
[//]: # (### Fixed)
[//]: # (List …
> v5 - Hide keyboard automatically on pay button click

- .github/workflows/check.yml
- .github/workflows/create_github_release.yml
- .github/workflows/create_release_notes_pr.yml
- .github/workflows/finalize_release.yml
- .github/workflows/generate_release_notes.yml
- .github/workflows/generate_version_name.yml
- .github/workflows/prepare_release.yml
- .github/workflows/publish_docs.yml
- .github/workflows/publish_to_maven_central.yml
- .github/workflows/update_release_notes.yml
Set minimal permissions for all workflows related to creating releases.
[6 alerts left](https://github.com/Adyen/adyen-android/security/code-scanning?query=is%3Aopen+branch%3Achore%2Frelease_workflow_permissions)
COSDK-583
> Specify release workflow permissions

- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitComponent.kt
- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionComponent.kt
- core/src/main/java/com/adyen/checkout/core/components/AdyenPaymentFlow.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/ui/StatusPollingComponent.kt
- core/src/main/java/com/adyen/checkout/core/redirect/internal/DefaultRedirectHandler.kt
- core/src/main/java/com/adyen/checkout/core/redirect/internal/RedirectHandler.kt
- core/src/main/java/com/adyen/checkout/core/redirect/internal/ui/RedirectEvent.kt
- core/src/main/java/com/adyen/checkout/core/redirect/internal/ui/RedirectViewEvent.kt
- core/src/test/java/com/adyen/checkout/core/action/internal/TestActionComponent.kt
- Removed `context` from `handleAction`.
- Implemented necessary logic in `PaymentFacilitator`
- Moved redirect logic to its own `RedirectEvent` composable
COSDK-547
> V6 - Await - Improvements

- .github/workflows/create_release_notes_pr.yml
The release notes PR was not created during the release and this should solve it.
> Give create release notes PR workflow contents write permission

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
Prevent the 3DS2 challenge from displaying when the cancel button is clicked by closing the transaction that was created before.
COSDK-607
- For 3DS2, when the cancel button is clicked before the challenge is displayed, then the challenge will no longer display.
> v5 - Prevent 3DS2 challenge when cancel button is clicked
