Adyen/adyen-android

- README.md
> Update proguard rules on Readme.

- build.gradle
- config/gradle/checksums.gradle
- drop-in/src/main/java/com/adyen/checkout/card/DropInCardView.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ActionHandler.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/LoadingDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodAdapter.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- example-app/build.gradle
- example-app/src/androidTest/java/com/adyen/checkout/example/MainActivityTest.kt
- example-app/src/androidTest/java/com/adyen/checkout/example/rules/OkHttpIdlingResourceRule.kt
- example-app/src/androidTest/java/com/adyen/checkout/example/utils/Espresso.kt
- example-app/src/androidTest/java/com/adyen/checkout/example/utils/UiAutomator.kt
- example-app/src/main/java/com/adyen/checkout/example/di/NetworkModule.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/PaymentMethodsViewModel.kt
Fix imports on UI tests for example-app
Fix redundant qualifier names on some classes
Update some dependencies
> Small fixes

- README.md
Update readme file to display latest version number.
> Update latest version on Readme

- config/detekt/detekt-baseline.xml
- config/detekt/detekt-config.yml
- config/gradle/detekt.gradle
- core-v3/src/main/java/com/adyen/checkout/core/log/LogUtil.java
- core-v3/src/main/java/com/adyen/checkout/core/util/KotlinBase.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- example-app/src/androidTest/java/com/adyen/checkout/example/MainActivityTest.kt
- example-app/src/androidTest/java/com/adyen/checkout/example/utils/Espresso.kt
- Re enable Detekt breaking build
- Allow TODO comments on detekt config
- Fix some code warnings.
> Re enable Detekt

- drop-in/build.gradle
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- Leave Flow as an experimental implementation
- Remove TEST comments and add proper comments
Tested flow with 3DS2 Component, Redirect Component and using don't keep activities dev flag.
Kept debug logs for further investigation.
> Clean up comments and leave Flow as an experiment for now.

- example-app/build.gradle
- example-app/src/main/java/com/adyen/checkout/example/di/ViewModelModule.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- gradle.properties
- Update `koin-android-viewmodel` to `koin-androidx-viewmodel`
- Disable Jetifier
> Update Koin to AndroidX and disable Jetifier.

- scripts/trigger_release_action.sh
Create script to trigger manual release of v3 branch.
Script expects variable GITHUB_ACCESS_TOKEN.
> Script to trigger release action on V3

- LICENSE
- README.md
- Add missing LICENSE file.
- Update latest version on README.
**Fixed issue**: #267
> Add LICENSE file.

- 3ds2/build.gradle
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.java
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.java
- Forgot to pass the `protocolVersion` from the 3DS2 Configuration to the SDK
> Pass the protocol version from the Configuration on 3DS2.

- base-v3/src/main/java/com/adyen/checkout/base/component/BaseConfigurationBuilder.java
- base-v3/src/main/java/com/adyen/checkout/base/component/Configuration.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- Cherry pick #276 to `develop` branch.
> Fix clientKey validation for BaseConfiguration on DropIn.

- README.md
- Reflect release on V3 branch on readme of default branch.
> Update latest version on Readme from V3 branch release.

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.java
- base-v3/src/main/java/com/adyen/checkout/base/model/payments/response/Action.java
- base-v3/src/main/java/com/adyen/checkout/base/model/payments/response/Threeds2Action.java
- base-v3/src/main/java/com/adyen/checkout/base/util/ActionTypes.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ActionHandler.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- Merge both 3DS2 fingerprint and 3DS2 challenge actions into one 3DS2 action with subtypes
> Change 3DS2 Action type structure

- base-v3/src/main/java/com/adyen/checkout/base/model/payments/request/SepaPaymentMethod.java
- base-v3/src/main/java/com/adyen/checkout/base/util/PaymentMethodTypes.java
- sepa-base/src/main/java/com/adyen/checkout/sepa/SepaComponent.java
- Fix the keys for SEPA payment method details.
> Update SepaPaymentMethod keys and enable it again.

- README.md
Update readme file on main branch to reflect release on v3 branch.
> Update latest version on readme file.

- components-core/src/main/java/com/adyen/checkout/components/model/paymentmethods/InputDetail.java
- components-core/src/main/java/com/adyen/checkout/components/model/paymentmethods/Item.java
- components-core/src/main/java/com/adyen/checkout/components/model/paymentmethods/PaymentMethod.java
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponent.java
- Support issuers in details for older api versions
> Revert support for issuers in details object on old API

- example-app/build.gradle
- example-app/default.local.gradle
- example-app/src/main/java/com/adyen/checkout/example/data/api/CheckoutApiService.kt
- example-app/src/main/java/com/adyen/checkout/example/di/NetworkModule.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
Quality of life fix to allow same local.gradle behavior as v4.
> Fix local.gradle

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.java
- await/src/main/java/com/adyen/checkout/await/AwaitConfiguration.java
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponentProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.java
- blik/src/main/java/com/adyen/checkout/blik/BlikConfiguration.java
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.java
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardValidationUtils.java
- card/src/main/java/com/adyen/checkout/card/repository/PublicKeyRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/base/BaseConfigurationBuilder.java
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayConfiguration.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashConfiguration.java
- eps/src/main/java/com/adyen/checkout/eps/EPSConfiguration.java
- example-app/default.local.gradle
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.java
- ideal/src/main/java/com/adyen/checkout/ideal/IdealConfiguration.java
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListConfiguration.java
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayConfiguration.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayConfiguration.java
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingConfiguration.java
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectConfiguration.java
- sepa/src/main/java/com/adyen/checkout/sepa/SepaConfiguration.java
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionConfiguration.java
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayConfiguration.java
- Make client key required for all configurations.
- Remove public key from CardConfiguration
> Make client key required

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/action/ActionComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GenericComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
Observe `LiveData` with `viewLifecycleOwner` instead of `this` in fragments.
https://developer.android.com/reference/androidx/fragment/app/Fragment.html#getViewLifecycleOwner()
> Observe with lifecycle owner in fragments

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
When returning from another Activity like a Redirect, if the DropInActivity had been destroyed, the result was parsed before the DropInService was bound, causing the request to fail.
- Added a queue variable to cache the request until the service is bound.
> Queue API requests if the service is not yet bound.

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.java
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentState.kt
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/NewCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/repository/PublicKeyRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/GenericComponentState.java
- components-core/src/main/java/com/adyen/checkout/components/PaymentComponentState.java
- components-core/src/main/java/com/adyen/checkout/components/base/BasePaymentComponent.java
- components-core/src/test/java/com/adyen/checkout/components/base/BaseComponentTest.java
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/ComponentDialogViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/base/BaseComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GenericComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentViewModel.kt
- drop-in/src/main/res/layout/fragment_card_component.xml
- drop-in/src/main/res/layout/fragment_generic_component.xml
- drop-in/src/main/res/layout/fragment_stored_payment_method.xml
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.java
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponentState.java
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponent.java
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayComponent.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaComponent.java
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayComponent.java
We need a way to handle the component initialization state:
- Add `isReady` flag to components to indicate if the initialization is done
- Handle flag in Drop in fragments
> Handle component initialization

- build.gradle
- config/gradle/checksums.gradle
Update WeChat Pay checksum since it's now on Maven Central.
> Update 3DS2 SDK to 2.2.2

- 3ds2/build.gradle
- build.gradle
Update 3DS2 SDK to 2.1.0-rc09.
This fixes SecurityException enforced in Android 10.
> [V3] Update 3DS2 SDK

- drop-in/src/main/AndroidManifest.xml
- example-app/src/main/AndroidManifest.xml
https://developer.android.com/about/versions/12/behavior-changes-12#exported
> Add android:exported to manifest

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardValidationUtils.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/NewCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/data/CardType.java
- card/src/main/java/com/adyen/checkout/card/repository/BinLookupRepository.kt
Disable Luhn check if Bin Lookup returns `enableLuhnCheck` false.
> Disable Luhn check on Bin Lookup response

- bcmc/src/main/res/layout/bcmc_view.xml
|Before|After|
|---|---|
|![Screenshot_1632131528](https://user-images.githubusercontent.com/9079915/133984067-470e14ef-735c-4b8d-baba-a4f01cb624cf.png)|![Screenshot_1632131477](https://user-images.githubusercontent.com/9079915/133984052-4db867ae-af01-447b-9a77-dd9ac7fc472d.png)|
> Fix visual bug in BCMC component card icon

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodListDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodsListViewModel.kt
When we have multiple payment methods with the same type in drop-in, clicking on any of them will always open the first one.
> Multiple payment methods with same type

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2ComponentProvider.kt
- await/src/main/java/com/adyen/checkout/await/AwaitComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/ActionComponentProvider.java
- components-core/src/main/java/com/adyen/checkout/components/base/BaseActionComponent.java
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponentProvider.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponentProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponentProvider.kt
Re-add removed methods and deprecate them.
> Remove breaking changes

- example-app/src/main/res/drawable/ic_settings.xml
- example-app/src/main/res/menu/main_menu.xml
Add a settings icon instead of having to click on the overflow menu then click Settings
> Add icon for example app settings

- components-core/src/main/java/com/adyen/checkout/components/model/payments/Amount.java
- components-core/src/main/java/com/adyen/checkout/components/model/payments/request/Order.kt
- components-core/src/main/java/com/adyen/checkout/components/model/payments/request/PaymentComponentData.java
- components-core/src/main/java/com/adyen/checkout/components/model/payments/response/BalanceResult.kt
- components-core/src/main/java/com/adyen/checkout/components/model/payments/response/OrderResponse.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GenericComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/giftcard/GiftCardBalanceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/CheckoutApiService.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/paymentsRequest/PaymentMethodsRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/paymentMethods/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAsyncDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/PaymentMethodsViewModel.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.java
- Add `orders` call.
- Include order in `/payments` call.
- Allow dynamically updating drop in with order and payment methods.
> Giftcard: order creation

- components-core/src/main/java/com/adyen/checkout/components/util/PaymentMethodTypes.java
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInViewModel.kt
- example-app/src/main/AndroidManifest.xml
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAsyncDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleFullAsyncDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/util/GiftCardBalanceUtils.kt
- Some final improvements and fixes.
- Docs updates.
- Enabling gift cards.
> Gift card: final fixes

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardListAdapter.kt
- card/src/main/java/com/adyen/checkout/card/CardOutputData.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/NewCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/res/layout/card_view.xml
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/CardComponentDialogFragment.kt
- drop-in/src/main/res/layout/fragment_card_component.xml
| Type | Before | After |
| - | - | - |
| Visible | ![image](https://user-images.githubusercontent.com/17701279/160148634-71edc30d-b142-4580-bf11-903038e6f756.png) | ![image](https://user-images.githubusercontent.com/17701279/160149262-cfdf5878-e716-475a-a565-9071b1744aa9.png) |
| Not visible | ![image](https://user-images.githubusercontent.com/17701279/160148796-123293cb-4e1f-43d6-b429-fe431d2fe831.png) | ![image](https://user-images.githubusercontent.com/17701279/160149501-3810a92d-c629-4ee9-9d89-52465c37e6b3.png) |
> Move card brands below input field

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/connection/SubmitFingerprintService.kt
- card/src/main/java/com/adyen/checkout/card/api/BinLookupService.kt
- components-core/src/main/java/com/adyen/checkout/components/api/OrderStatusService.kt
- components-core/src/main/java/com/adyen/checkout/components/api/PublicKeyService.kt
- components-core/src/main/java/com/adyen/checkout/components/model/PublicKeyResponse.kt
- components-core/src/main/java/com/adyen/checkout/components/repository/PublicKeyRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/status/api/StatusApi.kt
- components-core/src/main/java/com/adyen/checkout/components/status/api/StatusService.kt
- components-core/src/main/java/com/adyen/checkout/components/status/api/StatusTask.kt
Use `HttpClient` extensions in service classes and refactor `StatusService` a bit
> Refactor Services

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/repository/SubmitFingerprintRepository.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/repository/BinLookupRepository.kt
- checkout-core/build.gradle
- checkout-core/src/main/java/com/adyen/checkout/core/api/ErrorResponseBody.kt
- checkout-core/src/main/java/com/adyen/checkout/core/api/HttpException.kt
- checkout-core/src/main/java/com/adyen/checkout/core/api/OkHttpClient.kt
- checkout-core/src/main/java/com/adyen/checkout/core/util/ResultExt.kt
- components-core/src/main/java/com/adyen/checkout/components/repository/OrderStatusRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/repository/PublicKeyRepository.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/repository/SessionRepository.kt
- Use Kotlin Result in repositories to handle exceptions
- Differentiate between HTTP errors and "normal" IO errors
- Parse the error response if possible
> Refactor repositories

- components-core/src/main/java/com/adyen/checkout/components/base/lifecycle/ViewModelExt.kt
This PR apparently broke everything https://github.com/Adyen/adyen-android/pull/703. Not sure how it built on CI 🤷
> Fix compile error in viewModelExt

- components-core/src/main/java/com/adyen/checkout/components/model/connection/OrderPaymentMethod.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/repository/SessionRepository.kt
> Initialize session service

- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleFullAsyncDropInService.kt
Added the log line in this one as well for you @jreij
> Handle refused in partial payment flow correctly

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponentProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/DefaultBcmcDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/repository/BinLookupRepository.kt
- cse/src/main/java/com/adyen/checkout/cse/CardEncrypter.kt
- cse/src/main/java/com/adyen/checkout/cse/DefaultCardEncrypter.kt
- cse/src/main/java/com/adyen/checkout/cse/TestCardEncrypter.kt
- cse/src/main/java/com/adyen/checkout/cse/UnencryptedCard.kt
- giftcard/build.gradle
- giftcard/src/main/java/com/adyen/checkout/giftcard/DefaultGiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardDelegate.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/DefaultGiftCardDelegateTest.kt
- Move logic from `GiftCardComponent` into a delegate
- Convert `CardEncrypter` from an object to a normal class
- Add a test implementation of `CardEncrypter`
> Add gift card delegate

- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GooglePayComponentDialogFragment.kt
- googlepay/build.gradle
- googlepay/src/main/java/com/adyen/checkout/googlepay/DefaultGooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponentProvider.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayInputData.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/DefaultGooglePayDelegateTest.kt
- Add delegate + tests
- Fix crash in `GooglePayComponentDialogFragment`
> GooglePayDelegate: Add GooglePayDelegate

- RELEASE_NOTES.md
- bacs/src/main/res/template/values/strings.xml.tt
- bacs/src/main/res/values-ar/strings.xml
- bacs/src/main/res/values-cs-rCZ/strings.xml
- bacs/src/main/res/values-da-rDK/strings.xml
- bacs/src/main/res/values-de-rDE/strings.xml
- bacs/src/main/res/values-el-rGR/strings.xml
- bacs/src/main/res/values-es-rES/strings.xml
- bacs/src/main/res/values-fi-rFI/strings.xml
- bacs/src/main/res/values-fr-rFR/strings.xml
- bacs/src/main/res/values-hr-rHR/strings.xml
- bacs/src/main/res/values-hu-rHU/strings.xml
- bacs/src/main/res/values-it-rIT/strings.xml
- bacs/src/main/res/values-ja-rJP/strings.xml
- bacs/src/main/res/values-ko-rKR/strings.xml
- bacs/src/main/res/values-nb-rNO/strings.xml
- bacs/src/main/res/values-nl-rNL/strings.xml
- bacs/src/main/res/values-pl-rPL/strings.xml
- bacs/src/main/res/values-pt-rBR/strings.xml
- bacs/src/main/res/values-ro-rRO/strings.xml
- bacs/src/main/res/values-ru-rRU/strings.xml
- bacs/src/main/res/values-sk-rSK/strings.xml
- bacs/src/main/res/values-sl-rSI/strings.xml
- bacs/src/main/res/values-sv-rSE/strings.xml
- bacs/src/main/res/values-zh-rCN/strings.xml
- bacs/src/main/res/values-zh-rTW/strings.xml
- bacs/src/main/res/values/strings.xml
> Update release notes 4.7.1

- card/src/main/java/com/adyen/checkout/card/ui/CardNumberInput.kt
- components-core/src/main/java/com/adyen/checkout/components/base/BasePaymentComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/model/payments/response/Action.kt
- components-core/src/main/java/com/adyen/checkout/components/util/CheckoutCurrency.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayOutputData.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaOutputData.kt
`TextUtils` was used in the java classes but it's not necessary anymore with Kotlin and it creates problems with testing.
> Remove TextUtils

- await/src/main/java/com/adyen/checkout/await/AwaitComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/status/StatusRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/test/TestStatusRepository.kt
- components-core/src/test/java/com/adyen/checkout/components/status/DefaultStatusRepositoryTest.kt
- config/gradle/checksums.gradle
- dependencies.gradle
- qr-code/build.gradle
- qr-code/src/main/java/com/adyen/checkout/qrcode/DefaultQRCodeDelegate.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponent.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponentProvider.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeCountDownTimer.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeDelegate.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeOutputData.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeView.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/TimerData.kt
- qr-code/src/test/java/com/adyen/checkout/qrcode/DefaultQRCodeDelegateTest.kt
- Move logic inside `QRCodeComponent` to `DefaultQRCodeDelegate`
- Add AndroidX Lifecycle LiveData dependency, so it's easy to convert flows to LiveData
- Add test implementation of `StatusRepository`
> QRCodeDelegate: Add QRCodeDelegate

- await/build.gradle
- await/src/main/java/com/adyen/checkout/await/AwaitComponent.kt
- await/src/main/java/com/adyen/checkout/await/AwaitComponentProvider.kt
- await/src/main/java/com/adyen/checkout/await/AwaitDelegate.kt
- await/src/main/java/com/adyen/checkout/await/DefaultAwaitDelegate.kt
- await/src/test/java/com/adyen/checkout/await/DefaultAwaitDelegateTest.kt
- Move logic from `AwaitComponent` to a delegate
> AwaitDelegate: Add AwaitDelegate

- issuer-list/build.gradle
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/DefaultIssuerListDelegateTest.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/utils/TestIssuerPaymentMethod.kt
add test cases to DefaultIssuerListDelegate
> add test cases to DefaultIssuerListDelegate

- bacs/build.gradle
- bacs/src/test/java/com/adyen/checkout/bacs/DefaultBacsDirectDebitDelegateTest.kt
Add unit tests for DefaultBacsDirectDebitDelegate class
> Add unit tests for DefaultBacsDirectDebitDelegate class

- dependencies.gradle
Robolectric should be compatible with Java17 with this update
> UpdateRobolectric: Update Robolectric to 4.8.2

- example-app/src/main/java/com/adyen/checkout/example/data/storage/KeyValueStorage.kt
- example-app/src/main/java/com/adyen/checkout/example/di/StorageModule.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/res/values/arrays.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/xml/preferences.xml
Add option to enable address form for card component from the configuration menu
> AddressFormConfig: Make card address form configurable

- checkout-core/src/main/java/com/adyen/checkout/core/log/Logger.kt
- example-app/src/main/java/com/adyen/checkout/example/CheckoutExampleApplication.kt
- example-app/src/main/java/com/adyen/checkout/example/di/ThemeModule.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/NightThemeRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/ConfigurationActivity.kt
- example-app/src/main/res/values/arrays.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/xml/preferences.xml
https://user-images.githubusercontent.com/17701279/194528646-e9b53546-1b92-4236-b349-6d6ef51467b7.mp4
> NightThemeConfig: Make theme (dark mode) configurable from the settings

- dependencies.gradle
- example-app/build.gradle
This will help us detect and fix potential memory leaks
> LeakCanary: Add LeakCanary to example app

- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/api/model/Brand.kt
- card/src/main/java/com/adyen/checkout/card/data/DetectedCardType.kt
- card/src/main/java/com/adyen/checkout/card/repository/DefaultDetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/test/TestDetectCardTypeRepository.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/DualBrandedCardUtilsTest.kt
- card/src/test/java/com/adyen/checkout/card/StoredCardDelegateTest.kt
- checkout-core/src/main/java/com/adyen/checkout/core/model/JsonUtils.kt
https://user-images.githubusercontent.com/17701279/196677887-d9458fbc-e28d-495c-ad99-9582099aded3.mp4
> Focus on next field when card number matches pan

- example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewState.kt
- Make sure to always observe the component when the activity is created
- Convert validation highlighting to an event instead of a state
> Fix bugs in card example

- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/data/SessionDetails.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInActivityEvent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/CheckoutApiService.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/CheckoutSession.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/model/SessionModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/provider/CheckoutSessionInitializer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/provider/CheckoutSessionProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/provider/CheckoutSessionResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/repository/SessionRepository.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/repository/SessionRepositoryTest.kt
This PR is an attempt at providing a public API allowing merchants to create and setup a session, which they can pass to drop-in/components.
> Provide public API for session creation

- card/src/main/java/com/adyen/checkout/card/AddressConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/util/AddressValidationUtils.kt
> OptionalAddressFields: Remove addressFieldPolicy from FullAddress (v4)

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponentParamsMapper.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponentProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/DefaultBcmcDelegate.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/BcmcComponentParamsMapperTest.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/DefaultBcmcDelegateTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
Create a data class for the BCMC component that shadows the BCMC configuration and includes any extra parameters we need.
COAND-549
> Create BCMC component parameters for internal use

- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayComponentProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashComponentProvider.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSComponentProvider.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSConfiguration.kt
- ideal/src/main/java/com/adyen/checkout/ideal/IdealComponentProvider.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/DefaultIssuerListDelegate.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponentParams.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponentParamsMapper.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListConfiguration.kt
- issuer-list/src/test/java/IssuerListComponentParamsMapperTest.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/DefaultIssuerListDelegateTest.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/utils/TestIssuerListConfiguration.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayComponentProvider.kt
- online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/OnlineBankingPLComponentProvider.kt
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingComponentProvider.kt
Create a data class for the issuer list components that shadows the issuer list configurations and includes any extra parameters we need.
COAND-549
> Create issuer list component parameters for internal use

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Configuration.kt
- await/src/main/java/com/adyen/checkout/await/AwaitConfiguration.kt
- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitConfiguration.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- components-core/src/main/java/com/adyen/checkout/components/base/BaseConfigurationBuilder.kt
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- instant/src/main/java/com/adyen/checkout/instant/InstantPaymentConfiguration.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZConfiguration.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKConfiguration.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankConfiguration.kt
These params are available in the constructor now so we don't need their setters anymore
COAND-549
> Remove setShopperLocale and setEnvironment in configuration builders

- README.md
- RELEASE_NOTES.md
- dependencies.gradle
- example-app/build.gradle
> Update README and RELEASE_NOTES on develop

- .github/pull_request_template.md
- Not all points in this checklist are applicable for every PRs. Clarifying that the whole line should be removed if that is the case.
- Adding some clarification over the PR labels to be used.
COAND-670
> Clarify optional points in checklist

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PreselectedStoredPaymentViewModel.kt
- drop-in/src/main/res/layout/fragment_giftcard_component.xml
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- ui-core/src/main/java/com/adyen/checkout/components/ui/SubmitHandler.kt
Fix comments that's left out in [this PR](https://github.com/Adyen/adyen-android/pull/921).
COAND-651
> Address commented out code and todos related to Pay Button changes

- checkout-core/src/main/java/com/adyen/checkout/core/image/ImageLoader.kt
- ui-core/src/main/java/com/adyen/checkout/components/image/ImageLoadingExtensions.kt
- Make image loader life cycle aware
COAND-673
> Make image loader life cycle aware

- checkout-core/src/main/java/com/adyen/checkout/core/image/ImageLoader.kt
- checkout-core/src/main/java/com/adyen/checkout/core/image/InMemoryCache.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- ui-core/src/main/java/com/adyen/checkout/components/image/ImageLoadingExtensions.kt
- Add caching to image loader
- Ensure images are set from correct thread
COAND-673
> Add caching to image loader

- checkout-core/src/main/java/com/adyen/checkout/core/api/HttpClient.kt
- checkout-core/src/main/java/com/adyen/checkout/core/api/HttpClientExt.kt
- checkout-core/src/main/java/com/adyen/checkout/core/api/OkHttpClient.kt
- components-core/src/main/java/com/adyen/checkout/components/status/api/StatusService.kt
Make HttpClient functions suspending. This allows us to close the network connection properly when a coroutine is cancelled.
COAND-693
> Make HttpClient functions suspending

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitInputView.kt
- components-core/src/main/java/com/adyen/checkout/components/util/ValidationUtils.kt
- components-core/src/test/java/com/adyen/checkout/components/util/ValidationUtilsTest.kt
I changed the email regex and I added unit test for validation
COAND-678
> Change Email regex add unit test

- .idea/copyright/Adyen_MIT.xml
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/utils/TestOnlineBankingConfiguration.kt
Fix duplicate copy right
COAND-623
> Fix duplicate copy right

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- bacs/src/test/java/com/adyen/checkout/bacs/BacsDirectDebitComponentTest.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/BcmcComponentTest.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.kt
- blik/src/test/java/com/adyen/checkout/blik/BlikComponentTest.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/test/java/com/adyen/checkout/card/CardComponentTest.kt
- components-core/src/main/java/com/adyen/checkout/components/ButtonComponent.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PreselectedStoredPaymentViewModel.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/GiftCardComponentTest.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListComponent.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/IssuerListComponentTest.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayComponent.kt
- mbway/src/test/java/com/adyen/checkout/mbway/MBWayComponentTest.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/OnlineBankingComponent.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/OnlineBankingComponentTest.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaComponent.kt
- sepa/src/test/java/com/adyen/checkout/sepa/SepaComponentTest.kt
Make it possible for merchants to trigger submit action manually. 
COAND-691
> Add submit function to ButtonComponent

- action/src/main/java/com/adyen/checkout/action/DefaultActionHandlingComponent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewState.kt
- example-app/src/main/res/layout/activity_blik.xml
Use new/simple way of action handling in Blik example. Also, fixes a crash in actions views that expect a specific type of action delegate.
COAND-700
> Use new/simple way of action handling in Blik example

- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsViewState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/res/layout/fragment_bacs.xml
- example-app/src/main/res/values/strings.xml
- voucher/src/main/java/com/adyen/checkout/voucher/VoucherView.kt
Add example implementation of BACS. Also cleaned up some unnecessary things in the card example and fixed a bug in `VoucherView`.
COAND-701
> Add example implementation of BACS

- example-app/src/main/java/com/adyen/checkout/example/data/storage/KeyValueStorage.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/res/layout/fragment_instant.xml
- example-app/src/main/res/values/arrays.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/xml/preferences.xml
Add sample InstantPaymentComponent integration to example app.
COAND-702
> Add instant payment component example integration

- card/src/main/java/com/adyen/checkout/card/AddressDelegate.kt
- card/src/main/java/com/adyen/checkout/card/AddressOutputData.kt
- card/src/main/java/com/adyen/checkout/card/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/CardOutputData.kt
- card/src/main/java/com/adyen/checkout/card/CardView.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/ui/AddressFormInput.kt
- card/src/main/java/com/adyen/checkout/card/util/AddressValidationUtils.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/StoredCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/ui/Validation.kt
This change was made to use AddressFormInput in other modules.
COAND-368
> The address logics were moved from the card delegate to the address delegate

- giftcard/src/main/java/com/adyen/checkout/giftcard/DefaultGiftCardDelegate.kt
> Show loading until public key has been fetched for Gift Card Component

- ui-core/src/main/java/com/adyen/checkout/components/ui/view/RoundCornerImageView.kt
- ui-core/src/main/res/values/attrs.xml
If merchants define the same attr names in their project they get a compilation error, because it's not allowed to have duplicates.
COAND-677
> Prefix custom attr names

- bcmc/src/main/res/layout/bcmc_view.xml
- card/src/main/res/layout/brand_logo.xml
- card/src/main/res/layout/card_view.xml
- drop-in/src/main/res/layout/payment_methods_list_item.xml
- drop-in/src/main/res/layout/removable_payment_methods_list_item.xml
- ui-core/src/main/res/layout/recycler_list_with_image.xml
We prefixed our custom xml attributes for the `RoundCornerImageView` but didn't apply them to our layout files.
COAND-677
> Use new prefixed custom attribute names

- card/src/main/java/com/adyen/checkout/card/AddressConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/AddressFieldPolicyParams.kt
- card/src/main/java/com/adyen/checkout/card/AddressFormUIState.kt
- card/src/main/java/com/adyen/checkout/card/AddressParams.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParams.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/util/AddressFormUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/AddressValidationUtils.kt
- card/src/main/java/com/adyen/checkout/card/util/CardAddressValidationUtils.kt
- card/src/test/java/com/adyen/checkout/card/AddressFormUtilsTest.kt
- card/src/test/java/com/adyen/checkout/card/CardComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/Required.kt
- card/src/test/java/com/adyen/checkout/card/util/CardAddressValidationUtilsTest.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
it was added address params to use address input view in other modules. it was changed from the address configuration to address params in cardDelegate
COAND-368
> Add Address Params

- await/src/main/java/com/adyen/checkout/await/AwaitComponent.kt
- checkout-core/src/main/java/com/adyen/checkout/core/encryption/Sha256.kt
- checkout-core/src/main/java/com/adyen/checkout/core/log/Logger.kt
- components-core/src/main/java/com/adyen/checkout/components/model/payments/request/PaymentMethodDetails.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/BacsDirectDebitDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/component/GooglePayComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/paymentmethods/PaymentMethodAdapter.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/stored/PreselectedStoredPaymentMethodFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/PaymentMethodsListViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleFullAsyncDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/blik/BlikViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/IssuerListSpinnerView.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/DefaultQRCodeDelegate.kt
- ui-core/src/main/java/com/adyen/checkout/components/image/LogoSize.kt
Remove unnecessary Suppress annotations
COAND-624
> Remove unnecessary Suppress annotations

- components-core/src/main/java/com/adyen/checkout/components/model/payments/response/OrderResponse.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/SessionComponentCallback.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/SessionHandler.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/interactor/SessionCallResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/interactor/SessionInteractor.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/model/SessionPaymentResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/model/payments/SessionDetailsResponse.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/model/payments/SessionPaymentsResponse.kt
Expose all relevant session data in the on finished callback. Handle refused partial payments and non fully paid orders.
COAND-680
> Forward session result 

- card/src/main/java/com/adyen/checkout/card/CardComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/DefaultCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/DefaultCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/model/payments/request/OrderRequest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceContract.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInServiceContract.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/CheckoutSession.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/SessionComponentCallback.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/provider/CheckoutSessionInitializer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/provider/CheckoutSessionProvider.kt
Allow passing order on session creation and card component creation.
COAND-699
> Allow passing order on session creation and component creation

- paybybank/build.gradle
- paybybank/src/main/java/com/adyen/checkout/paybybank/DefaultPayByBankDelegate.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankInputData.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankOutputData.kt
- paybybank/src/test/java/com/adyen/checkout/paybybank/DefaultPayByBankDelegateTest.kt
Add tasks necessary to perform lint checks in `paybybank` module.
COAND-715
> Fix lint checks not working in paybybank module

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/ui/CardNumberInput.kt
- card/src/main/java/com/adyen/checkout/card/util/CardNumberUtils.kt
- card/src/test/java/com/adyen/checkout/card/CardNumberUtilsTest.kt
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayComponent.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashComponent.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSComponent.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.kt
- ideal/src/main/java/com/adyen/checkout/ideal/IdealComponent.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayComponent.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayComponent.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZComponent.kt
- online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/OnlineBankingPLComponent.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKComponent.kt
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingComponent.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankComponent.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaComponent.kt
Remove unnecessary usages of Array and replace them with List
COAND-717
> Remove unnecessary usages of Array

- example-app/src/main/AndroidManifest.xml
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/res/values/strings.xml
Added an example activity for taking over the sessions flow with the card component.
COAND-699
> Example for session take over + components

- sessions-core/src/main/java/com/adyen/checkout/sessions/interactor/SessionInteractor.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/interactor/SessionInteractorTest.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/models/TestPaymentMethod.kt
Add tests from SessionInteractor
COAND-699
> Add tests from SessionInteractor

- build.gradle
- components-core/src/main/java/com/adyen/checkout/components/api/LogoApi.kt
- config/gradle/checksums.gradle
- Upgrade 3DS2 SDK to v2.2.11
COAND-722
> Upgrade 3DS2 SDK to v2.2.11

- checkout-core/src/main/java/com/adyen/checkout/core/exception/MethodNotImplementedException.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInCallback.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/BaseDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/BaseDropInServiceContract.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceContract.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInServiceContract.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/interactor/SessionInteractor.kt
Update kdocs for drop-in
COAND-724
> Update kdocs for drop-in

- drop-in/src/main/java/com/adyen/checkout/dropin/DropIn.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInResultContractParams.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInCallback.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInResultContract.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInResultContractParams.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/service/SessionDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/PaymentsRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/model/SessionPaymentResult.kt
We were missing the full session result in drop-in.
COAND-680
> Return session result in drop-in

- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/provider/BacsDirectDebitComponentProvider.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/BacsDirectDebitDelegate.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/BacsDirectDebitValidationUtils.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/BacsDirectDebitViewProvider.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/DefaultBacsDirectDebitDelegate.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/model/BacsDirectDebitInputData.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/model/BacsDirectDebitOutputData.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/view/BacsDirectDebitConfirmationView.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/view/BacsDirectDebitInputView.kt
- bacs/src/test/java/com/adyen/checkout/bacs/BacsDirectDebitComponentTest.kt
- bacs/src/test/java/com/adyen/checkout/bacs/internal/DefaultBacsDirectDebitDelegateTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
Restructure packaging for bacs. The new structure is like in the picture below. Wasn't sure how to sub package the internal package, so let me know if you have ideas about it.
COAND-497
> Restructure packaging for bacs

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/provider/BcmcComponentProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/BcmcDelegate.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/BcmcViewProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/DefaultBcmcDelegate.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParams.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapper.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcInputData.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcOutputData.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/view/BcmcView.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/BcmcComponentTest.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/DefaultBcmcDelegateTest.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapperTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
Restructure packaging for bcmc
COAND-497
> Restructure packaging for bcmc

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaComponent.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/provider/SepaComponentProvider.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/DefaultSepaDelegate.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/SepaDelegate.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/SepaViewProvider.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/model/Iban.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/model/SepaInputData.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/model/SepaOutputData.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/view/IbanInput.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/ui/view/SepaView.kt
- sepa/src/main/res/layout/sepa_view.xml
- sepa/src/test/java/com/adyen/checkout/sepa/SepaComponentTest.kt
- sepa/src/test/java/com/adyen/checkout/sepa/internal/ui/DefaultSepaDelegateTest.kt
> Restructure packaging for sepa

- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/provider/BlikComponentProvider.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/BlikDelegate.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/BlikViewProvider.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/DefaultBlikDelegate.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/StoredBlikDelegate.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/model/BlikInputData.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/model/BlikOutputData.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/ui/view/BlikView.kt
- blik/src/test/java/com/adyen/checkout/blik/BlikComponentTest.kt
- blik/src/test/java/com/adyen/checkout/blik/internal/ui/DefaultBlikDelegateTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
Restructure packaging for blik
COAND-497
> Restructure packaging for blik

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZComponent.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/internal/provider/OnlineBankingCZComponentProvider.kt
> Restructure packaging for online banking CZ

- ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitComponent.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/provider/ACHDirectDebitComponentProvider.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/ACHDirectDebitDelegate.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/ACHDirectDebitViewProvider.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegate.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParams.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapper.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitInputData.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitOutputData.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/model/AddressFieldPolicyParams.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/ui/view/ACHDirectDebitView.kt
- ach/src/main/java/com/adyen/checkout/ach/internal/util/ACHDirectDebitValidationUtils.kt
- ach/src/test/java/com/adyen/checkout/ach/ACHDirectDebitComponentTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegateTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapperTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/util/ACHDirectDebitValidationUtilsTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
Restructure packaging for card
COAND-497
> Restructure packaging for ACH

- convenience-stores-jp/src/main/java/com/adyen/checkout/conveniencestoresjp/ConvenienceStoresJPComponent.kt
- convenience-stores-jp/src/main/java/com/adyen/checkout/conveniencestoresjp/internal/provider/ConvenienceStoresJPComponentProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- econtext/src/main/java/com/adyen/checkout/econtext/EContextComponent.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/provider/EContextComponentProvider.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/DefaultEContextDelegate.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/EContextDelegate.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/EContextViewProvider.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/model/EContextInputData.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/model/EContextOutputData.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/ui/view/EContextView.kt
- econtext/src/test/java/com/adyen/checkout/econtext/EContextComponentTest.kt
- econtext/src/test/java/com/adyen/checkout/econtext/TestEContextComponent.kt
- econtext/src/test/java/com/adyen/checkout/econtext/internal/ui/DefaultEContextDelegateTest.kt
- online-banking-jp/src/main/java/com/adyen/checkout/onlinebankingjp/OnlineBankingJPComponent.kt
- online-banking-jp/src/main/java/com/adyen/checkout/onlinebankingjp/internal/provider/OnlineBankingJPComponentProvider.kt
- payeasy/src/main/java/com/adyen/checkout/payeasy/PayEasyComponent.kt
- payeasy/src/main/java/com/adyen/checkout/payeasy/internal/provider/PayEasyComponentProvider.kt
- seven-eleven/src/main/java/com/adyen/checkout/seveneleven/SevenElevenComponent.kt
- seven-eleven/src/main/java/com/adyen/checkout/seveneleven/internal/provider/SevenElevenComponentProvider.kt
Restructure packaging for econtext and it's children
COAND-497
> Restructure packaging for econtext and it's children

- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/OnlineBankingComponent.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/provider/OnlineBankingComponentProvider.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/DefaultOnlineBankingDelegate.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/OnlineBankingDelegate.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/OnlineBankingView.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/OnlineBankingViewProvider.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/model/OnlineBankingInputData.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/model/OnlineBankingModel.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/ui/model/OnlineBankingOutputData.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/util/IssuersExt.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/util/PdfOpener.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/OnlineBankingComponentTest.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/internal/ui/DefaultOnlineBankingDelegateTest.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/utils/TestOnlineBankingComponent.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/utils/TestOnlineBankingConfiguration.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZComponent.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/internal/provider/OnlineBankingCZComponentProvider.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKComponent.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKComponentProvider.kt
> Restructure packaging for online banking core

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayComponent.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/provider/MBWayComponentProvider.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegate.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayDelegate.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MbWayViewProvider.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/model/MBWayInputData.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/model/MBWayOutputData.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayView.kt
- mbway/src/test/java/com/adyen/checkout/mbway/MBWayComponentTest.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
Restructure packaging for MBWay
COAND-497
> Restructure packaging for MBWay

- action/src/main/java/com/adyen/checkout/action/ActionDelegateProvider.kt
- await/src/main/java/com/adyen/checkout/await/AwaitComponent.kt
- await/src/main/java/com/adyen/checkout/await/internal/provider/AwaitComponentProvider.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitDelegate.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitViewProvider.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/DefaultAwaitDelegate.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/model/AwaitOutputData.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/view/AwaitView.kt
- await/src/test/java/com/adyen/checkout/await/AwaitComponentTest.kt
- await/src/test/java/com/adyen/checkout/await/internal/ui/DefaultAwaitDelegateTest.kt
> Restructure packaging for await component

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/OnlineBankingPLComponent.kt
- online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/internal/provider/OnlineBankingPLComponentProvider.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKComponent.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/internal/provider/OnlineBankingSKComponentProvider.kt
> Restructure packaging for online banking PL & SK

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankComponent.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/provider/PayByBankComponentProvider.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/DefaultPayByBankDelegate.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/PayByBankDelegate.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/PayByBankViewProvider.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/model/PayByBankInputData.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/model/PayByBankOutputData.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/view/PayByBankRecyclerAdapter.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/view/PayByBankView.kt
- paybybank/src/test/java/com/adyen/checkout/paybybank/PayByBankComponentTest.kt
- paybybank/src/test/java/com/adyen/checkout/paybybank/internal/ui/DefaultPayByBankDelegateTest.kt
Restructure packaging for PayByBank
COAND-497
> Restructure packaging for PayByBank

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- instant/src/main/java/com/adyen/checkout/instant/InstantPaymentComponent.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/ui/DefaultInstantPaymentDelegate.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/ui/InstantPaymentDelegate.kt
- instant/src/test/java/com/adyen/checkout/instant/InstantPaymentComponentTest.kt
- instant/src/test/java/com/adyen/checkout/instant/internal/ui/DefaultInstantPaymentDelegateTest.kt
Restructure packaging for instant
COAND-497
> Restructure packaging for instant

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModel.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardViewProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardInputData.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardOutputData.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardNumberInput.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardView.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardBalanceUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinUtils.kt
- giftcard/src/main/res/layout/giftcard_view.xml
- giftcard/src/test/java/com/adyen/checkout/giftcard/GiftCardComponentTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/util/GiftCardBalanceUtilsTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtilsTest.kt
> Restructure packaging for gift card

- action/src/main/java/com/adyen/checkout/action/ActionDelegateProvider.kt
- voucher/src/main/java/com/adyen/checkout/voucher/VoucherComponent.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/provider/VoucherComponentProvider.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/DefaultVoucherDelegate.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/VoucherDelegate.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/VoucherViewProvider.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/model/VoucherOutputData.kt
- voucher/src/main/java/com/adyen/checkout/voucher/internal/ui/view/VoucherView.kt
- voucher/src/test/java/com/adyen/checkout/voucher/VoucherComponentTest.kt
- voucher/src/test/java/com/adyen/checkout/voucher/internal/ui/DefaultVoucherDelegateTest.kt
Restructure packaging for Voucher
COAND-497
> Restructure packaging for Voucher

- action/src/main/java/com/adyen/checkout/action/ActionDelegateProvider.kt
- action/src/test/java/com/adyen/checkout/action/TestActionDelegate.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponent.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/QRCodeCountDownTimer.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/provider/QRCodeComponentProvider.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegate.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/QRCodeDelegate.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/QrCodeViewProvider.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/model/QRCodeOutputData.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/model/QrCodeUIEvent.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/view/FullQRCodeView.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/view/SimpleQRCodeView.kt
- qr-code/src/test/java/com/adyen/checkout/qrcode/QRCodeComponentTest.kt
- qr-code/src/test/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegateTest.kt
> Restructure packaging for qr code

- action/src/main/java/com/adyen/checkout/action/ActionDelegateProvider.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/provider/RedirectComponentProvider.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/RedirectDelegate.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/RedirectViewProvider.kt
- redirect/src/test/java/com/adyen/checkout/redirect/RedirectComponentTest.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegateTest.kt
> Restructure packaging for redirect

- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/BillingAddressParameters.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayConfiguration.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/MerchantInfo.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/ShippingAddressParameters.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/CardParameters.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/GooglePayPaymentMethodModel.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/IsReadyToPayRequestModel.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/PaymentDataRequestModel.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/PaymentMethodTokenizationSpecification.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/TokenizationParameters.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/data/model/TransactionInfoModel.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/provider/GooglePayComponentProvider.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParams.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapper.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/AllowedAuthMethods.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/AllowedCardNetworks.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/GooglePayUtils.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/GooglePayComponentTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
> Restructure packaging for google pay

- action/src/main/java/com/adyen/checkout/action/ActionDelegateProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ComponentParsingProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/DropInActivity.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponent.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/WeChatPayProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/provider/WeChatPayActionComponentProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegate.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/WeChatDelegate.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/WeChatViewProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/util/WeChatPayRequestGenerator.kt
- wechatpay/src/test/java/com/adyen/checkout/wechatpay/WeChatPayActionComponentTest.kt
- wechatpay/src/test/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegateTest.kt
> Restructure packaging for wechat

- cse/src/main/java/com/adyen/checkout/cse/EncryptionException.kt
Add missing kdocs for CSE
COAND-724
> Add missing kdocs for CSE

- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/CardConfiguration.kt
- card/src/main/java/com/adyen/checkout/card/internal/provider/CardComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardComponentParams.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/InstallmentOptionParams.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/InstallmentParams.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/InstallmentsParamsMapper.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/InstallmentUtils.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/model/InstallmentParamsMapperTest.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/model/JsonUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/InstallmentPlan.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/SessionRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/storage/KeyValueStorage.kt
- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/res/values/arrays.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/xml/preferences.xml
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupConfiguration.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupInstallmentOptions.kt
- Add Installment options params for cards to be used internally instead of card configuration
-  Add installment options mapper
COAND-613
> Display installments for /sessions integrations

- components-core/src/main/java/com/adyen/checkout/components/core/internal/util/PaymentMethodTypes.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegate.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/model/QRCodePaymentMethodConfig.kt
- qr-code/src/main/res/template/values/strings.xml.tt
- qr-code/src/main/res/values-ar/strings.xml
- qr-code/src/main/res/values-cs-rCZ/strings.xml
- qr-code/src/main/res/values-da-rDK/strings.xml
- qr-code/src/main/res/values-de-rDE/strings.xml
- qr-code/src/main/res/values-el-rGR/strings.xml
- qr-code/src/main/res/values-es-rES/strings.xml
- qr-code/src/main/res/values-fi-rFI/strings.xml
- qr-code/src/main/res/values-fr-rFR/strings.xml
- qr-code/src/main/res/values-hr-rHR/strings.xml
- qr-code/src/main/res/values-hu-rHU/strings.xml
- qr-code/src/main/res/values-it-rIT/strings.xml
- qr-code/src/main/res/values-ja-rJP/strings.xml
- qr-code/src/main/res/values-ko-rKR/strings.xml
- qr-code/src/main/res/values-nb-rNO/strings.xml
- qr-code/src/main/res/values-nl-rNL/strings.xml
- qr-code/src/main/res/values-pl-rPL/strings.xml
- qr-code/src/main/res/values-pt-rBR/strings.xml
- qr-code/src/main/res/values-pt-rPT/strings.xml
- qr-code/src/main/res/values-ro-rRO/strings.xml
- qr-code/src/main/res/values-ru-rRU/strings.xml
- qr-code/src/main/res/values-sk-rSK/strings.xml
- qr-code/src/main/res/values-sl-rSI/strings.xml
- qr-code/src/main/res/values-sv-rSE/strings.xml
- qr-code/src/main/res/values-zh-rCN/strings.xml
- qr-code/src/main/res/values-zh-rTW/strings.xml
- qr-code/src/main/res/values/strings.xml
PromptPay has been added to the supported payment methods
COAND-620
> Add PromptPay payment method

- ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ButtonDelegate.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/ViewableComponent.kt
Add missing kdocs for ui-core
COAND-724
> Add missing kdocs for ui-core

- test-core/src/main/java/com/adyen/checkout/test/TestDispatcherExtension.kt
- test-core/src/main/java/com/adyen/checkout/test/extensions/TestFlow.kt
- test-core/src/main/java/com/adyen/checkout/test/extensions/ViewModelExtensions.kt
Add missing kdocs for test-core and add visibility scoping
COAND-724
> Add missing kdocs for test-core

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Authentication3DS2Exception.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Cancelled3DS2Exception.kt
> Update kdocs for 3ds2

- ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitComponent.kt
- ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitComponentState.kt
> Add missing kdocs for ACH

- await/src/main/java/com/adyen/checkout/await/AwaitComponent.kt
- qr-code/src/main/java/com/adyen/checkout/qrcode/QRCodeComponent.kt
- redirect/src/main/java/com/adyen/checkout/redirect/RedirectComponent.kt
- voucher/src/main/java/com/adyen/checkout/voucher/VoucherComponent.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayActionComponent.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayUtils.kt
> Add missing kdocs for remaining action modules

- example-app/src/main/AndroidManifest.xml
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardComponentData.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/giftcard/GiftCardViewState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/res/layout/activity_gift_card.xml
- example-app/src/main/res/values/strings.xml
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardAction.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponentCallback.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponentState.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardException.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/GiftCardComponentEventHandler.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardDelegate.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/GiftCardComponentTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
Support resolving creating order and checking balance results in GiftCardComponent. Add next action to take in GiftCardComponentState.
COAND-719
> Improve partial payment flow in GiftCardComponent

- googlepay/src/main/java/com/adyen/checkout/googlepay/BillingAddressParameters.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponent.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayComponentState.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/MerchantInfo.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/ShippingAddressParameters.kt
> Add missing kdocs for googlepay

- ach/src/main/java/com/adyen/checkout/ach/ACHDirectDebitComponent.kt
- bacs/src/main/java/com/adyen/checkout/bacs/BacsDirectDebitComponent.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/BcmcComponent.kt
- blik/src/main/java/com/adyen/checkout/blik/BlikComponent.kt
- convenience-stores-jp/src/main/java/com/adyen/checkout/conveniencestoresjp/ConvenienceStoresJPComponent.kt
- dotpay/src/main/java/com/adyen/checkout/dotpay/DotpayComponent.kt
- entercash/src/main/java/com/adyen/checkout/entercash/EntercashComponent.kt
- eps/src/main/java/com/adyen/checkout/eps/EPSComponent.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- ideal/src/main/java/com/adyen/checkout/ideal/IdealComponent.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayComponent.kt
- molpay/src/main/java/com/adyen/checkout/molpay/MolpayComponent.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZComponent.kt
- online-banking-jp/src/main/java/com/adyen/checkout/onlinebankingjp/OnlineBankingJPComponent.kt
- online-banking-pl/src/main/java/com/adyen/checkout/onlinebankingpl/OnlineBankingPLComponent.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKComponent.kt
- openbanking/src/main/java/com/adyen/checkout/openbanking/OpenBankingComponent.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/PayByBankComponent.kt
- payeasy/src/main/java/com/adyen/checkout/payeasy/PayEasyComponent.kt
- sepa/src/main/java/com/adyen/checkout/sepa/SepaComponent.kt
- seven-eleven/src/main/java/com/adyen/checkout/seveneleven/SevenElevenComponent.kt
- upi/src/main/java/com/adyen/checkout/upi/UPIComponent.kt
- upi/src/main/java/com/adyen/checkout/upi/UPIComponentState.kt
> Reference PaymentMethodTypes in component docs

- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/OnlineBankingComponent.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/OnlineBankingConfiguration.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/provider/OnlineBankingComponentProvider.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/internal/OnlineBankingComponentTest.kt
- online-banking-core/src/test/java/com/adyen/checkout/onlinebankingcore/utils/TestOnlineBankingComponent.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZComponent.kt
- online-banking-cz/src/main/java/com/adyen/checkout/onlinebankingcz/OnlineBankingCZConfiguration.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKComponent.kt
- online-banking-sk/src/main/java/com/adyen/checkout/onlinebankingsk/OnlineBankingSKConfiguration.kt
These classes shouldn't be public facing, since they are abstract.
COAND-724
> Move public facing classes in online-banking-core to internal package

- card/src/main/java/com/adyen/checkout/card/CardBrand.kt
- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/CardComponentState.kt
- card/src/main/java/com/adyen/checkout/card/CardType.kt
- card/src/main/java/com/adyen/checkout/card/KCPAuthVisibility.kt
- card/src/main/java/com/adyen/checkout/card/SocialSecurityNumberVisibility.kt
> Add missing kdocs for card

- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodsApiResponse.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/provider/PaymentComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/provider/StoredPaymentComponentProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInSavedStateHandleContainer.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardBalanceUtils.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/CheckoutSession.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/CheckoutSessionProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/CheckoutSessionResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionComponentCallback.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionPaymentResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionSetupResponse.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/CheckoutSessionInitializer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/SessionInteractor.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/provider/SessionPaymentComponentProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/provider/SessionStoredPaymentComponentProvider.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/internal/SessionInteractorTest.kt
> Add missing kdocs for sessions-core

- config/gradle/checksums.gradle
- dependencies.gradle
Quick cleanup to remove some code for unused dependencies.
> Remove unused dependencies

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GooglePayComponentDialogFragment.kt
> Remove unused navigatedFromPreselected flag in GooglePayComponentDialogFragment

- bacs/src/main/java/com/adyen/checkout/bacs/internal/ui/DefaultBacsDirectDebitDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/CardAddressValidationUtils.kt
- checkout-core/src/main/java/com/adyen/checkout/core/internal/data/api/HttpClientFactory.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/BacsDirectDebitDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/GiftCardComponentDialogFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/PaymentsRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleSessionsDropInService.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/ui/DefaultPayByBankDelegate.kt
Remove unnecessary TODOs
COAND-505
> Remove unnecessary TODOs

- example-app/proguard-rules.pro
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/AdditionalData.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/BalanceRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/CancelOrderRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/CreateOrderRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/InstallmentPlan.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/Item.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/PaymentMethodsRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/PaymentsRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/RecurringProcessingModel.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/RemoveStoredPaymentMethodRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/SessionRequest.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/StorePaymentMethodMode.kt
- example-app/src/main/java/com/adyen/checkout/example/data/api/model/ThreeDS2RequestDataRequest.kt
- ui-core/consumer-rules.pro
The example app now works with obfuscation and loading logo's as well. Everything else already seems to work.
> Make obfuscation work correctly

- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
Updating library version and release notes for 5.0.0-alpha01.
COAND-752
> Preparing 5.0.0 alpha01 release

- .github/workflows/check_pr.yml
- .github/workflows/check_release.yml
Fix check PR workflow to exclude `main` instead of `master`.
> Fix check PR workflows

- dependencies.gradle
- scripts/version_name.sh
> Quick fix for version_name.sh

- dependencies.gradle
- scripts/version_name.sh
Reverts Adyen/adyen-android#1187
> Revert "Quick fix for version_name.sh"

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/provider/Adyen3DS2ComponentProvider.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParams.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapper.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapperTest.kt
Don't set a default value for `threeDSRequestorAppURL`
COAND-744
> Don't set a default value for threeDSRequestorAppURL

- googlepay/src/main/java/com/adyen/checkout/googlepay/ShippingAddressParameters.kt
> Correctly serialize ShippingAddressParameters

- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/ui/DefaultBcmcDelegate.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/DefaultBcmcDelegateTest.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
> Send brand in paymentComponentData for single branded cards

- README.md
- RELEASE_NOTES.md
- build.gradle
- example-app/build.gradle
Preparing release notes and updating SDK version to 4.12.0.
> Preparing release 4.12.0

- drop-in/src/main/java/com/adyen/checkout/dropin/DropInServiceResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionPaymentResult.kt
> Add kdocs for SessionPaymentResult

- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
Updating library version and release notes for 5.0.0-alpha02.
> Preparing release 5.0.0 alpha02

- .github/workflows/publish_docs.yml
Use java 17 with publish docs workflow.
> Use java 17 with publish docs workflow

- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsService.kt
Change `/v2/analytics` to `/v3/analytics`.
COAND-481
> Telemetry: Change analytics endpoint from v2 to v3

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/BaseDropInServiceContract.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInService.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/service/BaseDropInServiceInterfaces.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/CardComponentDialogFragment.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInBottomSheetDialogFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/extensions/LogExtensions.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
Add on bin value callback to CardComponent. This callback is called when the shopper enters their card number and the bin value changes.
COAND-732
> On bin changed callback

- drop-in/src/main/java/com/adyen/checkout/dropin/DropInServiceResult.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
Add event to navigate to the payment methods list
COAND-736
> Add event to navigate to the payment methods list

- build.gradle
- card/src/main/java/com/adyen/checkout/card/AddressConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/ui/viewmodel/DropInViewModelFactory.kt
- gradle/wrapper/gradle-wrapper.properties
- ui-core/src/main/java/com/adyen/checkout/components/ui/view/AdyenSwipeToRevealLayout.kt
Upgrade to target and compile sdk 33 (v4). Also upgraded the Gradle wrapper to fix some build warnings
COAND-791
> Upgrade to target sdk 33 (v4)

- .github/workflows/check_pr.yml
- .github/workflows/update_verification_metadata.yml
Remove updating dependency verification from workflow
> Remove updating dependency verification from workflow

- .github/workflows/assemble.yml
- .github/workflows/check_pr.yml
- .github/workflows/code_analysis.yml
- .github/workflows/run_tests.yml
- .github/workflows/update_verification_metadata.yml
> Improve workflow caching

- card/src/main/java/com/adyen/checkout/card/CardComponent.kt
> Fix dual branded flow check (v4)

- README.md
- RELEASE_NOTES.md
- build.gradle
- example-app/build.gradle
Adding release notes and increasing version to 4.13.0.
> Preparing release 4.13.0

- ach/src/main/java/com/adyen/checkout/ach/internal/provider/ACHDirectDebitComponentProvider.kt
- bacs/src/main/java/com/adyen/checkout/bacs/internal/provider/BacsDirectDebitComponentProvider.kt
- bcmc/src/main/java/com/adyen/checkout/bcmc/internal/provider/BcmcComponentProvider.kt
- blik/src/main/java/com/adyen/checkout/blik/internal/provider/BlikComponentProvider.kt
- boleto/src/main/java/com/adyen/checkout/boleto/internal/provider/BoletoComponentProvider.kt
- card/src/main/java/com/adyen/checkout/card/internal/provider/CardComponentProvider.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/provider/CashAppPayComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapper.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsRepositoryData.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/DefaultAnalyticsRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsSetupRequest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/DefaultAnalyticsRepositoryTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModelFactory.kt
- econtext/src/main/java/com/adyen/checkout/econtext/internal/provider/EContextComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/provider/GooglePayComponentProvider.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/provider/IssuerListComponentProvider.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/provider/MBWayComponentProvider.kt
- online-banking-core/src/main/java/com/adyen/checkout/onlinebankingcore/internal/provider/OnlineBankingComponentProvider.kt
- paybybank/src/main/java/com/adyen/checkout/paybybank/internal/provider/PayByBankComponentProvider.kt
- sepa/src/main/java/com/adyen/checkout/sepa/internal/provider/SepaComponentProvider.kt
- upi/src/main/java/com/adyen/checkout/upi/internal/provider/UPIComponentProvider.kt
Include the sessionId when making the initial telemetry data call.
COAND-793
> Add session ID to telemetry data

- README.md
- RELEASE_NOTES.md
- build.gradle
- example-app/build.gradle
Adding release notes and increasing version to 4.13.1
> Preparing release 4.13.1

- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
> Fix output data not being created on input changes

- README.md
- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
- example-app/build.gradle
> Preparing release 5.0.0 beta01

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
Disable phone number collection of 3DS2 SDK.
AUTHN-967
> Disable phone number collection of 3DS2 SDK (v4)

- cashapppay/src/main/java/com/adyen/checkout/cashapppay/CashAppPayOutputData.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/DefaultCashAppPayDelegate.kt
Send customer id in Cash App one time flow to make sure the payment will be authorised.
COAND-799
> Fix Cash App payment flow (v4)

- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegate.kt
- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayOutputData.kt
- cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/DefaultCashAppPayDelegateTest.kt
Send customer id in Cash App one time flow to make sure the payment will be authorised.
COAND-799
> Fix Cash App payment flow

- example-app/proguard-rules.pro
Add some rules to make sure example app can run with minifying enabled.
> Make example app work with obfuscation

- action-core/src/main/java/com/adyen/checkout/action/core/internal/ActionHandlingPaymentMethodConfigurationBuilder.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/BaseConfigurationBuilder.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/provider/PaymentComponentProvider.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/provider/StoredPaymentComponentProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/provider/SessionPaymentComponentProvider.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/provider/SessionStoredPaymentComponentProvider.kt
Remove @RestrictTo from classes that are indirectly exposed
COAND-803
> Fix restricted api warnings

- README.md
- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
- example-app/build.gradle
Preparing release 5.0.0: updating version number, release notes and readme file.
> Preparing release 5.0.0

- RELEASE_NOTES.md
- action-core/src/main/java/com/adyen/checkout/action/core/internal/ActionHandlingComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/ComponentAvailableCallback.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ActionComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ActivityResultHandlingComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ButtonComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ButtonConfigurationBuilder.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/IntentHandlingComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/PaymentComponent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/PaymentMethodAvailabilityCheck.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/provider/ActionComponentProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentParsingProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/WeChatPayProvider.kt
Remove `@RestrictTo` annotations from interfaces containing public functions.
COAND-803
> Fix wrong restricted API warnings

- README.md
- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
- example-app/build.gradle
> Preparing release 5.0.1

- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapper.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsPlatform.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
Make it possible to override version and platform for analytics
COAND-815
> Make it possible to override version and platform for analytics

- RELEASE_NOTES.md
- build.gradle
- example-app/build.gradle
> Preparing release 4.13.4

- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardConfiguration.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/GiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParams.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapper.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardOutputData.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardView.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
Add configuration to hide the PIN input field for gift cards.
COAND-741
> Add pinRequired configuration for gift card component

- example-app/src/main/java/com/adyen/checkout/example/ui/bacs/BacsFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayComponentData.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItem.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/ComponentItemProvider.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainNavigation.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/main/MainViewModel.kt
- example-app/src/main/res/layout/fragment_google_pay.xml
- example-app/src/main/res/values-night/styles.xml
- example-app/src/main/res/values/strings.xml
- example-app/src/main/res/values/styles.xml
Add Google Pay to the example app, including the availability check and the Google Pay dynamic button.
COAND-788
> Add Google Pay + advanced flow to example app

- cse/src/main/java/com/adyen/checkout/cse/internal/JSONWebEncryptor.kt
Replace A256CBC-HS512 with A256GCM
COAND-655
> Even better encryption

- config/gradle/sonarcloud.gradle
Set correct jacoco report path for sonar
COAND-829
> Set correct jacoco report path for sonar

- .github/workflows/sonar_cloud.yml
- config/gradle/jacoco.gradle
- config/gradle/sonarcloud.gradle
- dependencies.gradle
Exclude project specific files from test coverage since they can't be unit tested.
> Exclude files from test coverage

- RELEASE_NOTES.md
- drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInService.kt
For drop-in with sessions we will no longer display a detailed error message. Instead we will show a generic, user friendly message.
COAND-839
> Fix error dialog messages

- README.md
- docs/UI_CUSTOMIZATION.md
Add a UI customization guide to the readme.
See the [README](https://github.com/Adyen/adyen-android/blob/ui-customization-guide/README.md) and the [guide](https://github.com/Adyen/adyen-android/blob/ui-customization-guide/docs/UI_CUSTOMIZATION.md) for the parsed results.
COAND-837
> Add a UI customization guide to the readme

- README.md
- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
- example-app/build.gradle
Preparing release 5.2.0: Updating version number and release notes.
> Preparing release 5.2.0

- RELEASE_NOTES.md
- checkout-core/src/main/java/com/adyen/checkout/core/PermissionHandlerCallback.kt
- components-core/src/main/java/com/adyen/checkout/components/core/ActionComponentCallback.kt
- components-core/src/main/java/com/adyen/checkout/components/core/ComponentCallback.kt
- components-core/src/test/java/com/adyen/checkout/components/core/ActionComponentCallbackTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/ComponentCallbackTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/TestActionComponentCallback.kt
- components-core/src/test/java/com/adyen/checkout/components/core/TestComponentCallback.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantEvent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantFragment.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/instant/InstantViewModel.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionComponentCallback.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/SessionComponentCallbackTest.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/TestComponentState.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/TestPaymentMethod.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/TestSessionComponentCallback.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/internal/SessionComponentEventHandlerTest.kt
- sessions-core/src/test/java/com/adyen/checkout/sessions/core/internal/SessionInteractorTest.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ImageSaver.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/PermissionHandlerExtension.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/TestPermissionHandler.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/util/PermissionHandlerExtensionTest.kt
In this PR:
- Added permission request support to `InstantFragment`.
- Add `PERMISSION_REQUEST_NOT_HANDLED` handler result to cancel the running coroutine and show an error message.
Original PR: https://github.com/Adyen/adyen-android/pull/1434
COAND-372
> Voucher refactor and Multibanco support - Improvements

- drop-in/src/main/java/com/adyen/checkout/dropin/SessionDropInResult.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/SessionPaymentResult.kt
Clarify the purpose of each parameter in `SessionPaymentResult`.
> Improve code docs for SessionPaymentResult

- RELEASE_NOTES.md
Add integration steps in more detail for address lookup.
COAND-730
> Add detailed release notes for Address Lookup

- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
- instant/src/test/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProviderTest.kt
Add onlineBanking_SK to supported payment methods and make sure InstantPaymentComponent doesn't take over any other payment methods.
COAND-854
> Add onlineBanking_SK to supported payment methods

- components-core/build.gradle
- components-core/src/main/java/com/adyen/checkout/components/core/PaymentComponentData.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Action.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/ActionTypes.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/AwaitAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/QrCodeAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/RedirectAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/SdkAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2Action.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2ChallengeAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/Threeds2FingerprintAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/action/VoucherAction.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ActionTypes.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/PaymentDataRepository.kt
- components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/GenericPaymentMethod.kt
- components-core/src/test/java/com/adyen/checkout/components/core/PaymentComponentDataTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/action/RedirectActionTest.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/data/api/NativeRedirectService.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/data/model/NativeRedirectRequest.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/data/model/NativeRedirectResponse.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/provider/RedirectComponentProvider.kt
- redirect/src/main/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegate.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/data/api/NativeRedirectServiceTest.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/data/model/NativeRedirectRequestTest.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/data/model/NativeRedirectResponseTest.kt
- redirect/src/test/java/com/adyen/checkout/redirect/internal/ui/DefaultRedirectDelegateTest.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/test/TestRedirectHandler.kt
Add support for the native redirect action.
COAND-805
> Add support for native redirects

- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/model/Adyen3DS2ComponentParamsMapperTest.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/model/ACHDirectDebitComponentParamsMapperTest.kt
- bcmc/src/test/java/com/adyen/checkout/bcmc/internal/ui/model/BcmcComponentParamsMapperTest.kt
- boleto/src/test/java/com/adyen/checkout/boleto/internal/ui/model/BoletoComponentParamsMapperTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/model/CardComponentParamsMapperTest.kt
- cashapppay/src/test/java/com/adyen/checkout/cashapppay/internal/ui/model/CashAppPayComponentParamsMapperTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/CommonComponentParamsMapper.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/SessionParams.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/ButtonComponentParamsMapperTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/GenericComponentParamsMapperTest.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInSavedStateHandleContainer.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/model/DropInParamsMapper.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/model/DropInParamsMapperTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapperTest.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayComponentParamsMapperTest.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/internal/ui/model/IssuerListComponentParamsMapperTest.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/CheckoutSession.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/SessionSavedStateHandleContainer.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/data/model/SessionDetails.kt
- sessions-core/src/main/java/com/adyen/checkout/sessions/core/internal/ui/model/SessionParamsFactory.kt
Use environment and client key from sessions just in case it conflicts with the values provided in the configurations.
COAND-847
> Use environment and client key from sessions

- RELEASE_NOTES.md
- docs/ADDRESS_LOOKUP.md
Update release notes.
COAND-863
> Update release notes

- README.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
- example-app/build.gradle
Preparing release `5.3.0`.
COAND-863
> Preparing release 5.3.0

- docs/ADDRESS_LOOKUP.md
> Update address lookup docs

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsService.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsPlatformParamsTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManagerTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/DefaultAnalyticsRepositoryTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/AnalyticsTrackRequestProviderTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/analytics/data/remote/DefaultAnalyticsSetupProviderTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsServiceTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsSetupRequestTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsSetupResponseTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackInfoTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackLogTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/model/AnalyticsTrackRequestTest.kt
A continuation of #1501, adding the unit tests that were missing there.
COAND-844
> Analytics testing

- components-core/build.gradle
- components-core/src/testFixtures/java/com/adyen/checkout/components/core/internal/analytics/TestAnalyticsManager.java
- mbway/build.gradle
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegate.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
Test implementation for AnalyticsManager + analytics for MBWay.
COAND-845
> Test implementation for AnalyticsManager + analytics for MBWay

- card/build.gradle
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegate.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
Track analytics for Card component
COAND-845
> Analytics - Add events - Card

- RELEASE_NOTES.md
- card/src/main/res/values/styles.xml
Add missing styles for card
COAND-880
> Add missing styles for card

- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- issuer-list/build.gradle
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/ui/DefaultIssuerListDelegate.kt
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/ui/view/IssuerListSpinnerAdapter.kt
- issuer-list/src/test/java/com/adyen/checkout/issuerlist/internal/ui/DefaultIssuerListDelegateTest.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/DefaultMBWayDelegateTest.kt
Track analytics for Issuers list
COAND-845
> Analytics - Add events - Issuers list

- qr-code/src/main/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegate.kt
- qr-code/src/test/java/com/adyen/checkout/qrcode/internal/ui/DefaultQRCodeDelegateTest.kt
Track download event when QR code is downloaded
COAND-845
> Analytics - Add events - QR download 

- README.md
- RELEASE_NOTES.md
- components-core/src/test/java/com/adyen/checkout/components/core/internal/data/api/AnalyticsMapperTest.kt
- dependencies.gradle
- example-app/build.gradle
> Preparing release 5.3.1

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/analytics/ThreeDS2Events.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsEvent.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
Add analytics events for 3DS2 flow
COAND-845
> Analytics - Add events - 3DS2

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/Adyen3DS2Component.kt
- RELEASE_NOTES.md
- build.gradle
- config/gradle/checksums.gradle
- example-app/src/main/AndroidManifest.xml
Updated the 3DS2 SDK to 2.2.17 on v4
COAND-900
> Update 3DS2 SDK [v4]

- components-core/src/main/java/com/adyen/checkout/components/core/internal/BaseConfigurationBuilder.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/util/ValidationUtils.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/util/ValidationUtilsTest.kt
- Validate client key and environment together not separately.
- Fix inaccurate regex for client key.
- Add more tests.
COAND-905
> Improve client key validation

- .github/workflows/assemble.yml
- .github/workflows/check_release.yml
- .github/workflows/code_analysis.yml
- .github/workflows/publish_docs.yml
- .github/workflows/publish_release.yml
- .github/workflows/run_tests.yml
- .github/workflows/run_ui_tests.yml
- .github/workflows/sonar_cloud.yml
- .github/workflows/update_verification_metadata.yml
- build.gradle
- gradle.properties
Speed up sonar and other actions by:
- Enabling Gradle configuration cache
- Setting `resConfigs` on CI builds
- Enabling Gradle daemon on CI
- Disabling recompilation by `sonar` command
Future ideas: migrate to KSP and use non-transitive R classes
> Speed up sonar

- RELEASE_NOTES.md
- build.gradle
- config/gradle/checksums.gradle
Update 3DS2 SDK to 2.2.18 on v4
COAND-910
> Update 3DS2 SDK to 2.2.18 [v4]

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandler.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandlerTest.kt
- await/src/test/java/com/adyen/checkout/await/internal/ui/DefaultAwaitDelegateTest.kt
Restore 3DS2 state after process death
Note: labeled this PR as chore as there are already release notes about this from another PR
COAND-857
> Restore 3DS2 state after process death

- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/provider/WeChatPayActionComponentProvider.kt
- wechatpay/src/main/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegate.kt
- wechatpay/src/test/java/com/adyen/checkout/wechatpay/internal/ui/DefaultWeChatDelegateTest.kt
Correctly restore state of WeChatPay.
COAND-857
> Correctly restore state of WeChatPay

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
Remove storedEventCount counter, since it was not reliable due to concurrent operations
COAND-845
> Analytics - Remove stored event counter

- README.md
- RELEASE_NOTES.md
- dependencies.gradle
- example-app/build.gradle
> Prepare release 5.4.0

- example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupCompletionState.kt
- example-app/src/main/java/com/adyen/checkout/example/repositories/AddressLookupRepository.kt
- example-app/src/main/java/com/adyen/checkout/example/service/ExampleAdvancedDropInService.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/CardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverActivity.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardTakenOverViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardUiState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/SessionsCardViewModel.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/card/compose/SessionsCardScreen.kt
Support address lookup in card example with sessions. 
Extract address lookup related code to AddressLookupRepository.
COAND-871
> Improve address lookup examples

- scripts/process_api_changes.sh
Dump diff output in one code block. Formatting it manually is very difficult as there are a lot of cases to take into account. This is the easiest and most clear way.
COAND-926
> Simplify api change formatting

- RELEASE_NOTES.md
- ideal/api/ideal.api
- ideal/build.gradle
- ideal/src/main/java/com/adyen/checkout/ideal/IdealComponent.kt
- ideal/src/main/java/com/adyen/checkout/ideal/IdealConfiguration.kt
- ideal/src/main/java/com/adyen/checkout/ideal/internal/provider/IdealComponentProvider.kt
- ideal/src/main/java/com/adyen/checkout/ideal/internal/ui/DefaultIdealDelegate.kt
- ideal/src/main/java/com/adyen/checkout/ideal/internal/ui/IdealDelegate.kt
- ideal/src/test/java/com/adyen/checkout/ideal/IdealComponentTest.kt
- ideal/src/test/java/com/adyen/checkout/ideal/internal/ui/DefaultIdealDelegateTest.kt
- issuer-list/api/issuer-list.api
- issuer-list/src/main/java/com/adyen/checkout/issuerlist/internal/IssuerListConfiguration.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/DefaultRedirectHandler.kt
- Decouple `IdealComponent` etc from IssuerList (as much backwards compatible as possible)
- `IdealComponent` now functions like `InstantPaymentComponent` 
COAND-875
> Implement Ideal 2.0 flow

- renovate.json
- Add KSP to Kotlin group
- Move Kotlin Coroutines to their own group, since they don't depend on Kotlin updates
> Improve Renovate Kotlin grouping

- RELEASE_NOTES.md
- action-core/consumer-rules.pro
Don't warn for compileOnly dependencies (R8).
COAND-940
> Fix minification for compileOnly dependencies

- README.md
- RELEASE_NOTES.md
- dependencies.gradle
- example-app/build.gradle
> Preparing release 5.6.0

- RELEASE_NOTES.md
- build.gradle
- config/gradle/checksums.gradle
- example-app/build.gradle
> Update 3DS2 SDK to 2.2.19 (v4)

- build.gradle
- example-app/build.gradle
> Prepare release 4.13.6

- README.md
Update drop-in preview screenshot in readme.
> Update drop-in preview screenshot

- RELEASE_NOTES.md
- drop-in/src/main/res/template/values/strings.xml.tt
- drop-in/src/main/res/values-ar/strings.xml
- drop-in/src/main/res/values-cs-rCZ/strings.xml
- drop-in/src/main/res/values-da-rDK/strings.xml
- drop-in/src/main/res/values-de-rDE/strings.xml
- drop-in/src/main/res/values-el-rGR/strings.xml
- drop-in/src/main/res/values-es-rES/strings.xml
- drop-in/src/main/res/values-fi-rFI/strings.xml
- drop-in/src/main/res/values-fr-rFR/strings.xml
- drop-in/src/main/res/values-hr-rHR/strings.xml
- drop-in/src/main/res/values-hu-rHU/strings.xml
- drop-in/src/main/res/values-it-rIT/strings.xml
- drop-in/src/main/res/values-ja-rJP/strings.xml
- drop-in/src/main/res/values-ko-rKR/strings.xml
- drop-in/src/main/res/values-nb-rNO/strings.xml
- drop-in/src/main/res/values-nl-rNL/strings.xml
- drop-in/src/main/res/values-pl-rPL/strings.xml
- drop-in/src/main/res/values-pt-rBR/strings.xml
- drop-in/src/main/res/values-pt-rPT/strings.xml
- drop-in/src/main/res/values-ro-rRO/strings.xml
- drop-in/src/main/res/values-ru-rRU/strings.xml
- drop-in/src/main/res/values-sk-rSK/strings.xml
- drop-in/src/main/res/values-sl-rSI/strings.xml
- drop-in/src/main/res/values-sv-rSE/strings.xml
- drop-in/src/main/res/values-zh-rCN/strings.xml
- drop-in/src/main/res/values-zh-rTW/strings.xml
- drop-in/src/main/res/values/strings.xml
- drop-in/src/main/res/values/styles.xml
- Increase touch area of back and close button
- Set content description for back and close button
COAND-950
> Improve toolbar accessibility

- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/MealVoucherComponent.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/MealVoucherComponentCallback.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/MealVoucherComponentState.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/MealVoucherConfiguration.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/SessionsMealVoucherComponentCallback.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/provider/MealVoucherComponentProvider.kt
Created component, provider, configuration and component state classes.
COAND-683
> Create Meal Voucher component and related classes

- README.md
Update support link and include support email in readme.
COAND-948
> Update support contact section in readme

- bcmc/src/main/res/layout/bcmc_view.xml
- card/api/card.api
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardInputData.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardOutputData.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardNumberInput.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/StoredCardView.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
- card/src/main/res/layout/card_view.xml
- card/src/main/res/layout/stored_card_view.xml
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/util/CardValidationUtilsTest.kt
- giftcard/api/giftcard.api
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/view/GiftCardNumberInput.kt
- mealvoucher/api/mealvoucher.api
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/view/MealVoucherView.kt
- mealvoucher/src/main/res/layout/meal_voucher_view.xml
- mealvoucher/src/main/res/values/strings.xml
- mealvoucher/src/main/res/values/styles.xml
- ui-core/api/ui-core.api
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/model/ExpiryDate.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/ExpiryDateInput.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/SecurityCodeInput.kt
Create meal voucher view
COAND-683
> Meal voucher - Create MealVoucherView

- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/action/TwintSdkData.kt
- components-core/src/test/java/com/adyen/checkout/components/core/action/TwintSdkDataTest.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/internal/ui/DefaultTwintActionDelegate.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/internal/ui/TwintActionDelegate.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/internal/ui/TwintActionFragment.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/internal/ui/TwintFlowType.kt
- twint-action/src/test/java/com/adyen/checkout/twint/action/internal/ui/DefaultTwintActionDelegateTest.kt
Add `isStored` flag and use correct flow based on it.
COAND-927
> Twint - isStored flag

- card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/DefaultGiftCardValidator.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardValidator.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/provider/MealVoucherComponentProvider.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/view/MealVoucherView.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidationUtils.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidator.kt
- mealvoucher/src/main/res/values/strings.xml
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationResult.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationUtils.kt
Implement expiry date validation and extract validation logic to `GiftCardValidator`. Implement `MealVoucherValidator` and `DefaultGiftCardValidator` to enable different validation logic for `GiftCardComponent` and `MealVoucherComponent`.
COAND-683
> Meal voucher - Implement expiry date validation and extract validation logic to GiftCardValidator

- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/PaymentMethodDetails.kt
- components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/TwintPaymentMethod.kt
- components-core/src/test/java/com/adyen/checkout/components/core/paymentmethod/TwintPaymentMethodTest.kt
- twint/src/main/java/com/adyen/checkout/twint/TwintComponentState.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegate.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/StoredTwintDelegate.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegateTest.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/StoredTwintDelegateTest.kt
Implement stored twint delegate
COAND-927
> Implement stored twint delegate

- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/DefaultGiftCardValidator.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberValidationResult.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinValidationResult.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardValidationUtils.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidationUtils.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidator.kt
- mealvoucher/src/main/res/values/strings.xml
Improve validation and show different texts for giftcard and mealvoucher
COAND-683
> Meal voucher - Validation improvements

- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/ActionHandlingMethod.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/configuration/CheckoutConfigurationProvider.kt
- instant/api/instant.api
- instant/src/main/java/com/adyen/checkout/instant/ActionHandlingMethod.kt
- instant/src/main/java/com/adyen/checkout/instant/InstantPaymentConfiguration.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/ui/DefaultInstantPaymentDelegate.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/ui/model/InstantComponentParams.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/ui/model/InstantComponentParamsMapper.kt
- instant/src/test/java/com/adyen/checkout/instant/InstantPaymentConfigurationTest.kt
- instant/src/test/java/com/adyen/checkout/instant/internal/ui/model/InstantComponentParamsMapperTest.kt
- twint/api/twint.api
- twint/src/main/java/com/adyen/checkout/twint/TwintConfiguration.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegate.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParams.kt
- twint/src/main/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapper.kt
- twint/src/test/java/com/adyen/checkout/twint/TwintConfigurationTest.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/DefaultTwintDelegateTest.kt
- twint/src/test/java/com/adyen/checkout/twint/internal/ui/model/TwintComponentParamsMapperTest.kt
Add configuration option for Twint to force SDK or WEB flow.
COAND-927
> Twint - SDK/WEB flow configuration

- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- components-core/src/main/java/com/adyen/checkout/components/core/paymentmethod/PaymentMethodDetails.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/provider/GiftCardComponentProvider.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/protocol/DefaultGiftCardProtocol.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/protocol/GiftCardProtocol.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/provider/MealVoucherComponentProvider.kt
- mealvoucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/protocol/MealVoucherProtocol.kt
GiftCardProtocol is responsible for providing details for the differences in Gift Card and Meal Voucher flows such as ComponentViewType or the payment method object.
COAND-693
> Meal Voucher - Create gift card protocol

- .github/ISSUE_TEMPLATE/ask_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Update templates for opening issues.
COAND-842
> Update issue templates

- checkout-core/src/main/java/com/adyen/checkout/core/internal/util/LogcatLogger.kt
- lint/src/main/java/com/adyen/checkout/lint/LintIssueRegistry.kt
- lint/src/main/java/com/adyen/checkout/lint/NotAdyenLog.kt
- lint/src/test/java/com/adyen/checkout/lint/NotAdyenLogTest.kt
Add lint rule to check if we are using the correct logging framework (`adyenLog` and not `Log.x`).
COAND-956
> Add logging lint rule

- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/model/GiftCardComponentParamsMapper.kt
- meal-voucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/model/MealVoucherComponentParamsMapper.kt
Updated class visibilities
COAND-683
> Meal voucher - Update class visibilities

- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInViewModel.kt
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/ui/DropInViewModelTest.kt
- instant/src/main/java/com/adyen/checkout/instant/internal/provider/InstantPaymentComponentProvider.kt
- Add multibanco to supported list
- Add pay by bank to `SKIP_TO_SINGLE_PM_BLOCK_LIST`
- Add iDeal to supported instant payment methods
COAND-972
> Review payment method types

- card/src/main/java/com/adyen/checkout/card/internal/util/CardValidationUtils.kt
- card/src/test/java/com/adyen/checkout/card/internal/util/CardValidationUtilsTest.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtils.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinUtils.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/util/GiftCardNumberUtilsTest.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/util/GiftCardPinUtilsTest.kt
- meal-voucher/src/main/java/com/adyen/checkout/mealvoucher/internal/util/MealVoucherValidationUtils.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationResult.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationUtils.kt
- ui-core/src/test/java/com/adyen/checkout/ui/core/internal/util/ExpiryDateValidationUtilsTest.kt
Add tests for giftcard and mealvoucher util classes
COAND-693
> Meal vouchers - Add tests - Utils

- .github/ISSUE_TEMPLATE/ask_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Fixing labels as they are case sensitive.
COAND-842
> Fix labels in templates

- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardComponent.kt
- meal-voucher/build.gradle
- meal-voucher/src/test/java/com/adyen/checkout/mealvoucher/MealVoucherComponentTest.kt
- meal-voucher/src/test/java/com/adyen/checkout/mealvoucher/MealVoucherConfigurationTest.kt
- meal-voucher/src/test/java/com/adyen/checkout/mealvoucher/internal/ui/model/MealVoucherComponentParamsMapperTest.kt
Add `MealVoucherComponentTest`, `MealVoucherComponentParamsMapperTest`, `MealVoucherConfigurationTest`.
COAND-693
> Meal Voucher - Add component, configuration and params mapper tests

- giftcard/src/main/java/com/adyen/checkout/giftcard/GiftCardAction.kt
- meal-voucher/src/main/java/com/adyen/checkout/mealvoucher/MealVoucherComponent.kt
- meal-voucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/MealVoucherViewProvider.kt
- meal-voucher/src/main/java/com/adyen/checkout/mealvoucher/internal/ui/view/MealVoucherView.kt
Fix and remove todos.
COAND-693
> Meal Voucher - Fix remaining todos

- docs/payment-methods/GIFT_CARD.md
- docs/payment-methods/README.md
- Add documentations for gift cards.
COAND-693
> Meal voucher - Add gift card documentation

- README.md
- RELEASE_NOTES.md
Put reference to Adyen Test Cards in the README and release notes.
COAND-1001
> Document Adyen Test Cards

- docs/payment-methods/README.md
Add Twint to payment methods docs readme.
> Add Twint to payment methods docs readme

- meal-voucher-fr/src/main/java/com/adyen/checkout/mealvoucherfr/internal/ui/view/MealVoucherFRView.kt
Remove the end margin of expiry date when security code is not required and therefore hidden.
COAND-683
> Fix layout alignment issue when security code is hidden in meal vouchers

- README.md
- RELEASE_NOTES.md
- dependencies.gradle
- example-app/build.gradle
> Prepare release 5.7.0

- README.md
Update drop-in preview screenshots in README.md.
> Update drop-in preview screenshots in readme

- components-core/src/main/java/com/adyen/checkout/components/core/AnalyticsConfiguration.kt
Add link in `AnalyticsLevel` to the docs section explaining the [data we are collecting](https://docs.adyen.com/online-payments/analytics-and-data-tracking/#data-we-are-collecting).
COAND-980
> Link to docs in analytics level

- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2DelegateTest.kt
- 3ds2/src/test/java/com/adyen/checkout/adyen3ds2/internal/ui/SharedChallengeStatusHandlerTest.kt
- gradle/libs.versions.toml
Uncomment 3DS2 tests that were previously failing because of obfuscation.
COAND-1011
> Uncomment previously failing 3DS2 tests

- README.md
Replace prefill with autofill in readme to provide a more accurate description of the test cards app's functionality.
COAND-1001
> Replace prefill with autofill for test cards app in readme

- scripts/version_name.sh
Change the `version_name.sh` script to read the version name from version catalogs.
COAND-977
> Version catalogs - Fix version name script

- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodTypes.kt
- paybybank-us/api/paybybank-us.api
- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/PayByBankUSConfiguration.kt
- paybybank-us/src/test/java/com/adyen/checkout/paybybankus/PayByBankUSConfigurationTest.kt
Add configuration class implementation.
COAND-974
> Pay By Bank US - Implement configuration

- .github/workflows/check.yml
- .github/workflows/create_github_release.yml
- .github/workflows/publish_release.yml
- .github/workflows/publish_to_maven_central.yml
Break release job apart into multiple jobs.
[Here](https://github.com/Adyen/adyen-android/actions/runs/11572437317) is a workflow run which demonstrated how it looks.
COAND-1013
> Release - Break release job apart

- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/PayByBankUSComponent.kt
Implement `PayByBankUSComponent`.
COAND-974
> Pay By Bank US - Component

- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/DefaultPayByBankUSDelegate.kt
Implement `DefaultPayByBankUSDelegate`.
COAND-974
> Pay By Bank US - Delegate

- cashapppay/src/main/java/com/adyen/checkout/cashapppay/internal/ui/view/CashAppPayButtonView.kt
- components-core/api/components-core.api
- components-core/src/main/java/com/adyen/checkout/components/core/ComponentAvailableCallback.kt
- components-core/src/main/java/com/adyen/checkout/components/core/PaymentMethodUnavailableException.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/compose/ResultContent.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/compose/ResultState.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/compose/SessionsGooglePayViewModel.kt
- googlepay/api/googlepay.api
- googlepay/src/main/java/com/adyen/checkout/googlepay/GooglePayUnavailableException.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/provider/GooglePayComponentProvider.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayButtonView.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/GooglePayDelegate.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/model/GooglePayOutputData.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/util/GooglePayAvailabilityCheck.kt
- googlepay/src/test/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegateTest.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/AdyenComponentView.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/DefaultPayButton.kt
- ui-core/src/main/java/com/adyen/checkout/ui/core/internal/ui/view/PayButton.kt
Check Google Pay availability when initialising the component. If unavailable, the button will be hidden.
COAND-943
> Google Pay availability check

- .github/workflows/create_github_release.yml
The release action is changed, since the action we used was not maintained. The new action will allow us to make updates in the future.
COAND-1013
> Release - Change release action

- .github/workflows/finalize_release.yml
Publish the draft release for a specific tag, create the tag and delete the branch.
COAND-1015
> Release - Publish release and delete branch

- drop-in/api/drop-in.api
- drop-in/build.gradle
- drop-in/src/main/java/com/adyen/checkout/dropin/DropInConfiguration.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/provider/ComponentProvider.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodAdapter.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodsListViewModel.kt
- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/model/PaymentMethodModel.kt
- drop-in/src/main/res/layout/payment_methods_list_item.xml
- drop-in/src/main/res/template/values/strings.xml.tt
- drop-in/src/main/res/values/strings.xml
- drop-in/src/test/java/com/adyen/checkout/dropin/internal/Helpers.kt
- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/ui/model/PayByBankUSBrandLogo.kt
Include the module in drop-in and display the brand logos in payment methods list.
COAND-974
> Pay by Bank US - Drop-in

- ach/src/main/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegate.kt
- ach/src/test/java/com/adyen/checkout/ach/internal/ui/DefaultACHDirectDebitDelegateTest.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
- giftcard/src/main/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegate.kt
- giftcard/src/test/java/com/adyen/checkout/giftcard/internal/ui/DefaultGiftCardDelegateTest.kt
Track errors triggered by encryption failures.
COAND-1008
> Analytics - Encryption Errors

- RELEASE_NOTES.md
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardInputData.kt
> AddressLookup - Fix view not retaining correct input state

- paybybank-us/src/test/java/com/adyen/checkout/paybybankus/PayByBankUSComponentTest.kt
- paybybank-us/src/test/java/com/adyen/checkout/paybybankus/internal/ui/DefaultPayByBankUSDelegateTest.kt
Add `PayByBankUSComponentTest` and `DefaultPayByBankUSDelegateTest`.
COAND-974
> Pay by Bank US - Component & Delegate Tests

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/PaymentMethodsListViewModel.kt
- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/DefaultPayByBankUSDelegate.kt
Display 4 logos on the payment methods list item.
COAND-974
> Pay by Bank - Align number of logos in Payment Methods List with iOS

- docs/payment-methods/GOOGLE_PAY.md
- example-app/src/main/java/com/adyen/checkout/example/ui/googlepay/GooglePayViewModel.kt
- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
Add documentation on Google Pay + a migration guide for the new implementation
COAND-941
> Google Pay docs

- README.md
- example-app/build.gradle
- gradle/libs.versions.toml
> Bump version to 5.7.1

- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/DefaultPayByBankUSDelegate.kt
- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/PayByBankUSDelegate.kt
- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/StoredPayByBankUSDelegate.kt
- paybybank-us/src/main/java/com/adyen/checkout/paybybankus/internal/provider/PayByBankUSComponentProvider.kt
- paybybank-us/src/test/java/com/adyen/checkout/paybybankus/internal/ui/StoredPayByBankUSDelegateTest.kt
Add tests for `StoredPayByBankUSDelegate` and remove `ButtonDelegate` and `UIStateDelegate` from common `PayByBankUSDelegate`. 
COAND-974
> Pay by Bank US - Stored Delegate Tests

- .github/workflows/create_release_notes_pr.yml
- .github/workflows/generate_release_notes.yml
- scripts/create_release_notes_pr.sh
- scripts/generate_release_notes.sh
- Create a new branch for the release notes (`x.x.x`)
- Fetch the generated release notes from artifacts and commit them to the newly created branch
- Open a PR to the `release-notes` branch.
Example of the workflow run can be found [here](https://github.com/Adyen/adyen-testcards-android/actions/runs/12031704620/job/33541857137) and the created PR [here](https://github.com/Adyen/adyen-testcards-android/pull/34).
COAND-1033
> Release process - Create release notes pr

- .github/workflows/publish_release.yml
Mark release as draft in publish release job to help testing before publishing.
> Mark release as draft in publish release job

- drop-in/src/main/java/com/adyen/checkout/dropin/internal/ui/DropInActivity.kt
Make sure the loading fragment transaction is completed before trying to dismiss it. This fixes a crash that happened when opening instant payment methods in drop-in.
COAND-984
> Fix crash when opening instant pm in drop-in

- README.md
- RELEASE_NOTES.md
- example-app/build.gradle
- gradle/libs.versions.toml
> Prepare release 5.8.0

- googlepay/src/main/java/com/adyen/checkout/googlepay/internal/ui/DefaultGooglePayDelegate.kt
- twint-action/src/main/java/com/adyen/checkout/twint/action/internal/ui/DefaultTwintActionDelegate.kt
Add messages for error events which are being tracked more than once
COAND-1047
> Analytics - Add message for error events

- .github/workflows/update_release_notes.yml
- scripts/fetch_release_notes_version_name.sh
- scripts/fetch_updated_release_notes_file.sh
Add updating release notes for github release after merging the release notes changes pull request to `release-notes` branch. 
1. It requires release notes file to be placed in project root direct directory with the following name pattern: `<VERSION_NAME>.md // ex. 1.2.3.md`
2. It requires the branch for updating release notes to be named in the following format: `release-notes/<version_name>`
3. It fetches the version name from the head commit, which we expect it to be the merge commit from a branch that is named `release-notes/<version_name>`. (`fetch_version_name` step)
4. It fetches the file path …
> Release - Add update release notes script

- scripts/create_release_notes_pr.sh
Update PR description for release notes, which looks more descriptive and has requirement checkboxes.
COAND-1054
> Release - Update PR description for release notes

- .github/workflows/finalize_release.yml
- .github/workflows/publish_docs.yml
Publish docs as part of finalize_release workflow, instead of with every merge to main
COAND-1019
> Release - Publish docs as part of finalize_release workflow

- README.md
Add SDK lifecycle section to readme.
> Add SDK lifecycle section to readme

- .github/workflows/publish_release.yml
Change OSSRH token for V4
COAND-1022
> V4 - Change OSSRH token

- payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/PayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToInputData.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToOutputData.kt
- payto/src/test/java/com/adyen/checkout/payto/internal/DefaultPayToDelegateTest.kt
Add delegate implementation for PayTo. More tests and function will be added when we add new field in the view.
COAND-1058
> PayTo - Add PayToDelegate implementation

- README.md
Update broken badge link in readme, it now links to the Check Main workflow.
> Update broken badge in readme

- payto/api/payto.api
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/DefaultPayToDelegate.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/model/PayToMode.kt
- payto/src/main/java/com/adyen/checkout/payto/internal/ui/view/PayToView.kt
- payto/src/main/res/layout/payto_view.xml
- payto/src/main/res/values/strings.xml
- payto/src/main/res/values/styles.xml
Add views for the PayTo implementation. The PayId type selector will be populated later.
COAND-1058
> PayTo - View layout implementation

- card-scanning/api/card-scanning.api
- card-scanning/build.gradle
- card-scanning/src/main/java/com/adyen/checkout/card/scanning/AdyenCardScanner.kt
- card-scanning/src/main/java/com/adyen/checkout/card/scanning/AdyenCardScannerResult.kt
Create and implement card scanner class. Testing can and will be done in a later stage.
COAND-429
> [Card scanning] Setup scanner

- .github/workflows/check_dependency_changes.yml
- .github/workflows/check_pr.yml
- scripts/check_dependency_changes.py
Updating our dependencies often indirectly updates other transitive dependencies without giving us much visibility on the changes. This PR aims to improve visibility over these transitive dependency updates.
Workflow:
- On every PR check, the `dependencyList` task is called at the base and head of the branch. This task generates a full list of runtime dependencies used by all the modules that we publish.
- The results are then compared and if changes are found, they will be posted in a comment on the PR.
- The workflow will also add a PR review comment to alert the developers of these changes. This comment will block the PR from being accidentally merged without addressing the changes.
> Show dependency changes in every PR

- .github/workflows/finalize_release.yml
This change makes the finalize_release steps to run sequentially
COAND-1072
> Fix finalize_release workflow

- README.md
Fix lifecycle state of v3 in readme from deprecated to end-of life.
> Fix lifecycle state of v3 in readme

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/ErrorEvent.kt
Use correct error codes for public key and native redirect events.
COAND-1081
> Use correct error codes for public key and native redirect events

- payto/src/main/res/values-da-rDK/strings.xml
- payto/src/main/res/values-de-rDE/strings.xml
- payto/src/main/res/values-es-rES/strings.xml
- payto/src/main/res/values-fi-rFI/strings.xml
- payto/src/main/res/values-it-rIT/strings.xml
- payto/src/main/res/values-pl-rPL/strings.xml
- payto/src/main/res/values-pt-rBR/strings.xml
- payto/src/main/res/values-pt-rPT/strings.xml
- payto/src/main/res/values-sv-rSE/strings.xml
- payto/src/main/res/values-zh-rTW/strings.xml
- payto/src/main/res/values/strings.xml
Some of the translations got adjusted to keep the format consistent
COAND-1058
> PayTo - Fix translations

- card-scanning/api/card-scanning.api
- card-scanning/src/main/java/com/adyen/checkout/card/scanning/AdyenCardScanner.kt
- card/src/main/java/com/adyen/checkout/card/internal/analytics/CardEvents.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/CardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardScanningFragment.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/CardScannerWrapper.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/AnalyticsEvent.kt
Add analytics for card scanning. See the ticket for more details. The API did not add the events yet, so it returns an error currently.
COAND-1082
> Card scanning analytics

- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/state/DefaultDelegateStateManager.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/ui/model/state/DelegateStateManager.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/state/DefaultDelegateStateManagerTest.kt
- components-core/src/test/java/com/adyen/checkout/components/core/internal/ui/model/state/TestFieldId.kt
- Add updateState() function to allow updating non inout field state values, which in turn triggers revalidation of fields.
COAND-935
> State management changes - MBWay - Add updateState() function

- ui/api/ui.api
- ui/src/main/java/com/adyen/checkout/ui/internal/DefaultColors.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenButtonStyles.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenCheckoutTheme.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenColors.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenElements.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenSegmentedButtonStyle.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenSwitchStyle.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenTextFieldStyle.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenTextStyles.kt
Create base structure for the UI theme. This allows for customization and forms the base for our design system.
COAND-1084
> Setup UI theme

- ui/api/ui.api
- ui/build.gradle
- ui/src/main/java/com/adyen/checkout/ui/internal/AdyenCheckoutTheme.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/InternalColors.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/Text.kt
- Define base composable theme
- Add text composable for every text style
COAND-1084
> Setup text composables

- core/api/core.api
- core/build.gradle
- core/src/main/java/com/adyen/checkout/core/AdyenPaymentFlow.kt
- core/src/main/java/com/adyen/checkout/core/internal/AdyenComponent.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/PaymentDelegate.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/view/PayButton.kt
- ui/build.gradle
Add submit to AdyenComponent.
COAND-1073
> v6 - Submit

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/DefaultDelegateStateManager.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/DelegateState.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/DelegateStateFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/DelegateStateManager.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/FieldChangeListener.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/FieldId.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/model/DelegateFieldState.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/model/FieldId.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/model/Validation.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/model/ViewFieldState.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/transformer/DefaultTransformer.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/transformer/DefaultTransformerRegistry.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/transformer/FieldTransformer.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/transformer/FieldTransformerRegistry.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/updater/StateUpdater.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/updater/StateUpdaterRegistry.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/validator/DefaultValidator.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/validator/FieldValidator.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/validator/FieldValidatorRegistry.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/view/MbWayComponent.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/state/MBWayFieldId.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/view/MbWayComponent.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/AdyenCheckoutTheme.kt
Add core implementation of the state management
COAND-1073
> v6 - Add initial state management

- core/build.gradle
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/DefaultDelegateStateManagerTest.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/DelegateFieldStateTest.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/TestDelegateState.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/TestDelegateStateFactory.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/TestFieldId.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/TestFieldTransformerRegistry.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/TestFieldValidatorRegistry.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/TestStateUpdaterRegistry.kt
Add tests for initial state management
COAND-1084
> v6 - Add initial state management - Tests

- core/build.gradle
- core/src/main/java/com/adyen/checkout/core/internal/ui/state/model/Validation.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayDelegate.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayDelegateStateFactory.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayDelegateState.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayStateUpdaterRegistry.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayTransformerRegistry.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayValidatorRegistry.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayViewState.kt
- core/src/test/java/core/adyen/checkout/core/mbway/internal/MBWayDelegateStateFactoryTest.kt
- core/src/test/java/core/adyen/checkout/core/mbway/internal/model/MBWayStateUpdaterRegistryTest.kt
- core/src/test/java/core/adyen/checkout/core/mbway/internal/model/MBWayTransformerRegistryTest.kt
- core/src/test/java/core/adyen/checkout/core/mbway/internal/model/MBWayValidatorRegistryTest.kt
Add state management for MBWayDelegate
COAND-1073
> v6 - Add state management for MBWayDelegate

- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/DefaultAnalyticsManager.kt
Fixes the crash mentioned in #2091 and #2092.
We suspect that coroutineScope is null because `onCleared()` gets called in the Component level, but analytics manager tries to track some failure events for api calls running in the background when `onCleared()` is called. This change removes the requirement for non-nullability to avoid crashes as a workaround at the moment.
COAND-1088
[//]: # (Use the headers listed below to organize your release notes. Each section should begin with ### followed by a valid label)
[//]: # (Allowed labels: `Breaking changes`, `New`, `Fixed`, `Improved`, `Changed`, …
> Fix crash in DefaultAnalyticsManager

- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardBrandItem.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardBrandAdapter.kt
- card/src/main/res/layout/card_brand_item.xml
- card/src/main/res/values/styles.xml
Add adapter for brand selection section.
COAND-1085
> Co-badged Cards - Adapter

- core/src/main/java/com/adyen/checkout/core/AdyenPaymentFlow.kt
- core/src/main/java/com/adyen/checkout/core/internal/AdyenComponent.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayDelegate.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/view/MbWayComponent.kt
- core/src/test/java/core/adyen/checkout/core/internal/ui/state/DelegateFieldStateTest.kt
Add viewState for the new MbWay component
COAND-1073
> v6 - Add viewState for MBWayDelegate

- card/api/card.api
- card/src/main/java/com/adyen/checkout/card/internal/data/model/DetectedCardType.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardBrandItem.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardInputData.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/model/CardOutputData.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardBrandAdapter.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/view/CardView.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/DetectedCardTypesUtils.kt
- card/src/main/res/layout/card_view.xml
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
Use `CardBrandAdapter` in `CardView` to display brand options.
COAND-1085
> Co-badged Cards - Display card brand options

- card/src/main/java/com/adyen/checkout/card/internal/data/api/DefaultDetectCardTypeRepository.kt
- card/src/main/java/com/adyen/checkout/card/internal/data/model/Brand.kt
- card/src/main/java/com/adyen/checkout/card/internal/data/model/DetectedCardType.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/StoredCardDelegate.kt
- card/src/test/java/com/adyen/checkout/card/internal/data/api/TestDetectCardTypeRepository.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/ui/StoredCardDelegateTest.kt
- card/src/test/java/com/adyen/checkout/card/internal/util/DualBrandedCardUtilsTest.kt
Use localized brand name provided in the `BinLookupResponse` as brand name display value.
COAND-1085
> Co-badged Cards - Display localeBrand from BinLookupResponse

- example-app/src/main/java/com/adyen/checkout/example/data/api/model/ThreeDSRequestData.kt
- example-app/src/main/java/com/adyen/checkout/example/service/RequestUtils.kt
Add support for redirect 3DS flow on sessions in the example app.
> Add support for redirect 3DS flow on sessions

- .github/pull_request_template.md
- config/git/commit-template
Use `COSDK` in templates instead of `COAND`.
> Update commit and pr template to have COSDK instead of COAND

- card/src/main/java/com/adyen/checkout/card/internal/ui/CardConfigDataGenerator.kt
- card/src/main/java/com/adyen/checkout/card/internal/ui/DefaultCardDelegate.kt
- card/src/main/java/com/adyen/checkout/card/internal/util/DualBrandedCardHandler.kt
- components-core/src/main/java/com/adyen/checkout/components/core/internal/analytics/GenericEvents.kt
Analytics events for co-badged cards.
COAND-1085
> Co-badged Cards: Analytics

- card/src/main/res/layout/card_brand_item.xml
- card/src/main/res/values/styles.xml
Radio buttons were not correctly aligned on the end of the layout. This fixes the layout.
COSDK-30
> Co-badged Cards: Fix padding issue of radio buttons

- .gitignore
Ignore `.kotlin` folder in git.
> Add .kotlin folder to gitignore

- .github/ISSUE_TEMPLATE/ask_question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/add_pr_label.yml
- .github/workflows/check_v5.yml
- .github/workflows/codeql.yml
- .github/workflows/run_ui_tests.yml
- README.md
- docs/UI_CUSTOMIZATION.md
- scripts/validate_dependencies_for_release_notes.py
Adjust scripts, workflows and links to make v5 branch functional.
Release process is tested in [this workflow run](https://github.com/Adyen/adyen-android/actions/runs/15461234867).
COSDK-487
> v5 - Update scripts, workflows and documentation links

- core/src/main/java/com/adyen/checkout/core/AdyenPaymentFlow.kt
- core/src/main/java/com/adyen/checkout/core/internal/AdvancedComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/internal/AdvancedPaymentFacilitatorFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/AdyenComponent.kt
- core/src/main/java/com/adyen/checkout/core/internal/BaseComponentState.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentComponentEvent.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitatorFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentFacilitatorProvider.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentMethodFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/PaymentMethodProvider.kt
- core/src/main/java/com/adyen/checkout/core/internal/SessionsPaymentFacilitatorFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/EventDelegate.kt
- core/src/main/java/com/adyen/checkout/core/internal/ui/PaymentDelegate.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayFactory.kt
Add `PaymentMethodProvider` class to instantiate payment methods by `txVariant`.
COSDK-482
> v6 - Add PaymentMethodProvider

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/internal/analytics/AnalyticsManagerFactory.kt
- core/src/main/java/com/adyen/checkout/core/internal/analytics/data/remote/DefaultAnalyticsSetupProvider.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayComponentState.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayDelegate.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/MBWayFactory.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayStateUpdaterRegistry.kt
- core/src/main/java/com/adyen/checkout/core/mbway/internal/ui/model/MBWayValidatorRegistry.kt
- core/src/main/java/com/adyen/checkout/core/paymentmethod/PaymentComponentState.kt
- core/src/test/java/com/adyen/checkout/core/internal/analytics/TestAnalyticsManager.kt
Now componentState is generated from delegate state
COSDK-505
> V6 - MBWay - Generate componentState from delegate state

- scripts/drop_all_open_ossrh_repositories.py
- scripts/move_ossrh_repository_to_central_portal.py
Clean up scripts to reduce logging, in case sensitive data gets logged
COSDK-516
> Sonatype - Clean up scripts

- README.md
- SUPPORT.md
Update support URL in Readme
COSDK-535
> V5 - Update Support URL in README.md 

- .github/workflows/create_github_release.yml
- .github/workflows/finalize_release.yml
Now the tag will be generated correctly, since we provide the commit hash to the release action
COSDK-541
> V5 - Release - Add the commit to the release action

- .github/workflows/create_github_release.yml
- .github/workflows/finalize_release.yml
Now the tag will be generated correctly, since we provide the commit hash to the release action
COSDK-541
> V6 - Release - Add the commit to the release action

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/action/data/Action.kt
- core/src/main/java/com/adyen/checkout/core/sessions/SessionPaymentResult.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionCallResult.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/data/model/SessionPaymentsResponse.kt
- Move action related classes to core
- Return a result for submitPayment in SessionInteractor
COSDK-480
> V6 - Action - Move action to core

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/components/CheckoutResult.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/ComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandler.kt
- Move result handling out of the event handlers to PaymentFacilitator
COSDK-480
> V6 - Action - Move result handling to payment facilitator

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/components/AdyenPaymentFlow.kt
- core/src/main/java/com/adyen/checkout/core/components/CheckoutController.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedPaymentFacilitatorFactory.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdyenComponent.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitatorProvider.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsPaymentFacilitatorFactory.kt
- lint/src/main/java/com/adyen/checkout/lint/ObjectInPublicSealedClass.kt
- lint/src/test/java/com/adyen/checkout/lint/ObjectInPublicSealedClassTest.kt
Introduce basic implementation of checkout controller. This is used by merchants to control the checkout flow.
The `ObjectInPublicSealedClass` was updated as well to correctly check parent visibility.
COSDK-511
> v6 - Checkout controller

- .github/workflows/add_pr_label.yml
This PR wraps  `branch_name` parameter with quote marks for extra security.
COSDK-558
> Escape branch name in add_pr_label.yml

- core/src/main/java/com/adyen/checkout/core/analytics/internal/DefaultAnalyticsManager.kt
- core/src/main/java/com/adyen/checkout/core/analytics/internal/data/DefaultAnalyticsRepository.kt
- core/src/main/java/com/adyen/checkout/core/common/internal/api/HttpClientExt.kt
- core/src/main/java/com/adyen/checkout/core/common/internal/model/JsonUtils.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/model/SessionParamsFactory.kt
- core/src/testFixtures/java/com/adyen/checkout/test/LoggingExtension.kt
Remove `TODO`s we had left for commented out `adyenLog` statements.
COSDK-512
> v6 - Remove AdyenLogger related TODOs

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/components/internal/AdyenComponent.kt
- core/src/main/java/com/adyen/checkout/core/sessions/CheckoutSession.kt
- core/src/main/java/com/adyen/checkout/core/sessions/SessionPaymentResult.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/CheckoutSessionInitializer.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/CheckoutSessionProvider.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/data/api/SessionRepository.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/data/model/SessionSetupRequest.kt
- core/src/test/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandlerTest.kt
- mbway/src/main/java/com/adyen/checkout/mbway/MBWayConfiguration.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayFactory.kt
Clean up some of the `TODO`s that are already done.
> v6 - Clean up done TODOs

- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayComponent.kt
- ui/api/ui.api
- ui/src/main/java/com/adyen/checkout/ui/internal/AdyenCheckoutTheme.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/AdyenTextFieldDefaults.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/Buttons.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/Stepper.kt
- ui/src/main/java/com/adyen/checkout/ui/internal/Switch.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenButtonStyles.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenCheckoutTheme.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/AdyenElements.kt
- ui/src/main/java/com/adyen/checkout/ui/theme/CheckoutAttributes.kt
Create new `attributes` object in the theming structure. This will make the API more straightforward and intuitive.
Here is an overview of how it is now
COSDK-147
> v6 - Update theme structure

- README.md
> V6 - Update readme

- .github/workflows/codeql.yml
Apply change in #2258 to v5.
COSDK-578
> v5 - Include GitHub actions analysis

- .github/workflows/codeql.yml
Enable CodeQL to scan GitHub Actions for known vulnerabilities.
> Include GitHub actions analysis

- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitComponent.kt
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionComponentEvent.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentComponentEvent.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/ui/EventComponent.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/ui/PaymentComponent.kt
- core/src/test/java/com/adyen/checkout/core/action/internal/TestActionComponent.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayComponent.kt
Added action component event and cleaned MBWayComponent from unnecessary extension.
COSDK-547
> V6 - Await - Add action component event

- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitComponent.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitFactory.kt
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionComponent.kt
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionComponentProvider.kt
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionFactory.kt
- core/src/test/java/com/adyen/checkout/core/action/internal/ActionComponentProviderTest.kt
- core/src/test/java/com/adyen/checkout/core/action/internal/TestActionComponent.kt
Add await factory implementation
COSDK-547
> V6 - Await - Await factory

- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitComponent.kt
- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionComponentEvent.kt
- core/src/main/java/com/adyen/checkout/core/components/CheckoutCallbacks.kt
- core/src/main/java/com/adyen/checkout/core/components/CheckoutResult.kt
- core/src/main/java/com/adyen/checkout/core/components/ComponentError.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandler.kt
- core/src/test/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandlerTest.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6ViewModel.kt
Implement error events for Await action
COSDK-547
> V6 - Await - Error event

- .github/workflows/add_pr_label.yml
- .github/workflows/assemble.yml
- .github/workflows/check.yml
- .github/workflows/check_dependency_changes.yml
- .github/workflows/check_labels.yml
- .github/workflows/check_pr.yml
- .github/workflows/check_v5.yml
- .github/workflows/code_analysis.yml
- .github/workflows/create_github_release.yml
- .github/workflows/create_release_notes_pr.yml
- .github/workflows/finalize_release.yml
- .github/workflows/generate_dependency_graph.yml
- .github/workflows/generate_release_notes.yml
- .github/workflows/generate_version_name.yml
- .github/workflows/get_dependency_list.yml
- .github/workflows/prepare_release.yml
- .github/workflows/publish_docs.yml
- .github/workflows/publish_to_maven_central.yml
- .github/workflows/run_tests.yml
- .github/workflows/run_ui_tests.yml
- .github/workflows/sonar_cloud.yml
- .github/workflows/stale_issues.yml
- .github/workflows/update_release_notes.yml
- .github/workflows/update_verification_metadata.yml
- .github/workflows/validate_dependencies.yml
- .github/workflows/validate_public_api.yml
Add minimal permissions to all workflows. This was copied from the main branch.
COSDK-583
> v5 - Workflow permissions

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/common/PaymentResult.kt
- core/src/main/java/com/adyen/checkout/core/components/Checkout.kt
- core/src/main/java/com/adyen/checkout/core/components/CheckoutCallbacks.kt
- core/src/main/java/com/adyen/checkout/core/components/CheckoutContext.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedComponentCallbacks.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/AdvancedPaymentFacilitatorFactory.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/SessionsComponentCallbacks.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandler.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsPaymentFacilitatorFactory.kt
- core/src/test/java/com/adyen/checkout/core/sessions/internal/SessionsComponentEventHandlerTest.kt
- example-app/src/main/java/com/adyen/checkout/example/ui/v6/V6SessionsViewModel.kt
Improve `CheckoutCallbacks` class to support advanced and sessions flow by making it a common callback class that could translate itself into `AdvancedComponentCallbacks` or `SessionsComponentCallbacks` internally. 
COSDK-144
> v6 - Unify callbacks for advanced and sessions flows

- 3ds2/src/main/java/com/adyen/checkout/adyen3ds2/internal/ui/DefaultAdyen3DS2Delegate.kt
The changes are cherry picked from #2298 to keep v6 and v5 in sync
> v6 - Fix 3ds2 cancel button

- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitComponent.kt
- await/src/main/java/com/adyen/checkout/await/internal/ui/AwaitFactory.kt
- core/src/main/java/com/adyen/checkout/core/action/internal/ActionComponent.kt
- core/src/main/java/com/adyen/checkout/core/common/internal/helper/ContextExtensions.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/PaymentFacilitator.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/ui/PaymentComponent.kt
- core/src/test/java/com/adyen/checkout/core/action/internal/ActionComponentProviderTest.kt
- core/src/test/java/com/adyen/checkout/core/action/internal/TestActionComponent.kt
- core/src/test/java/com/adyen/checkout/core/components/internal/PaymentMethodProviderTest.kt
- core/src/test/java/com/adyen/checkout/core/components/internal/ui/TestPaymentComponent.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/MBWayComponent.kt
Override LocalContext to provide localized context to be used for localization.
COSDK-146
> v6 - Override LocalContext with localized context

- core/api/core.api
- core/src/main/java/com/adyen/checkout/core/common/localization/CheckoutLocalizationKey.kt
- core/src/main/java/com/adyen/checkout/core/common/localization/internal/DefaultLocalizationSource.kt
- core/src/main/java/com/adyen/checkout/core/components/internal/ui/state/model/TextInputState.kt
- core/src/main/res/values/strings.xml
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/state/MBWayViewStateValidator.kt
- mbway/src/main/java/com/adyen/checkout/mbway/internal/ui/view/MbWayComponent.kt
- mbway/src/test/java/com/adyen/checkout/mbway/internal/ui/state/MBWayViewStateValidatorTest.kt
Add localization for the MBWay component
COSDK-632
> V6 - Localization - MBWay

- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionInteractor.kt
- core/src/main/java/com/adyen/checkout/core/sessions/internal/SessionsPaymentFacilitatorFactory.kt
Add analytics for SessionInteractor 
COSDK-631
> V6 - Analytics - SessionInteractor
